MODULE MODE_GRADIENT_M_PHY_MANYBLOCKS


IMPLICIT NONE



CONTAINS
SUBROUTINE GZ_M_W_PHY_MANYBLOCKS (D, PY, PDZZ, PGZ_M_W, LDACC, KGPBLKS)
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PDZZ(D%NIT, D%NJT, D%NKT, KGPBLKS)
REAL, INTENT (IN)::PY(D%NIT, D%NJT, D%NKT, KGPBLKS)
REAL, INTENT (OUT)::PGZ_M_W(D%NIT, D%NJT, D%NKT, KGPBLKS)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
INTEGER::IKL
INTEGER::IKU
INTEGER::IKA
INTEGER::IJE
INTEGER::IIE
INTEGER::IJB
INTEGER::IIB
INTEGER::IKTE
INTEGER::IKTB
INTEGER::IKT
INTEGER::JK
INTEGER::JJ
INTEGER::JI
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PDZZ, PGZ_M_W, PY) 


IKT=D%NKT
IKTB=D%NKTB
IKTE=D%NKTE
IIE=D%NIEC
IIB=D%NIBC
IJE=D%NJEC
IJB=D%NJBC
IKT=D%NKT
IKA=D%NKA
IKU=D%NKU
IKL=D%NKL

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JJ, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=IKTB, IKTE

      DO JJ=IJB, IJE
        
        PGZ_M_W (JI, JJ, JK, JBLK)=(PY (JI, JJ, JK, JBLK)-PY (JI, JJ, JK-IKL, JBLK))/PDZZ (JI, JJ, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDDO


DO JJ=IJB, IJE
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      
      PGZ_M_W (JI, JJ, IKU, JBLK)=(PY (JI, JJ, IKU, JBLK)-PY&
      & (JI, JJ, IKU-IKL, JBLK))/PDZZ (JI, JJ, IKU, JBLK)
      PGZ_M_W (JI, JJ, IKA, JBLK)=PGZ_M_W (JI, JJ, IKU, JBLK)
    
    ENDDO

  ENDDO

ENDDO


!$ACC END DATA
END SUBROUTINE GZ_M_W_PHY_MANYBLOCKS

SUBROUTINE GX_M_M_PHY_MANYBLOCKS (D, OFLAT, PA, PDXX, PDZZ, PDZX, PGX_M_M, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODE_SHUMAN_PHY,ONLY:MXF_PHY, MXM_PHY, DXF_PHY, DZM_PHY, MZF_PHY
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MZF_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MXM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MXF_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : DZM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : DXF_PHY_MANYBLOCKS
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(D%NIT, D%NJT, D%NKT, KGPBLKS)
REAL, INTENT (IN)::PDXX(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PDZZ(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PDZX(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
LOGICAL, INTENT (IN)::OFLAT
REAL, INTENT (OUT)::PGX_M_M(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL::ZMXF_PDXX(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK6(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK5(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK4(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK3(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK2(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK1(D%NIT, D%NJT, D%NKT,KGPBLKS)
INTEGER::IKT
INTEGER::IJE
INTEGER::IIE
INTEGER::IJB
INTEGER::IIB
INTEGER::JK
INTEGER::JJ
INTEGER::JI
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&CREATE (ZMXF_PDXX, ZWORK1, ZWORK2, ZWORK3, ZWORK4, ZWORK5, ZWORK6) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PDXX, PDZX, PDZZ, PGX_M_M) 

IF (LHOOK) CALL DR_HOOK ('GX_M_M_MANYBLOCKS', 0, ZHOOK_HANDLE)
IIE=D%NIEC
IIB=D%NIBC
IJE=D%NJEC
IJB=D%NJBC
IKT=D%NKT
CALL MXF_PHY_MANYBLOCKS (D, PDXX, ZMXF_PDXX, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MXM_PHY_MANYBLOCKS (D, PA, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL DXF_PHY_MANYBLOCKS (D, ZWORK1, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)

CALL DZM_PHY_MANYBLOCKS (D, PA, ZWORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MXF_PHY_MANYBLOCKS (D, PDZX, ZWORK4, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JJ, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT

      DO JJ=IJB, IJE
        
        ZWORK5 (JI, JJ, JK, JBLK)=ZWORK3 (JI, JJ, JK, JBLK)*ZWORK4&
        & (JI, JJ, JK, JBLK)/PDZZ (JI, JJ, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDDO

CALL MZF_PHY_MANYBLOCKS (D, ZWORK5, ZWORK6, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JJ, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT

      DO JJ=IJB, IJE
        
        PGX_M_M (JI, JJ, JK, JBLK)=(ZWORK2 (JI, JJ, JK, JBLK)-ZWORK6&
        & (JI, JJ, JK, JBLK))/ZMXF_PDXX (JI, JJ, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDDO


IF (LHOOK) CALL DR_HOOK ('GX_M_M_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE GX_M_M_PHY_MANYBLOCKS

SUBROUTINE GY_M_M_PHY_MANYBLOCKS (D, OFLAT, PA, PDYY, PDZZ, PDZY, PGY_M_M, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODE_SHUMAN_PHY,ONLY:MYM_PHY, DYF_PHY, MYF_PHY, DZM_PHY, MZF_PHY
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MZF_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MYM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MYF_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : DZM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : DYF_PHY_MANYBLOCKS
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(D%NIT, D%NJT, D%NKT, KGPBLKS)
REAL, INTENT (IN)::PDYY(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PDZZ(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PDZY(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
LOGICAL, INTENT (IN)::OFLAT
REAL, INTENT (OUT)::PGY_M_M(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL::ZMYF_PDYY(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK5(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK4(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK3(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK2(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK1(D%NIT, D%NJT, D%NKT,KGPBLKS)
INTEGER::IKT
INTEGER::IJE
INTEGER::IIE
INTEGER::IJB
INTEGER::IIB
INTEGER::JK
INTEGER::JJ
INTEGER::JI
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&CREATE (ZMYF_PDYY, ZWORK1, ZWORK2, ZWORK3, ZWORK4, ZWORK5) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PDYY, PDZY, PDZZ, PGY_M_M) 

IF (LHOOK) CALL DR_HOOK ('GY_M_M_MANYBLOCKS', 0, ZHOOK_HANDLE)
IIE=D%NIEC
IIB=D%NIBC
IJE=D%NJEC
IJB=D%NJBC
IKT=D%NKT
CALL MYM_PHY_MANYBLOCKS (D, PA, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL DYF_PHY_MANYBLOCKS (D, ZWORK1, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MYF_PHY_MANYBLOCKS (D, PDYY, ZMYF_PDYY, LDACC = LDACC, KGPBLKS = KGPBLKS)

CALL DZM_PHY_MANYBLOCKS (D, PA, ZWORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MYF_PHY_MANYBLOCKS (D, PDZY, ZWORK4, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JJ, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT

      DO JJ=IJB, IJE
        
        ZWORK5 (JI, JJ, JK, JBLK)=ZWORK4 (JI, JJ, JK, JBLK)*ZWORK3&
        & (JI, JJ, JK, JBLK)/PDZZ (JI, JJ, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDDO

CALL MZF_PHY_MANYBLOCKS (D, ZWORK5, ZWORK4, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JJ, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT

      DO JJ=IJB, IJE
        
        PGY_M_M (JI, JJ, JK, JBLK)=(ZWORK2 (JI, JJ, JK, JBLK)-ZWORK4&
        & (JI, JJ, JK, JBLK))/ZMYF_PDYY (JI, JJ, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDDO


IF (LHOOK) CALL DR_HOOK ('GY_M_M_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE GY_M_M_PHY_MANYBLOCKS

SUBROUTINE GX_M_U_PHY_MANYBLOCKS (D, OFLAT, PY, PDXX, PDZZ, PDZX, PGX_M_U, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_PARAMETERS,ONLY:JPHEXT, JPVEXT_TURB
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
LOGICAL, INTENT (IN)::OFLAT
REAL, INTENT (IN)::PY(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PDXX(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PDZZ(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PDZX(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (OUT)::PGX_M_U(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL::ZGX_M_U(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZDXX(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZY(D%NIT, D%NJT, D%NKT,KGPBLKS)
INTEGER IKA
INTEGER IKL
INTEGER JK
INTEGER JI
INTEGER IKU
INTEGER IIU
INTEGER::IJU
INTEGER::JIJKEND
INTEGER::JIJKOR
INTEGER::JIJK
INTEGER::JI_1JKP1
INTEGER::JIJKP1
INTEGER::JI_1JK_1
INTEGER::JIJK_1
INTEGER::JI_1JK
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&CREATE (ZDXX, ZGX_M_U, ZY) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PDXX, PDZX, PDZZ, PGX_M_U, PY) 

IF (LHOOK) CALL DR_HOOK ('GX_M_U_MANYBLOCKS', 0, ZHOOK_HANDLE)
IIU=D%NIT
IJU=D%NJT
IKU=D%NKT
IKL=D%NKL
IKA=D%NKA


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    PGX_M_U (JI, 1:IJU, 1+JPVEXT_TURB:IKU-JPVEXT_TURB, JBLK)=(PY (JI, 1:IJU, 1+JPVEXT_TURB:IKU-JPVEXT_TURB&
    &, JBLK)-PY (JI, 1:IJU, 1+JPVEXT_TURB:IKU-JPVEXT_TURB, JBLK)-((PY (JI, 1:IJU, 1+JPVEXT_TURB:IKU-JPVEXT_TURB&
    &, JBLK)-PY (JI, 1:IJU, JPVEXT_TURB:IKU-JPVEXT_TURB-1, JBLK))/PDZZ (JI, 1:IJU, 1+JPVEXT_TURB:IKU-JPVEXT_TURB&
    &, JBLK)+(PY (JI, 1:IJU, 1+JPVEXT_TURB:IKU-JPVEXT_TURB, JBLK)-PY (JI, 1:IJU, JPVEXT_TURB:IKU-JPVEXT_TURB&
    &-1, JBLK))/PDZZ (JI, 1:IJU, 1+JPVEXT_TURB:IKU-JPVEXT_TURB, JBLK))*PDZX (JI, 1:IJU, 1+JPVEXT_TURB:IKU&
    &-JPVEXT_TURB, JBLK)*0.25-((PY (JI, 1:IJU, 1+JPVEXT_TURB+1:IKU-JPVEXT_TURB+1, JBLK)-PY (JI, 1:IJU, 1+JPVEXT_TURB&
    &:IKU-JPVEXT_TURB, JBLK))/PDZZ (JI, 1:IJU, 1+JPVEXT_TURB+1:IKU-JPVEXT_TURB+1, JBLK)+(PY (JI, 1:IJU, 1&
    &+JPVEXT_TURB+1:IKU-JPVEXT_TURB+1, JBLK)-PY (JI, 1:IJU, 1+JPVEXT_TURB:IKU-JPVEXT_TURB, JBLK))/PDZZ (JI&
    &, 1:IJU, 1+JPVEXT_TURB+1:IKU-JPVEXT_TURB+1, JBLK))*PDZX (JI, 1:IJU, 1+JPVEXT_TURB+1:IKU-JPVEXT_TURB+1&
    &, JBLK)*0.25)/PDXX (JI, 1:IJU, 1+JPVEXT_TURB:IKU-JPVEXT_TURB, JBLK)
    
    PGX_M_U (JI,:, IKU, JBLK)=(PY (JI,:, IKU, JBLK)-PY (JI,:, IKU, JBLK))/PDXX (JI,:, IKU, JBLK)
    PGX_M_U (JI,:, IKA, JBLK)=PGX_M_U (JI,:, IKU, JBLK)
    
    
    PGX_M_U (JI,:,:, JBLK)=PGX_M_U (JI,:,:, JBLK)
  
  ENDDO

ENDDO




IF (LHOOK) CALL DR_HOOK ('GX_M_U_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE GX_M_U_PHY_MANYBLOCKS

SUBROUTINE GY_M_V_PHY_MANYBLOCKS (D, OFLAT, PY, PDYY, PDZZ, PDZY, PGY_M_V, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_PARAMETERS,ONLY:JPHEXT, JPVEXT_TURB
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
LOGICAL, INTENT (IN)::OFLAT
REAL, INTENT (IN)::PDYY(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PDZY(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PDZZ(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PY(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (OUT)::PGY_M_V(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
INTEGER IKA
INTEGER IKL
INTEGER JK
INTEGER JJ
INTEGER JI
INTEGER IKU
INTEGER IJU
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PDYY, PDZY, PDZZ, PGY_M_V, PY) 

IF (LHOOK) CALL DR_HOOK ('GY_M_V_MANYBLOCKS', 0, ZHOOK_HANDLE)
IJU=D%NJT
IKU=D%NKT
IKL=D%NKL
IKA=D%NKA
IKU=D%NKU


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JJ, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1+JPVEXT_TURB, IKU-JPVEXT_TURB

      DO JJ=1+JPHEXT, IJU
        PGY_M_V (JI, JJ, JK, JBLK)=(PY (JI, JJ, JK, JBLK)-PY (JI, JJ-1, JK, JBLK)-((PY (JI, JJ, JK, JBLK)-PY&
        & (JI, JJ, JK-IKL, JBLK))/PDZZ (JI, JJ, JK, JBLK)+(PY (JI, JJ-1, JK, JBLK)-PY (JI, JJ-IKL, JK-IKL,&
        & JBLK))/PDZZ (JI, JJ-1, JK, JBLK))*PDZY (JI, JJ, JK, JBLK)*0.25-((PY (JI, JJ, JK+IKL, JBLK)-PY (JI&
        &, JJ, JK, JBLK))/PDZZ (JI, JJ, JK+IKL, JBLK)+(PY (JI, JJ-1, JK+IKL, JBLK)-PY (JI, JJ-1, JK, JBLK)&
        &)/PDZZ (JI, JJ-1, JK+IKL, JBLK))*PDZY (JI, JJ, JK+IKL, JBLK)*0.25)/PDYY (JI, JJ, JK, JBLK)
      ENDDO

    ENDDO

  ENDDO

ENDDO


DO JJ=1+JPHEXT, IJU
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      PGY_M_V (JI, JJ, IKU, JBLK)=(PY (JI, JJ, IKU, JBLK)-PY&
      & (JI, JJ-1, IKU, JBLK))/PDYY (JI, JJ, IKU, JBLK)
      PGY_M_V (JI, JJ, IKA, JBLK)=-999.
    ENDDO

  ENDDO

  
ENDDO



DO JJ=1, JPHEXT
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      PGY_M_V (JI, JJ,:, JBLK)=PGY_M_V (JI, IJU-2*JPHEXT+JJ,:, JBLK)
    ENDDO

  ENDDO

ENDDO

IF (LHOOK) CALL DR_HOOK ('GY_M_V_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE GY_M_V_PHY_MANYBLOCKS

ENDMODULE MODE_GRADIENT_M_PHY_MANYBLOCKS
