
MODULE MODE_TURB_VER_THERMO_FLUX_MANYBLOCKS


IMPLICIT NONE



CONTAINS
SUBROUTINE TURB_VER_THERMO_FLUX_MANYBLOCKS (D, CST, CSTURB, TURBN, TLES, KRR, KRRL, KRRI, KSV,&
& KGRADIENTS, OOCEAN, ODEEPOC, OFLYER, OCOUPLES, OCOMPUTE_SRC, PEXPL, PTSTEP, TPFILE, PDXX, PDYY&
&, PDZZ, PDZX, PDZY, PDIRCOSZW, PZZ, PRHODJ, PTHVREF, PHGRAD, PZS, PSFTHM, PSFRM, PSFTHP, PSFRP&
&, PWM, PTHLM, PRM, PSVM, PTKEM, PLM, PLEPS, PLOCPEXNM, PATHETA, PAMOIST, PSRCM, PFRAC_ICE, PBETA&
&, PSQRT_TKE, PDTH_DZ, PDR_DZ, PRED2TH3, PRED2R3, PRED2THR3, PBLL_O_E, PETHETA, PEMOIST, PREDTH1&
&, PREDR1, PPHI3, PPSI3, PD, PFWTH, PFWR, PFTH2, PFR2, PFTHR, MFMOIST, PBL_DEPTH, PWTHV, PRTHLS&
&, PRRS, PTHLP, PRP, PTP, PWTH, PWRC, PSSTFL, PSSTFL_C, PSSRFL_C, LDACC, KGPBLKS)
USE MODE_SHUMAN_PHY,ONLY:MZM_PHY, DZM_PHY, MXF_PHY, MYF_PHY, MZF_PHY, DZF_PHY
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MZM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MZF_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : DZM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : DZF_PHY_MANYBLOCKS
USE MODE_PRANDTL,ONLY:D_PHI3DTDZ_O_DDTDZ, M3_WTH_W2TH, D_M3_WTH_W2TH_O_DDTDZ, M3_WTH_WTH2&
&, D_M3_WTH_WTH2_O_DDTDZ, M3_WTH_W2R, D_M3_WTH_W2R_O_DDTDZ, M3_WTH_WR2, D_M3_WTH_WR2_O_DDTDZ&
&, M3_WTH_WTHR, D_M3_WTH_WTHR_O_DDTDZ, D_PSI3DRDZ_O_DDRDZ, M3_WR_W2R, D_M3_WR_W2R_O_DDRDZ&
&, M3_WR_WR2, D_M3_WR_WR2_O_DDRDZ, M3_WR_W2TH, D_M3_WR_W2TH_O_DDRDZ, M3_WR_WTH2, D_M3_WR_WTH2_O_DDRDZ&
&, M3_WR_WTHR, D_M3_WR_WTHR_O_DDRDZ
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_WTH_WTHR_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_WTH_WTH2_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_WTH_WR2_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_WTH_W2TH_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_WTH_W2R_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_WR_WTHR_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_WR_WTH2_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_WR_WR2_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_WR_W2TH_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_WR_W2R_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_PSI3DRDZ_O_DDRDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_PHI3DTDZ_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_WTH_WTHR_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_WTH_WTH2_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_WTH_WR2_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_WTH_W2TH_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_WTH_W2R_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_WR_WTHR_O_DDRDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_WR_WTH2_O_DDRDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_WR_WR2_O_DDRDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_WR_W2TH_O_DDRDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_WR_W2R_O_DDRDZ_MANYBLOCKS
USE MODE_TRIDIAG_THERMO,ONLY:TRIDIAG_THERMO
USE MODE_TRIDIAG_THERMO_MANYBLOCKS, ONLY : TRIDIAG_THERMO_MANYBLOCKS
USE MODE_GRADIENT_W_PHY,ONLY:GZ_W_M_PHY
USE MODE_IO_FIELD_WRITE_PHY,ONLY:IO_FIELD_WRITE_PHY
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_CST,ONLY:CST_T
USE MODD_CTURB,ONLY:CSTURB_T
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_FIELD,ONLY:TFIELDMETADATA, TYPEREAL
USE MODD_IO,ONLY:TFILEDATA
USE MODD_LES,ONLY:TLES_T
USE MODD_PARAMETERS,ONLY:XUNDEF
USE MODD_TURB_N,ONLY:TURB_T
USE MODI_LES_MEAN_SUBGRID_PHY
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
TYPE (CST_T), INTENT (IN)::CST
TYPE (CSTURB_T), INTENT (IN)::CSTURB
TYPE (TURB_T), INTENT (IN)::TURBN
TYPE (TLES_T), INTENT (INOUT)::TLES
INTEGER, INTENT (IN)::KRR
INTEGER, INTENT (IN)::KRRL
INTEGER, INTENT (IN)::KRRI
INTEGER, INTENT (IN)::KSV
INTEGER, INTENT (IN)::KGRADIENTS
LOGICAL, INTENT (IN)::OOCEAN
LOGICAL, INTENT (IN)::ODEEPOC
LOGICAL, INTENT (IN)::OFLYER
LOGICAL, INTENT (IN)::OCOUPLES
LOGICAL, INTENT (IN)::OCOMPUTE_SRC
REAL, INTENT (IN)::PEXPL
REAL, INTENT (IN)::PTSTEP
TYPE (TFILEDATA), INTENT (INOUT)::TPFILE
REAL, INTENT (IN)::PDZY(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDZX(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDYY(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDXX(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDZZ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDIRCOSZW(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PZZ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PRHODJ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHVREF(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PHGRAD(:, :, :, :) ! (D%NIJT, D%NKT, KGRADIENTS)
REAL, INTENT (IN)::PZS(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFRM(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFTHM(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFRP(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFTHP(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PWM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHLM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PRM(:, :, :, :) ! (D%NIJT, D%NKT, KRR)
REAL, INTENT (IN)::PSVM(:, :, :, :) ! (D%NIJT, D%NKT, KSV)
REAL, INTENT (IN)::PTKEM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PLM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PLEPS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PLOCPEXNM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PATHETA(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PAMOIST(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PSRCM(:, :, :)
!REAL, INTENT (IN)::PSRCM(MERGE (D%NIT, 0, OCOMPUTE_SRC)*MERGE&
!& (D%NJT, 0, OCOMPUTE_SRC), MERGE (D%NKT, 0, OCOMPUTE_SRC))
REAL, INTENT (IN)::PFRAC_ICE(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PBETA(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PSQRT_TKE(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDTH_DZ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDR_DZ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PRED2TH3(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PRED2R3(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PRED2THR3(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PBLL_O_E(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PETHETA(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PEMOIST(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PREDTH1(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PREDR1(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PPHI3(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PPSI3(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PD(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PFWTH(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PFWR(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PFTH2(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PFR2(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PFTHR(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::MFMOIST(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PBL_DEPTH(D%NIT, D%NJT, KGPBLKS)
REAL, INTENT (OUT)::PWTHV(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRTHLS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRRS(:, :, :, :) ! (D%NIJT, D%NKT, KRR)
REAL, INTENT (OUT)::PTHLP(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT)::PRP(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT)::PTP(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT)::PWTH(:)
REAL, INTENT (OUT)::PWRC(:)
REAL, INTENT (IN), OPTIONAL, TARGET::PSSTFL(:)
REAL, INTENT (IN), OPTIONAL, TARGET::PSSTFL_C(:)
REAL, INTENT (IN), OPTIONAL, TARGET::PSSRFL_C(:)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL::ZWORK4(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK3(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZALT(D%NIJT, D%NKT,KGPBLKS)
REAL::ZCLD_THOLD(D%NIJT, D%NKT,KGPBLKS)
REAL::ZRWRNP(D%NIJT, D%NKT,KGPBLKS)
REAL::ZRWTHL(D%NIJT, D%NKT,KGPBLKS)
REAL::ZF_LEONARD(D%NIJT, D%NKT,KGPBLKS)
REAL::Z3RDMOMENT(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDFDDRDZ(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDFDDTDZ(D%NIJT, D%NKT,KGPBLKS)
REAL::ZF(D%NIJT, D%NKT,KGPBLKS)
REAL::ZKEFF(D%NIJT, D%NKT,KGPBLKS)
REAL::ZFLXZ(D%NIJT, D%NKT,KGPBLKS)
REAL::ZA(D%NIJT, D%NKT,KGPBLKS)
INTEGER::IKE
INTEGER::IKB
INTEGER::IKU
INTEGER::IKA
INTEGER::IKT
INTEGER::IKTE
INTEGER::IKTB
INTEGER::JK
INTEGER::JI
INTEGER::IIJE
INTEGER::IIJB
INTEGER::IKL
REAL::ZTIME2
REAL::ZTIME1
INTEGER::IJU
INTEGER::IIU
LOGICAL::GUSERV
LOGICAL::GFTH2
LOGICAL::GFWTH
LOGICAL::GFR2
LOGICAL::GFWR
LOGICAL::GFTHR
TYPE (TFIELDMETADATA)::TZFIELD
REAL::ZCLDTHOLD
REAL::ZALTHGRAD
REAL::ZMZF2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZSHUGRADWK1_2D(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMZM2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMZM2D_WORK2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZGZ_W_M2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
REAL, POINTER :: PSSRFL_C_PTR
REAL, POINTER :: PSSTFL_PTR
REAL, POINTER :: PSSTFL_C_PTR
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&CREATE (Z3RDMOMENT, ZA, ZALT, ZCLD_THOLD, ZDFDDRDZ, ZDFDDTDZ, ZF, ZFLXZ, ZF_LEONARD, &
!$ACC&        ZGZ_W_M2D_WORK1, ZKEFF, ZMZF2D_WORK1, ZMZM2D_WORK1, ZMZM2D_WORK2, &
!$ACC&        ZRWRNP, ZRWTHL, ZSHUGRADWK1_2D, ZWORK1, ZWORK2, ZWORK3, ZWORK4) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (CST, CSTURB, D, MFMOIST, PAMOIST, PATHETA, PBETA, PBLL_O_E, PBL_DEPTH, &
!$ACC&         PD, PDIRCOSZW, PDR_DZ, PDTH_DZ, PDXX, PDYY, PDZX, PDZY, PDZZ, PEMOIST, &
!$ACC&         PETHETA, PFR2, PFRAC_ICE, PFTH2, PFTHR, PFWR, PFWTH, PHGRAD, PLEPS, PLM, &
!$ACC&         PLOCPEXNM, PPHI3, PPSI3, PRED2R3, PRED2TH3, PRED2THR3, PREDR1, PREDTH1, &
!$ACC&         PRHODJ, PRM, PRP, PRRS, PRTHLS, PSFRM, PSFRP, PSFTHM, PSFTHP, PSQRT_TKE, &
!$ACC&         PSRCM, PSSRFL_C, PSSTFL, PSSTFL_C, PSVM, PTHLM, PTHLP, PTHVREF, PTKEM, &
!$ACC&         PTP, PWM, PWRC, PWTH, PWTHV, PZS, PZZ, TLES, TPFILE, TURBN) 

IF (LHOOK) CALL DR_HOOK ('TURB_VER_THERMO_FLUX_MANYBLOCKS', 0, ZHOOK_HANDLE)
IIU=D%NIT
IJU=D%NJT
IIJE=D%NIJE
IIJB=D%NIJB
IKT=D%NKT
IKA=D%NKA
IKU=D%NKU
IKTB=D%NKTB
IKTE=D%NKTE
IKB=D%NKB
IKE=D%NKE
IKL=D%NKL
ZALTHGRAD=TURBN%XALTHGRAD
ZCLDTHOLD=TURBN%XCLDTHOLD
GUSERV=(KRR/=0)


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZWORK1 (JI, JK, JBLK)=PLM (JI, JK, JBLK)*SQRT (PTKEM (JI, JK, JBLK))
    
    ENDDO

  ENDDO

ENDDO

CALL MZM_PHY_MANYBLOCKS (D, ZWORK1, ZKEFF, LDACC = LDACC, KGPBLKS = KGPBLKS)


GFTH2=.FALSE.
GFR2=.FALSE.
GFTHR=.FALSE.
GFWTH=.FALSE.
GFWR=.FALSE.

IF (TURBN%CTOM/='NONE') THEN
  GFTH2=ANY (PFTH2 (:,:,:)/=0.)
  GFR2=ANY (PFR2 (:,:,:)/=0.).AND.GUSERV
  GFTHR=ANY (PFTHR (:,:,:)/=0.).AND.GUSERV
  GFWTH=ANY (PFWTH (:,:,:)/=0.)
  GFWR=ANY (PFWR (:,:,:)/=0.).AND.GUSERV
ENDIF

CALL DZM_PHY_MANYBLOCKS (D, PTHLM, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL D_PHI3DTDZ_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, PPHI3, PREDTH1, PREDR1, PRED2TH3&
&, PRED2THR3, "1DIM", GUSERV, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZF (JI, JK, JBLK)=-TURBN%XCSHF*PPHI3 (JI, JK, JBLK)*ZKEFF (JI&
      &, JK, JBLK)*ZWORK1 (JI, JK, JBLK)/PDZZ (JI, JK, JBLK)
      ZDFDDTDZ (JI, JK, JBLK)=-TURBN%XCSHF*ZKEFF (JI, JK, JBLK)*ZWORK2 (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO




IF (GFWTH) THEN
  CALL M3_WTH_W2TH_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1, PD&
  &, ZKEFF, PTKEM, Z3RDMOMENT, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL D_M3_WTH_W2TH_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1, PD, PBLL_O_E&
  &, PETHETA, ZKEFF, PTKEM, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+Z3RDMOMENT (JI, JK, JBLK)*PFWTH (JI, JK, JBLK)
        ZDFDDTDZ (JI, JK, JBLK)=ZDFDDTDZ (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*PFWTH (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDIF


IF (GFTH2) THEN
  CALL M3_WTH_WTH2_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1, PD, PBLL_O_E&
  &, PETHETA, Z3RDMOMENT, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL D_M3_WTH_WTH2_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, Z3RDMOMENT, PREDTH1,&
  & PREDR1, PD, PBLL_O_E, PETHETA, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL MZM_PHY_MANYBLOCKS (D, PFTH2, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+Z3RDMOMENT (JI, JK, JBLK)*ZWORK2 (JI, JK, JBLK)
        ZDFDDTDZ (JI, JK, JBLK)=ZDFDDTDZ (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*ZWORK2 (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDIF


IF (GFWR) THEN
  CALL M3_WTH_W2R_MANYBLOCKS (D, CSTURB, TURBN, PD, ZKEFF, PTKEM, PBLL_O_E&
  &, PEMOIST, PDTH_DZ, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL D_M3_WTH_W2R_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1, PD, ZKEFF&
  &, PTKEM, PBLL_O_E, PEMOIST, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*PFWR (JI, JK, JBLK)
        ZDFDDTDZ (JI, JK, JBLK)=ZDFDDTDZ (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*PFWR (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDIF


IF (GFR2) THEN
  CALL M3_WTH_WR2_MANYBLOCKS (D, CSTURB, TURBN, PD, ZKEFF, PTKEM, PSQRT_TKE, PBLL_O_E&
  &, PBETA, PLEPS, PEMOIST, PDTH_DZ, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL MZM_PHY_MANYBLOCKS (D, PFR2, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL D_M3_WTH_WR2_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1, PD, ZKEFF, PTKEM,&
  & PSQRT_TKE, PBLL_O_E, PBETA, PLEPS, PEMOIST, ZWORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*ZWORK2 (JI, JK, JBLK)
        ZDFDDTDZ (JI, JK, JBLK)=ZDFDDTDZ (JI, JK, JBLK)+ZWORK3 (JI, JK, JBLK)*ZWORK2 (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDIF


IF (GFTHR) THEN
  CALL M3_WTH_WTHR_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PD, ZKEFF, PTKEM, PSQRT_TKE&
  &, PBETA, PLEPS, PEMOIST, Z3RDMOMENT, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL D_M3_WTH_WTHR_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, Z3RDMOMENT, PREDTH1,&
  & PREDR1, PD, PBLL_O_E, PETHETA, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL MZM_PHY_MANYBLOCKS (D, PFTHR, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+Z3RDMOMENT (JI, JK, JBLK)*ZWORK2 (JI, JK, JBLK)
        ZDFDDTDZ (JI, JK, JBLK)=ZDFDDTDZ (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*ZWORK2 (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDIF


IF (OOCEAN) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      
      ZF (JI, IKE+1, JBLK)=PSFTHM (JI, JBLK)*0.5*(1.+PRHODJ (JI, IKU, JBLK)/PRHODJ (JI, IKE, JBLK))
    
    ENDDO

  ENDDO

ELSE
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      
      ZF (JI, IKB, JBLK)=(TURBN%XIMPL*PSFTHP (JI, JBLK)+PEXPL*PSFTHM (JI, JBLK))/PDIRCOSZW&
      & (JI, JBLK)*0.5*(1.+PRHODJ (JI, IKA, JBLK)/PRHODJ (JI, IKB, JBLK))
      
      ZF (JI, IKE+1, JBLK)=0.
    ENDDO

  ENDDO

  
ENDIF

CALL TRIDIAG_THERMO_MANYBLOCKS (D, PTHLM, ZF, ZDFDDTDZ, PTSTEP, TURBN&
&%XIMPL, PDZZ, PRHODJ, PTHLP, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZRWTHL (JI, JK, JBLK)=PRHODJ (JI, JK, JBLK)*(PTHLP (JI, JK, JBLK)-PTHLM (JI, JK, JBLK))/PTSTEP
    
    ENDDO


    DO JK=1, IKT
      
      ZWORK1 (JI, JK, JBLK)=PTHLP (JI, JK, JBLK)-PTHLM (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO



CALL DZM_PHY_MANYBLOCKS (D, ZWORK1, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      PRTHLS (JI, JK, JBLK)=PRTHLS (JI, JK, JBLK)+ZRWTHL (JI, JK, JBLK)
      ZFLXZ (JI, JK, JBLK)=ZF (JI, JK, JBLK)+TURBN%XIMPL*ZDFDDTDZ &
      &(JI, JK, JBLK)*ZWORK2 (JI, JK, JBLK)/PDZZ (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO



IF (OOCEAN) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      
      ZFLXZ (JI, IKE+1, JBLK)=ZFLXZ (JI, IKE, JBLK)
    
    ENDDO

  ENDDO

ELSE
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      
      ZFLXZ (JI, IKA, JBLK)=ZFLXZ (JI, IKB, JBLK)
    
    ENDDO

  ENDDO

ENDIF




IF (OOCEAN) THEN
  CALL MZF_PHY_MANYBLOCKS (D, ZFLXZ, ZMZF2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        PTP (JI, JK, JBLK)=CST%XG*CST%XALPHAOC*ZMZF2D_WORK1 (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ELSE

  IF (KRR/=0) THEN
    CALL MZM_PHY_MANYBLOCKS (D, PETHETA, ZMZM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZSHUGRADWK1_2D (JI, JK, JBLK)=ZMZM2D_WORK1 (JI, JK, JBLK)*ZFLXZ (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

    CALL MZF_PHY_MANYBLOCKS (D, ZSHUGRADWK1_2D, ZMZF2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          PTP (JI, JK, JBLK)=PBETA (JI, JK, JBLK)*ZMZF2D_WORK1 (JI, JK, JBLK)
        
        ENDDO

        
        PTP (JI, IKB, JBLK)=PBETA (JI, IKB, JBLK)*PETHETA (JI, IKB, JBLK&
        &)*0.5*(ZFLXZ (JI, IKB, JBLK)+ZFLXZ (JI, IKB+IKL, JBLK))
      
      ENDDO

    ENDDO

  
  ELSE
    CALL MZF_PHY_MANYBLOCKS (D, ZFLXZ, ZMZF2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          PTP (JI, JK, JBLK)=PBETA (JI, JK, JBLK)*ZMZF2D_WORK1 (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF

ENDIF

CALL MZM_PHY_MANYBLOCKS (D, PETHETA, ZMZM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      PWTHV (JI, JK, JBLK)=ZMZM2D_WORK1 (JI, JK, JBLK)*ZFLXZ (JI, JK, JBLK)
    
    ENDDO

    
    PWTHV (JI, IKB, JBLK)=PETHETA (JI, IKB, JBLK)*ZFLXZ (JI, IKB, JBLK)
  
  ENDDO

ENDDO



IF (OOCEAN) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      
      PWTHV (JI, IKE, JBLK)=PETHETA (JI, IKE, JBLK)*ZFLXZ (JI, IKE, JBLK)
    
    ENDDO

  ENDDO

ENDIF


IF (TURBN%LPROJQITURB) THEN

  IF (KRRL>=1) THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZWORK1 (JI, JK, JBLK)=ZFLXZ (JI, JK, JBLK)/PDZZ (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

    CALL DZF_PHY_MANYBLOCKS (D, ZWORK1, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)

    IF (KRRI>=1) THEN
      
      !$ACC PARALLEL LOOP GANG &
      !$ACC&IF (LDACC) &
      !$ACC&PRIVATE (JBLK) &
      !$ACC&VECTOR_LENGTH (D%NIT) 

      

      DO JBLK = 1, KGPBLKS
        
        !$ACC LOOP VECTOR &
        !$ACC&PRIVATE (JI, JK) 

        

        DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

          DO JK=1, IKT
            
            PRRS (JI, JK, 2, JBLK)=PRRS (JI, JK, 2, JBLK)-PRHODJ (JI, JK, JBLK)*PATHETA (JI, JK, JBLK&
            &)*2.*PSRCM (JI, JK, JBLK)*ZWORK2 (JI, JK, JBLK)*(1.0-PFRAC_ICE (JI, JK, JBLK))
            PRRS (JI, JK, 4, JBLK)=PRRS (JI, JK, 4, JBLK)-PRHODJ (JI, JK, JBLK)*PATHETA (JI, JK&
            &, JBLK)*2.*PSRCM (JI, JK, JBLK)*ZWORK2 (JI, JK, JBLK)*PFRAC_ICE (JI, JK, JBLK)
          
          ENDDO

        ENDDO

      ENDDO

    ELSE
      
      !$ACC PARALLEL LOOP GANG &
      !$ACC&IF (LDACC) &
      !$ACC&PRIVATE (JBLK) &
      !$ACC&VECTOR_LENGTH (D%NIT) 

      

      DO JBLK = 1, KGPBLKS
        
        !$ACC LOOP VECTOR &
        !$ACC&PRIVATE (JI, JK) 

        

        DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

          DO JK=1, IKT
            
            PRRS (JI, JK, 2, JBLK)=PRRS (JI, JK, 2, JBLK)-PRHODJ (JI, JK, JBLK)*PATHETA&
            & (JI, JK, JBLK)*2.*PSRCM (JI, JK, JBLK)*ZWORK2 (JI, JK, JBLK)
          
          ENDDO

        ENDDO

      ENDDO

    ENDIF

  ENDIF

ENDIF


IF (KRR/=0) THEN
  CALL DZM_PHY_MANYBLOCKS (D, PRM (:,:, 1,:), ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  CALL D_PSI3DRDZ_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, PPSI3, PREDR1, PREDTH1, PRED2R3&
  &, PRED2THR3, "1DIM", GUSERV, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZF (JI, JK, JBLK)=-TURBN%XCSHF*PPSI3 (JI, JK, JBLK)*ZKEFF (JI&
        &, JK, JBLK)*ZWORK1 (JI, JK, JBLK)/PDZZ (JI, JK, JBLK)
        ZDFDDRDZ (JI, JK, JBLK)=-TURBN%XCSHF*ZKEFF (JI, JK, JBLK)*ZWORK2 (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO


  

  

  IF (GFWR) THEN
    CALL M3_WR_W2R_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PREDTH1, PD&
    &, ZKEFF, PTKEM, Z3RDMOMENT, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_WR_W2R_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PREDTH1, PD, PBLL_O_E&
    &, PEMOIST, ZKEFF, PTKEM, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+Z3RDMOMENT (JI, JK, JBLK)*PFWR (JI, JK, JBLK)
          ZDFDDRDZ (JI, JK, JBLK)=ZDFDDRDZ (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*PFWR (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF


  IF (GFR2) THEN
    CALL M3_WR_WR2_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PREDTH1, PD, PBLL_O_E&
    &, PEMOIST, Z3RDMOMENT, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL MZM_PHY_MANYBLOCKS (D, PFR2, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_WR_WR2_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, Z3RDMOMENT, PREDR1, PREDTH1&
    &, PD, PBLL_O_E, PEMOIST, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+Z3RDMOMENT (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
          ZDFDDRDZ (JI, JK, JBLK)=ZDFDDRDZ (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF


  IF (GFWTH) THEN
    CALL M3_WR_W2TH_MANYBLOCKS (D, CSTURB, TURBN, PD, ZKEFF, PTKEM, PBLL_O_E&
    &, PETHETA, PDR_DZ, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_WR_W2TH_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PREDTH1, PD, ZKEFF&
    &, PTKEM, PBLL_O_E, PETHETA, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*PFWTH (JI, JK, JBLK)
          ZDFDDRDZ (JI, JK, JBLK)=ZDFDDRDZ (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*PFWTH (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF


  IF (GFTH2) THEN
    CALL MZM_PHY_MANYBLOCKS (D, PFTH2, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL M3_WR_WTH2_MANYBLOCKS (D, CSTURB, TURBN, PD, ZKEFF, PTKEM, PSQRT_TKE, PBLL_O_E&
    &, PBETA, PLEPS, PETHETA, PDR_DZ, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_WR_WTH2_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PREDTH1, PD, ZKEFF, PTKEM,&
    & PSQRT_TKE, PBLL_O_E, PBETA, PLEPS, PETHETA, ZWORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
          ZDFDDRDZ (JI, JK, JBLK)=ZDFDDRDZ (JI, JK, JBLK)+ZWORK3 (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF


  IF (GFTHR) THEN
    CALL M3_WR_WTHR_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PD, ZKEFF, PTKEM, PSQRT_TKE&
    &, PBETA, PLEPS, PETHETA, Z3RDMOMENT, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL MZM_PHY_MANYBLOCKS (D, PFTHR, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_WR_WTHR_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, Z3RDMOMENT, PREDR1, PREDTH1&
    &, PD, PBLL_O_E, PEMOIST, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+Z3RDMOMENT (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
          ZDFDDRDZ (JI, JK, JBLK)=ZDFDDRDZ (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF


  IF (OOCEAN) THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
        ZF (JI, IKE, JBLK)=0.
      ENDDO

    ENDDO

  ELSE
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
        
        ZF (JI, IKB, JBLK)=(TURBN%XIMPL*PSFRP (JI, JBLK)+PEXPL*PSFRM (JI, JBLK))/PDIRCOSZW&
        & (JI, JBLK)*0.5*(1.+PRHODJ (JI, IKA, JBLK)/PRHODJ (JI, IKB, JBLK))
        
        ZF (JI, IKE+1, JBLK)=0.
      ENDDO

    ENDDO

  
  ENDIF

  CALL TRIDIAG_THERMO_MANYBLOCKS (D, PRM (:,:, 1,:), ZF, ZDFDDRDZ, PTSTEP&
  &, TURBN%XIMPL, PDZZ, PRHODJ, PRP, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZRWRNP (JI, JK, JBLK)=PRHODJ (JI, JK, JBLK)*(PRP (JI, JK, JBLK)-PRM (JI, JK, 1, JBLK))/PTSTEP
      
      ENDDO


      DO JK=1, IKT
        
        ZWORK1 (JI, JK, JBLK)=PRP (JI, JK, JBLK)-PRM (JI, JK, 1, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

  
  
  CALL DZM_PHY_MANYBLOCKS (D, ZWORK1, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        PRRS (JI, JK, 1, JBLK)=PRRS (JI, JK, 1, JBLK)+ZRWRNP (JI, JK, JBLK)
        ZFLXZ (JI, JK, JBLK)=ZF (JI, JK, JBLK)+TURBN%XIMPL*ZDFDDRDZ &
        &(JI, JK, JBLK)*ZWORK2 (JI, JK, JBLK)/PDZZ (JI, JK, JBLK)
      
      ENDDO

      
      ZFLXZ (JI, IKA, JBLK)=ZFLXZ (JI, IKB, JBLK)
    
    ENDDO

  ENDDO


  

  

  IF (OOCEAN) THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
        
        ZFLXZ (JI, IKU, JBLK)=ZFLXZ (JI, IKE, JBLK)
      
      ENDDO

    ENDDO

  ENDIF


  

  

  IF (OOCEAN) THEN
    CALL MZF_PHY_MANYBLOCKS (D, ZFLXZ, ZMZF2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZA (JI, JK, JBLK)=-CST%XG*CST%XBETAOC*ZMZF2D_WORK1 (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ELSE
    CALL MZM_PHY_MANYBLOCKS (D, PEMOIST, ZMZM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZSHUGRADWK1_2D (JI, JK, JBLK)=ZMZM2D_WORK1 (JI, JK, JBLK)*ZFLXZ (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

    CALL MZF_PHY_MANYBLOCKS (D, ZSHUGRADWK1_2D, ZMZF2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZA (JI, JK, JBLK)=PBETA (JI, JK, JBLK)*ZMZF2D_WORK1 (JI, JK, JBLK)
        
        ENDDO

        
        ZA (JI, IKB, JBLK)=PBETA (JI, IKB, JBLK)*PEMOIST (JI, IKB, JBLK&
        &)*0.5*(ZFLXZ (JI, IKB, JBLK)+ZFLXZ (JI, IKB+IKL, JBLK))

        

        DO JK=1, IKT
          
          PTP (JI, JK, JBLK)=PTP (JI, JK, JBLK)+ZA (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  
  
  ENDIF

  CALL MZM_PHY_MANYBLOCKS (D, PEMOIST, ZMZM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        PWTHV (JI, JK, JBLK)=PWTHV (JI, JK, JBLK)+ZMZM2D_WORK1 (JI, JK, JBLK)*ZFLXZ (JI, JK, JBLK)
      
      ENDDO

      
      PWTHV (JI, IKB, JBLK)=PWTHV (JI, IKB, JBLK)+PEMOIST (JI, IKB, JBLK)*ZFLXZ (JI, IKB, JBLK)
    
    ENDDO

  ENDDO


  

  IF (OOCEAN) THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
        
        PWTHV (JI, IKE, JBLK)=PWTHV (JI, IKE, JBLK)+PEMOIST (JI, IKE, JBLK)*ZFLXZ (JI, IKE, JBLK)
      
      ENDDO

    ENDDO

  ENDIF


  IF (TURBN%LPROJQITURB) THEN

    IF (KRRL>=1) THEN
      
      !$ACC PARALLEL LOOP GANG &
      !$ACC&IF (LDACC) &
      !$ACC&PRIVATE (JBLK) &
      !$ACC&VECTOR_LENGTH (D%NIT) 

      

      DO JBLK = 1, KGPBLKS
        
        !$ACC LOOP VECTOR &
        !$ACC&PRIVATE (JI, JK) 

        

        DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

          DO JK=1, IKT
            
            ZWORK2 (JI, JK, JBLK)=ZFLXZ (JI, JK, JBLK)/PDZZ (JI, JK, JBLK)
          
          ENDDO

        ENDDO

      ENDDO

      CALL DZF_PHY_MANYBLOCKS (D, ZWORK2, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

      IF (KRRI>=1) THEN
        
        !$ACC PARALLEL LOOP GANG &
        !$ACC&IF (LDACC) &
        !$ACC&PRIVATE (JBLK) &
        !$ACC&VECTOR_LENGTH (D%NIT) 

        

        DO JBLK = 1, KGPBLKS
          
          !$ACC LOOP VECTOR &
          !$ACC&PRIVATE (JI, JK) 

          

          DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

            DO JK=1, IKT
              
              PRRS (JI, JK, 2, JBLK)=PRRS (JI, JK, 2, JBLK)-PRHODJ (JI, JK, JBLK)*PAMOIST (JI, JK, JBLK&
              &)*2.*PSRCM (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)*(1.0-PFRAC_ICE (JI, JK, JBLK))
              PRRS (JI, JK, 4, JBLK)=PRRS (JI, JK, 4, JBLK)-PRHODJ (JI, JK, JBLK)*PAMOIST (JI, JK&
              &, JBLK)*2.*PSRCM (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)*PFRAC_ICE (JI, JK, JBLK)
            
            ENDDO

          ENDDO

        ENDDO

      ELSE
        
        !$ACC PARALLEL LOOP GANG &
        !$ACC&IF (LDACC) &
        !$ACC&PRIVATE (JBLK) &
        !$ACC&VECTOR_LENGTH (D%NIT) 

        

        DO JBLK = 1, KGPBLKS
          
          !$ACC LOOP VECTOR &
          !$ACC&PRIVATE (JI, JK) 

          

          DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

            DO JK=1, IKT
              
              PRRS (JI, JK, 2, JBLK)=PRRS (JI, JK, 2, JBLK)-PRHODJ (JI, JK, JBLK)*PAMOIST&
              & (JI, JK, JBLK)*2.*PSRCM (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
            
            ENDDO

          ENDDO

        ENDDO

      ENDIF

    ENDIF

  ENDIF

ENDIF


IF (LHOOK) CALL DR_HOOK ('TURB_VER_THERMO_FLUX_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE TURB_VER_THERMO_FLUX_MANYBLOCKS

ENDMODULE MODE_TURB_VER_THERMO_FLUX_MANYBLOCKS
