
MODULE MODE_TURB_VER_MANYBLOCKS


IMPLICIT NONE



CONTAINS
SUBROUTINE TURB_VER_MANYBLOCKS (D, CST, CSTURB, TURBN, NEBN, TLES, KRR, KRRL, KRRI, KGRADIENTS, OOCEAN&
&, ODEEPOC, OCOMPUTE_SRC, KSV, KSV_LGBEG, KSV_LGEND, PEXPL, O2D, ONOMIXLG, OFLAT, OCOUPLES, OBLOWSNOW&
&, OFLYER, PRSNOW, PTSTEP, TPFILE, PDXX, PDYY, PDZZ, PDZX, PDZY, PDIRCOSZW, PZZ, PCOSSLOPE, PSINSLOPE&
&, PRHODJ, PTHVREF, PSFUM, PSFVM, PSFTHM, PSFRM, PSFSVM, PSFTHP, PSFRP, PSFSVP, PCDUEFF, PTAU11M, PTAU12M&
&, PTAU33M, PUM, PVM, PWM, PUSLOPEM, PVSLOPEM, PTHLM, PRM, PSVM, PTKEM, PLM, PLENGTHM, PLENGTHH, PLEPS&
&, MFMOIST, PLOCPEXNM, PATHETA, PAMOIST, PSRCM, PFRAC_ICE, PFWTH, PFWR, PFTH2, PFR2, PFTHR, PBL_DEPTH&
&, PSBL_DEPTH, PLMO, PHGRAD, PZS, PRUS, PRVS, PRWS, PRTHLS, PRRS, PRSVS, PDP, PTP, PSIGS, PWTH, PWRC,&
& PSSTFL, PSSTFL_C, PSSRFL_C, PSSUFL_C, PSSVFL_C, PSSUFL, PSSVFL, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_CST,ONLY:CST_T
USE MODD_CTURB,ONLY:CSTURB_T
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_FIELD,ONLY:TFIELDMETADATA, TYPEREAL
USE MODD_IO,ONLY:TFILEDATA
USE MODD_LES,ONLY:TLES_T
USE MODD_TURB_N,ONLY:TURB_T
USE MODD_NEB_N,ONLY:NEB_T
USE MODE_PRANDTL,ONLY:PRANDTL, PHI3, PSI3, PSI_SV
USE MODE_PRANDTL_MANYBLOCKS, ONLY : PSI_SV_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : PSI3_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : PRANDTL_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : PHI3_MANYBLOCKS
USE MODE_GRADIENT_M_PHY,ONLY:GZ_M_W_PHY
USE MODE_GRADIENT_M_PHY_MANYBLOCKS, ONLY : GZ_M_W_PHY_MANYBLOCKS
USE MODE_TURB_VER_THERMO_FLUX,ONLY:TURB_VER_THERMO_FLUX
USE MODE_TURB_VER_THERMO_FLUX_MANYBLOCKS, ONLY : TURB_VER_THERMO_FLUX_MANYBLOCKS
USE MODE_TURB_VER_THERMO_CORR,ONLY:TURB_VER_THERMO_CORR
USE MODE_TURB_VER_THERMO_CORR_MANYBLOCKS, ONLY : TURB_VER_THERMO_CORR_MANYBLOCKS
USE MODE_TURB_VER_DYN_FLUX,ONLY:TURB_VER_DYN_FLUX
USE MODE_TURB_VER_DYN_FLUX_MANYBLOCKS, ONLY : TURB_VER_DYN_FLUX_MANYBLOCKS
USE MODE_IO_FIELD_WRITE_PHY,ONLY:IO_FIELD_WRITE_PHY
USE MODI_LES_MEAN_SUBGRID_PHY
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
TYPE (CST_T), INTENT (IN)::CST
TYPE (CSTURB_T), INTENT (IN)::CSTURB
TYPE (TURB_T), INTENT (IN)::TURBN
TYPE (NEB_T), INTENT (IN)::NEBN
TYPE (TLES_T), INTENT (INOUT)::TLES
INTEGER, INTENT (IN)::KGRADIENTS
INTEGER, INTENT (IN)::KRR
INTEGER, INTENT (IN)::KRRL
INTEGER, INTENT (IN)::KRRI
INTEGER, INTENT (IN)::KSV_LGEND
INTEGER, INTENT (IN)::KSV_LGBEG
INTEGER, INTENT (IN)::KSV
LOGICAL, INTENT (IN)::OOCEAN
LOGICAL, INTENT (IN)::ODEEPOC
LOGICAL, INTENT (IN)::OFLYER
LOGICAL, INTENT (IN)::OCOMPUTE_SRC
LOGICAL, INTENT (IN)::OFLAT
LOGICAL, INTENT (IN)::OCOUPLES
LOGICAL, INTENT (IN)::OBLOWSNOW
REAL, INTENT (IN)::PRSNOW
LOGICAL, INTENT (IN)::ONOMIXLG
LOGICAL, INTENT (IN)::O2D
REAL, INTENT (IN)::PEXPL
REAL, INTENT (IN)::PTSTEP
TYPE (TFILEDATA), INTENT (INOUT)::TPFILE
REAL, INTENT (IN)::PDZY(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDZX(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDZZ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDYY(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDXX(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDIRCOSZW(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PZZ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PCOSSLOPE(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSINSLOPE(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PZS(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PRHODJ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::MFMOIST(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHVREF(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PHGRAD(:, :, :, :) ! (D%NIJT, D%NKT, KGRADIENTS)
REAL, INTENT (IN)::PSFVM(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFUM(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFRM(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFTHM(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFSVM(:, :, :) ! (D%NIJT, KSV)
REAL, INTENT (IN)::PSFRP(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFTHP(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFSVP(:, :, :) ! (D%NIJT, KSV)
REAL, INTENT (IN)::PCDUEFF(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PTAU11M(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PTAU12M(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PTAU33M(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PTHLM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PWM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PVM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PUM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PRM(:, :, :, :) ! (D%NIJT, D%NKT, KRR)
REAL, INTENT (IN)::PSVM(:, :, :, :) ! (D%NIJT, D%NKT, KSV)
REAL, INTENT (IN)::PUSLOPEM(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PVSLOPEM(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PTKEM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PLM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PLENGTHM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PLENGTHH(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PLEPS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PLOCPEXNM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PATHETA(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PAMOIST(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PSRCM(:, :, :)
!REAL, INTENT (IN)::PSRCM(MERGE (D%NIJT, 0, OCOMPUTE_SRC), MERGE (D%NKT, 0, OCOMPUTE_SRC))
REAL, INTENT (IN)::PFRAC_ICE(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PFWTH(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PFWR(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PFTH2(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PFR2(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PFTHR(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PBL_DEPTH(D%NIJT, KGPBLKS)
REAL, INTENT (INOUT)::PSBL_DEPTH(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PLMO(:, :) ! (D%NIJT)
REAL, INTENT (INOUT)::PRTHLS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRWS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRVS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRUS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRRS(:, :, :, :) ! (D%NIJT, D%NKT, KRR)
REAL, INTENT (INOUT)::PRSVS(:, :, :, :) ! (D%NIJT, D%NKT, KSV)
REAL, INTENT (OUT)::PTP(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT)::PDP(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT)::PSIGS(:, :, :)
REAL, INTENT (OUT)::PWTH(:)
REAL, INTENT (OUT)::PWRC(:)
!REAL, INTENT (OUT)::PWSV(:, :, :)
REAL, INTENT (IN), OPTIONAL, TARGET::PSSTFL(:)
REAL, INTENT (IN), OPTIONAL, TARGET::PSSTFL_C(:)
REAL, INTENT (IN), OPTIONAL, TARGET::PSSRFL_C(:)
REAL, INTENT (IN), OPTIONAL, TARGET::PSSUFL_C(:)
REAL, INTENT (IN), OPTIONAL, TARGET::PSSVFL_C(:)
REAL, INTENT (IN), OPTIONAL, TARGET::PSSUFL(:)
REAL, INTENT (IN), OPTIONAL, TARGET::PSSVFL(:)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL::ZRP(D%NIJT, D%NKT,KGPBLKS)
REAL::ZTHLP(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWV(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWU(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWTHV(D%NIJT, D%NKT,KGPBLKS)
REAL::ZD(D%NIJT, D%NKT,KGPBLKS)
REAL::ZPSI3(D%NIJT, D%NKT,KGPBLKS)
REAL::ZPHI3(D%NIJT, D%NKT,KGPBLKS)
REAL::ZREDR1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZREDTH1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZEMOIST(D%NIJT, D%NKT,KGPBLKS)
REAL::ZETHETA(D%NIJT, D%NKT,KGPBLKS)
REAL::ZBLL_O_E(D%NIJT, D%NKT,KGPBLKS)
REAL::ZRED2THR3(D%NIJT, D%NKT,KGPBLKS)
REAL::ZRED2R3(D%NIJT, D%NKT,KGPBLKS)
REAL::ZRED2TH3(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDR_DZ(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDTH_DZ(D%NIJT, D%NKT,KGPBLKS)
REAL::ZSQRT_TKE(D%NIJT, D%NKT,KGPBLKS)
REAL::ZBETA(D%NIJT, D%NKT,KGPBLKS)
REAL::ZRED2RS(D%NIJT, D%NKT, KSV,KGPBLKS)
REAL::ZRED2THS(D%NIJT, D%NKT, KSV,KGPBLKS)
REAL::ZREDS1(D%NIJT, D%NKT, KSV,KGPBLKS)
REAL::ZPSI_SV(D%NIJT, D%NKT, KSV,KGPBLKS)
REAL::ZLM(D%NIJT, D%NKT,KGPBLKS)
LOGICAL::GUSERV
INTEGER::IKT
INTEGER::IIJB
INTEGER::IIJE
INTEGER::IKE
INTEGER::IKB
INTEGER::JK
INTEGER::JI
INTEGER::JSV
REAL::ZTIME1
REAL::ZTIME2
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (TFIELDMETADATA)::TZFIELD
REAL, POINTER :: PSSRFL_C_PTR
REAL, POINTER :: PSSTFL_PTR
REAL, POINTER :: PSSTFL_C_PTR
REAL, POINTER :: PSSUFL_PTR
REAL, POINTER :: PSSUFL_C_PTR
REAL, POINTER :: PSSVFL_PTR
REAL, POINTER :: PSSVFL_C_PTR
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&CREATE (ZBETA, ZBLL_O_E, ZD, ZDR_DZ, ZDTH_DZ, ZEMOIST, ZETHETA, ZLM, ZPHI3, ZPSI3, &
!$ACC&        ZPSI_SV, ZRED2R3, ZRED2RS, ZRED2TH3, ZRED2THR3, ZRED2THS, ZREDR1, &
!$ACC&        ZREDS1, ZREDTH1, ZRP, ZSQRT_TKE, ZTHLP, ZWTHV, ZWU, ZWV) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (CST, CSTURB, D, MFMOIST, NEBN, PAMOIST, PATHETA, PBL_DEPTH, PCDUEFF, &
!$ACC&         PCOSSLOPE, PDIRCOSZW, PDP, PDXX, PDYY, PDZX, PDZY, PDZZ, PFR2, PFRAC_ICE, &
!$ACC&         PFTH2, PFTHR, PFWR, PFWTH, PHGRAD, PLENGTHH, PLENGTHM, PLEPS, PLM, PLMO, &
!$ACC&         PLOCPEXNM, PRHODJ, PRM, PRRS, PRSVS, PRTHLS, PRUS, PRVS, PRWS, PSBL_DEPTH, &
!$ACC&         PSFRM, PSFRP, PSFSVM, PSFSVP, PSFTHM, PSFTHP, PSFUM, PSFVM, PSIGS, PSINSLOPE, &
!$ACC&         PSRCM, PSSRFL_C, PSSTFL, PSSTFL_C, PSSUFL, PSSUFL_C, PSSVFL, PSSVFL_C, &
!$ACC&         PSVM, PTAU11M, PTAU12M, PTAU33M, PTHLM, PTHVREF, PTKEM, PTP, PUM, PUSLOPEM, &
!$ACC&         PVM, PVSLOPEM, PWM, PWRC, PWTH, PZS, PZZ, TLES, TPFILE, TURBN) 

IF (LHOOK) CALL DR_HOOK ('TURB_VER_MANYBLOCKS', 0, ZHOOK_HANDLE)
IKB=D%NKTB
IKE=D%NKTE
IKT=D%NKT
IIJE=D%NIJE
IIJB=D%NIJB
CALL PRANDTL_MANYBLOCKS (D, CST, CSTURB, TURBN, KRR, KSV, KRRI, .FALSE., "1DIM", OOCEAN, .FALSE., &
&.FALSE., OCOMPUTE_SRC, TPFILE, .FALSE., PDXX, PDYY, PDZZ, PDZX, PDZY, PTHVREF, PLOCPEXNM, PATHETA&
&, PAMOIST, PLM, PLEPS, PTKEM, PTHLM, PRM, PSVM, PSRCM, ZREDTH1, ZREDR1, ZRED2TH3, ZRED2R3, ZRED2THR3&
&, ZREDS1, ZRED2THS, ZRED2RS, ZBLL_O_E, ZETHETA, ZEMOIST, LDACC = LDACC, KGPBLKS = KGPBLKS)

IF (OOCEAN) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZBETA (JI, JK, JBLK)=CST%XG*CST%XALPHAOC
      
      ENDDO

    ENDDO

  ENDDO

ELSE
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZBETA (JI, JK, JBLK)=CST%XG/PTHVREF (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDIF


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZSQRT_TKE (JI, JK, JBLK)=SQRT (PTKEM (JI, JK, JBLK))
    
    ENDDO

  ENDDO

ENDDO

CALL GZ_M_W_PHY_MANYBLOCKS (D, PTHLM, PDZZ, ZDTH_DZ, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    ZDR_DZ (JI,:, JBLK)=0.
  ENDDO

ENDDO


IF (KRR>0)  THEN
  CALL GZ_M_W_PHY_MANYBLOCKS (D, PRM (:,:, 1,:), PDZZ, ZDR_DZ, LDACC = LDACC, KGPBLKS = KGPBLKS)
ENDIF



!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZD (JI, JK, JBLK)=(1.+ZREDTH1 (JI, JK, JBLK)+ZREDR1 (JI, JK, JBLK&
      &))*(1.+0.5*(ZREDTH1 (JI, JK, JBLK)+ZREDR1 (JI, JK, JBLK)))
    
    ENDDO

  ENDDO

ENDDO


GUSERV=KRR/=0
CALL PHI3_MANYBLOCKS (D, CSTURB, TURBN, ZREDTH1, ZREDR1, ZRED2TH3, ZRED2R3&
&, ZRED2THR3, "1DIM", GUSERV, ZPHI3, LDACC = LDACC, KGPBLKS = KGPBLKS)

IF (KRR/=0) THEN
  CALL PSI3_MANYBLOCKS (D, CSTURB, TURBN, ZREDR1, ZREDTH1, ZRED2R3, ZRED2TH3&
  &, ZRED2THR3, "1DIM", GUSERV, ZPSI3, LDACC = LDACC, KGPBLKS = KGPBLKS)
ELSE
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZPSI3 (JI, JK, JBLK)=1.
      
      ENDDO

    ENDDO

  ENDDO

ENDIF

CALL PSI_SV_MANYBLOCKS (D, CSTURB, TURBN, KSV, ZREDTH1, ZREDR1, ZREDS1, ZRED2THS&
&, ZRED2RS, ZPHI3, ZPSI3, ZPSI_SV, LDACC = LDACC, KGPBLKS = KGPBLKS)


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    ZLM (JI,:, JBLK)=PLM (JI,:, JBLK)
  ENDDO

ENDDO


CALL TURB_VER_THERMO_FLUX_MANYBLOCKS (D, CST, CSTURB, TURBN, TLES, KRR, KRRL, KRRI, KSV, KGRADIENTS&
&, OOCEAN, ODEEPOC, .FALSE., OCOUPLES, OCOMPUTE_SRC, PEXPL, PTSTEP, TPFILE, PDXX, PDYY, PDZZ, PDZX&
&, PDZY, PDIRCOSZW, PZZ, PRHODJ, PTHVREF, PHGRAD, PZS, PSFTHM, PSFRM, PSFTHP, PSFRP, PWM, PTHLM,&
& PRM, PSVM, PTKEM, ZLM, PLEPS, PLOCPEXNM, PATHETA, PAMOIST, PSRCM, PFRAC_ICE, ZBETA, ZSQRT_TKE,&
& ZDTH_DZ, ZDR_DZ, ZRED2TH3, ZRED2R3, ZRED2THR3, ZBLL_O_E, ZETHETA, ZEMOIST, ZREDTH1, ZREDR1, ZPHI3&
&, ZPSI3, ZD, PFWTH, PFWR, PFTH2, PFR2, PFTHR, MFMOIST, PBL_DEPTH, ZWTHV, PRTHLS, PRRS, ZTHLP, ZRP&
&, PTP, PWTH, PWRC, PSSTFL, PSSTFL_C, PSSRFL_C, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL TURB_VER_THERMO_CORR_MANYBLOCKS (D, CST, CSTURB, TURBN, NEBN, TLES, KRR, KRRL, KRRI&
&, KSV, OCOMPUTE_SRC, OCOUPLES, PEXPL, TPFILE, PDXX, PDYY, PDZZ, PDZX, PDZY, PDIRCOSZW,&
& PRHODJ, PTHVREF, PSFTHM, PSFRM, PSFTHP, PSFRP, PWM, PTHLM, PRM, PSVM, PTKEM, ZLM, PLEPS&
&, PLOCPEXNM, PATHETA, PAMOIST, ZBETA, ZSQRT_TKE, ZDTH_DZ, ZDR_DZ, ZRED2TH3, ZRED2R3, ZRED2THR3&
&, ZBLL_O_E, ZETHETA, ZEMOIST, ZREDTH1, ZREDR1, ZPHI3, ZPSI3, ZD, PFWTH, PFWR, PFTH2, PFR2&
&, PFTHR, ZTHLP, ZRP, MFMOIST, PSIGS, LDACC = LDACC, KGPBLKS = KGPBLKS)

CALL TURB_VER_DYN_FLUX_MANYBLOCKS (D, CST, CSTURB, TURBN, TLES, KSV, .FALSE., .FALSE., KRR&
&, OOCEAN, OCOUPLES, PEXPL, PTSTEP, TPFILE, PDXX, PDYY, PDZZ, PDZX, PDZY, PDIRCOSZW, PZZ, PCOSSLOPE&
&, PSINSLOPE, PRHODJ, PSFUM, PSFVM, PCDUEFF, PTAU11M, PTAU12M, PTAU33M, PTHLM, PRM, PSVM, PUM&
&, PVM, PWM, PUSLOPEM, PVSLOPEM, PTKEM, ZLM, MFMOIST, ZWU, ZWV, PRUS, PRVS, PRWS, PDP, PTP&
&, PSSUFL_C, PSSVFL_C, PSSUFL, PSSVFL, LDACC = LDACC, KGPBLKS = KGPBLKS)


IF (LHOOK) CALL DR_HOOK ('TURB_VER_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE TURB_VER_MANYBLOCKS

ENDMODULE MODE_TURB_VER_MANYBLOCKS
