MODULE MODE_SHUMAN_PHY_MANYBLOCKS


IMPLICIT NONE



CONTAINS
SUBROUTINE MYF_PHY_MANYBLOCKS (D, PA, PMYF, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_PARAMETERS
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(D%NIT, D%NJT, D%NKT, KGPBLKS)
REAL, INTENT (OUT)::PMYF(D%NIT, D%NJT, D%NKT, KGPBLKS)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JI
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PMYF) 

IF (LHOOK) CALL DR_HOOK ('MYF_MANYBLOCKS', 0, ZHOOK_HANDLE)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    PMYF(JI,:,:, JBLK)=PA(JI,:,:, JBLK)
  ENDDO

ENDDO

IF (LHOOK) CALL DR_HOOK ('MYF_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE MYF_PHY_MANYBLOCKS

SUBROUTINE MYF2D_PHY_MANYBLOCKS (D, PA, PMYF, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_PARAMETERS
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(D%NIT, D%NJT, KGPBLKS)
REAL, INTENT (OUT)::PMYF(D%NIT, D%NJT, KGPBLKS)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JI
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PMYF) 

IF (LHOOK) CALL DR_HOOK ('MYF_MANYBLOCKS', 0, ZHOOK_HANDLE)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    PMYF(JI,:, JBLK)=PA(JI,:, JBLK)
  ENDDO

ENDDO

IF (LHOOK) CALL DR_HOOK ('MYF_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE MYF2D_PHY_MANYBLOCKS

SUBROUTINE MYM2D_PHY_MANYBLOCKS (D, PA, PMYM, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_PARAMETERS
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(D%NIT, D%NJT, KGPBLKS)
REAL, INTENT (OUT)::PMYM(D%NIT, D%NJT, KGPBLKS)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JI
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PMYM) 

IF (LHOOK) CALL DR_HOOK ('MYM_MANYBLOCKS', 0, ZHOOK_HANDLE)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    PMYM(JI,:, JBLK)=PA(JI,:, JBLK)
  ENDDO

ENDDO

IF (LHOOK) CALL DR_HOOK ('MYM_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE MYM2D_PHY_MANYBLOCKS

SUBROUTINE MYM_PHY_MANYBLOCKS (D, PA, PMYM, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_PARAMETERS
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(D%NIT, D%NJT, D%NKT, KGPBLKS)
REAL, INTENT (OUT)::PMYM(D%NIT, D%NJT, D%NKT, KGPBLKS)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
INTEGER::IJU
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JI
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PMYM) 

IF (LHOOK) CALL DR_HOOK ('MYM_MANYBLOCKS', 0, ZHOOK_HANDLE)
IJU=SIZE (PA, 2)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    PMYM(JI,:,:, JBLK)=PA(JI,:,:, JBLK)
  ENDDO

ENDDO

IF (LHOOK) CALL DR_HOOK ('MYM_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE MYM_PHY_MANYBLOCKS

SUBROUTINE MZM_PHY_MANYBLOCKS (D, PA, PMZM, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(D%NIJT, D%NKT, KGPBLKS)
REAL, INTENT (OUT)::PMZM(D%NIJT, D%NKT, KGPBLKS)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
INTEGER::IKT
INTEGER::IIJE
INTEGER::IIJB
INTEGER::JI
INTEGER::JK
INTEGER::IKU
INTEGER::IKA
INTEGER::IKL
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PMZM) 

IF (LHOOK) CALL DR_HOOK ('MZM_MANYBLOCKS', 0, ZHOOK_HANDLE)
IIJB=D%NIJB
IIJE=D%NIJE
IKT=D%NKT
IKL=D%NKL
IKA=D%NKA
IKU=D%NKU

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=2, IKT-1
      
      PMZM (JI, JK, JBLK)=0.5*(PA (JI, JK, JBLK)+PA (JI, JK-IKL, JBLK))
    
    ENDDO

    
    PMZM (JI, IKA, JBLK)=-999.
    PMZM (JI, IKU, JBLK)=0.5*(PA (JI, IKU, JBLK)+PA (JI, IKU-IKL, JBLK))
  
  ENDDO

ENDDO


IF (LHOOK) CALL DR_HOOK ('MZM_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE MZM_PHY_MANYBLOCKS

SUBROUTINE DZM_PHY_MANYBLOCKS (D, PA, PDZM, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(D%NIJT, D%NKT, KGPBLKS)
REAL, INTENT (OUT)::PDZM(D%NIJT, D%NKT, KGPBLKS)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
INTEGER::IKT
INTEGER::IIJE
INTEGER::IIJB
INTEGER::JI
INTEGER::JK
INTEGER::IKU
INTEGER::IKA
INTEGER::IKL
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PDZM) 

IF (LHOOK) CALL DR_HOOK ('DZM_MANYBLOCKS', 0, ZHOOK_HANDLE)
IIJB=D%NIJB
IIJE=D%NIJE
IKT=D%NKT
IKL=D%NKL
IKA=D%NKA
IKU=D%NKU

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=2, IKT-1
      
      PDZM (JI, JK, JBLK)=PA (JI, JK, JBLK)-PA (JI, JK-IKL, JBLK)
    
    ENDDO

    
    PDZM (JI, IKA, JBLK)=-999.
    PDZM (JI, IKU, JBLK)=PA (JI, IKU, JBLK)-PA (JI, IKU-IKL, JBLK)
  
  ENDDO

ENDDO


IF (LHOOK) CALL DR_HOOK ('DZM_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE DZM_PHY_MANYBLOCKS

SUBROUTINE MXM_PHY_MANYBLOCKS (D, PA, PMXM, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_PARAMETERS
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(D%NIT, D%NJT, D%NKT, KGPBLKS)
REAL, INTENT (OUT)::PMXM(D%NIT, D%NJT, D%NKT, KGPBLKS)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
INTEGER::IIU
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JI
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PMXM) 

IF (LHOOK) CALL DR_HOOK ('MXM_MANYBLOCKS', 0, ZHOOK_HANDLE)
IIU=SIZE (PA, 1)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    PMXM(JI,:,:, JBLK)=PA(JI,:,:, JBLK)
  ENDDO

ENDDO

IF (LHOOK) CALL DR_HOOK ('MXM_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE MXM_PHY_MANYBLOCKS

SUBROUTINE MXM2D_PHY_MANYBLOCKS (D, PA, PMXM, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_PARAMETERS
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(D%NIT, D%NJT, KGPBLKS)
REAL, INTENT (OUT)::PMXM(D%NIT, D%NJT, KGPBLKS)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JI
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PMXM) 

IF (LHOOK) CALL DR_HOOK ('MXM_MANYBLOCKS', 0, ZHOOK_HANDLE)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    PMXM(JI,:, JBLK)=PA(JI,:, JBLK)
  ENDDO

ENDDO

IF (LHOOK) CALL DR_HOOK ('MXM_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE MXM2D_PHY_MANYBLOCKS

SUBROUTINE MXF_PHY_MANYBLOCKS (D, PA, PMXF, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(D%NIT, D%NJT, D%NKT, KGPBLKS)
REAL, INTENT (OUT)::PMXF(D%NIT, D%NJT, D%NKT, KGPBLKS)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JI
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PMXF) 

IF (LHOOK) CALL DR_HOOK ('MXF_MANYBLOCKS', 0, ZHOOK_HANDLE)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    PMXF(JI,:,:, JBLK)=PA(JI,:,:, JBLK)
  ENDDO

ENDDO

IF (LHOOK) CALL DR_HOOK ('MXF_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE MXF_PHY_MANYBLOCKS

SUBROUTINE MXF2D_PHY_MANYBLOCKS (D, PA, PMXF, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(D%NIT, D%NJT, KGPBLKS)
REAL, INTENT (OUT)::PMXF(D%NIT, D%NJT, KGPBLKS)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JI
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PMXF) 

IF (LHOOK) CALL DR_HOOK ('MXF_MANYBLOCKS', 0, ZHOOK_HANDLE)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    PMXF(JI,:, JBLK)=PA(JI,:, JBLK)
  ENDDO

ENDDO

IF (LHOOK) CALL DR_HOOK ('MXF_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE MXF2D_PHY_MANYBLOCKS

SUBROUTINE MZF_PHY_MANYBLOCKS (D, PA, PMZF, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(D%NIJT, D%NKT, KGPBLKS)
REAL, INTENT (OUT)::PMZF(D%NIJT, D%NKT, KGPBLKS)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
INTEGER::IKT
INTEGER::IIJE
INTEGER::IIJB
INTEGER::JI
INTEGER::JK
INTEGER::IKU
INTEGER::IKA
INTEGER::IKL
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PMZF) 

IF (LHOOK) CALL DR_HOOK ('MZF_MANYBLOCKS', 0, ZHOOK_HANDLE)
IIJB=D%NIJB
IIJE=D%NIJE
IKT=D%NKT
IKL=D%NKL
IKA=D%NKA
IKU=D%NKU

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=2, IKT-1
      
      PMZF (JI, JK, JBLK)=0.5*(PA (JI, JK, JBLK)+PA (JI, JK+IKL, JBLK))
    
    ENDDO

    
    PMZF (JI, IKU, JBLK)=-999.
    PMZF (JI, IKA, JBLK)=0.5*(PA (JI, IKA, JBLK)+PA (JI, IKA+IKL, JBLK))
  
  ENDDO

ENDDO


IF (LHOOK) CALL DR_HOOK ('MZF_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE MZF_PHY_MANYBLOCKS

SUBROUTINE DXF2D_PHY_MANYBLOCKS (D, PA, PDXF, LDACC, KGPBLKS)
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_PARAMETERS,ONLY:JPHEXT
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(:, :, :) ! (D%NIT, D%NJT)
REAL, INTENT (OUT)::PDXF(:, :, :) ! (D%NIT, D%NJT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
INTEGER::JI
INTEGER::IIU
INTEGER::IJU
INTEGER::JJ
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PDXF) 



!$ACC END DATA
END SUBROUTINE DXF2D_PHY_MANYBLOCKS

SUBROUTINE DZF_PHY_MANYBLOCKS (D, PA, PDZF, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(D%NIJT, D%NKT, KGPBLKS)
REAL, INTENT (OUT)::PDZF(D%NIJT, D%NKT, KGPBLKS)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
INTEGER::IKT
INTEGER::IIJE
INTEGER::IIJB
INTEGER::JI
INTEGER::JK
INTEGER::IKU
INTEGER::IKA
INTEGER::IKL
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PDZF) 

IF (LHOOK) CALL DR_HOOK ('DZF_MANYBLOCKS', 0, ZHOOK_HANDLE)
IIJB=D%NIJB
IIJE=D%NIJE
IKT=D%NKT
IKL=D%NKL
IKA=D%NKA
IKU=D%NKU

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=2, IKT-1
      
      PDZF (JI, JK, JBLK)=PA (JI, JK+IKL, JBLK)-PA (JI, JK, JBLK)
    
    ENDDO

    
    PDZF (JI, IKA, JBLK)=PA (JI, IKA+IKL, JBLK)-PA (JI, IKA, JBLK)
    PDZF (JI, IKU, JBLK)=-999.
  
  ENDDO

ENDDO


IF (LHOOK) CALL DR_HOOK ('DZF_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE DZF_PHY_MANYBLOCKS

SUBROUTINE DXM2D_PHY_MANYBLOCKS (D, PA, PDXM, LDACC, KGPBLKS)
USE MODD_PARAMETERS,ONLY:JPHEXT
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(:, :, :) ! (D%NIT, D%NJT)
REAL, INTENT (OUT)::PDXM(:, :, :) ! (D%NIT, D%NJT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JI
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PDXM) 



!$ACC END DATA
END SUBROUTINE DXM2D_PHY_MANYBLOCKS

SUBROUTINE DYM_PHY_MANYBLOCKS (D, PA, PDYM, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_PARAMETERS,ONLY:JPHEXT
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (OUT)::PDYM(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
INTEGER::JJ
INTEGER::IJU
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JI
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PDYM) 

IF (LHOOK) CALL DR_HOOK ('DYM_MANYBLOCKS', 0, ZHOOK_HANDLE)
IJU=SIZE (PA, 2)

DO JJ=2, IJU
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      PDYM (JI, JJ,:, JBLK)=PA (JI, JJ,:, JBLK)-PA (JI, JJ-1,:, JBLK)
    ENDDO

  ENDDO

ENDDO


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    PDYM (JI, 1,:, JBLK)=PDYM (JI, IJU-2*JPHEXT+1,:, JBLK)
  ENDDO

ENDDO

IF (LHOOK) CALL DR_HOOK ('DYM_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE DYM_PHY_MANYBLOCKS

SUBROUTINE DYM2D_PHY_MANYBLOCKS (D, PA, PDYM, LDACC, KGPBLKS)
USE MODD_PARAMETERS,ONLY:JPHEXT
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(:, :, :) ! (D%NIT, D%NJT)
REAL, INTENT (OUT)::PDYM(:, :, :) ! (D%NIT, D%NJT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JI
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PDYM) 



!$ACC END DATA
END SUBROUTINE DYM2D_PHY_MANYBLOCKS

SUBROUTINE DXM_PHY_MANYBLOCKS (D, PA, PDXM, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_PARAMETERS,ONLY:JPHEXT
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (OUT)::PDXM(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
INTEGER::JI
INTEGER::IIU
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PDXM) 

IF (LHOOK) CALL DR_HOOK ('DXM_MANYBLOCKS', 0, ZHOOK_HANDLE)
IIU=SIZE (PA, 1)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    PDXM (JI,:,:, JBLK)=PA (JI,:,:, JBLK)-PA (JI,:,:, JBLK)
    
    PDXM (JI,:,:, JBLK)=PDXM (JI,:,:, JBLK)
  ENDDO

ENDDO


IF (LHOOK) CALL DR_HOOK ('DXM_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE DXM_PHY_MANYBLOCKS

SUBROUTINE DXF_PHY_MANYBLOCKS (D, PA, PDXF, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (OUT)::PDXF(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JI
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PDXF) 

IF (LHOOK) CALL DR_HOOK ('DXF_MANYBLOCKS', 0, ZHOOK_HANDLE)
IF (LHOOK) CALL DR_HOOK ('DXF_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE DXF_PHY_MANYBLOCKS

SUBROUTINE DYF_PHY_MANYBLOCKS (D, PA, PDYF, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (OUT)::PDYF(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JI
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PDYF) 

IF (LHOOK) CALL DR_HOOK ('DYF_MANYBLOCKS', 0, ZHOOK_HANDLE)
IF (LHOOK) CALL DR_HOOK ('DYF_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE DYF_PHY_MANYBLOCKS

SUBROUTINE DYF2D_PHY_MANYBLOCKS (D, PA, PDYF, LDACC, KGPBLKS)
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_PARAMETERS,ONLY:JPHEXT
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(:, :, :) ! (D%NIT, D%NJT)
REAL, INTENT (OUT)::PDYF(:, :, :) ! (D%NIT, D%NJT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
INTEGER::JI
INTEGER::JJ
INTEGER::IJU
INTEGER::IIU
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PDYF) 



!$ACC END DATA
END SUBROUTINE DYF2D_PHY_MANYBLOCKS

ENDMODULE MODE_SHUMAN_PHY_MANYBLOCKS
