MODULE MODE_GRADIENT_W_PHY_MANYBLOCKS


IMPLICIT NONE



CONTAINS
SUBROUTINE GX_W_UW_PHY_MANYBLOCKS (D, OFLAT, PA, PDXX, PDZZ, PDZX, PGX_W_UW, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODE_SHUMAN_PHY,ONLY:MZM_PHY, DXM_PHY, MZF_PHY, MXM_PHY, DZM_PHY
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MZM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MZF_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MXM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : DZM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : DXM_PHY_MANYBLOCKS
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PDXX(D%NIT, D%NJT, D%NKT, KGPBLKS)
REAL, INTENT (IN)::PDZZ(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PDZX(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
LOGICAL, INTENT (IN)::OFLAT
REAL, INTENT (OUT)::PGX_W_UW(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL::ZWORK5(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK4(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK3(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK2(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK1(D%NIT, D%NJT, D%NKT,KGPBLKS)
INTEGER::IKT
INTEGER::IJE
INTEGER::IIE
INTEGER::IJB
INTEGER::IIB
INTEGER::JK
INTEGER::JJ
INTEGER::JI
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&CREATE (ZWORK1, ZWORK2, ZWORK3, ZWORK4, ZWORK5) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PDXX, PDZX, PDZZ, PGX_W_UW) 

IF (LHOOK) CALL DR_HOOK ('GX_W_UW_MANYBLOCKS', 0, ZHOOK_HANDLE)
IIE=D%NIEC
IIB=D%NIBC
IJE=D%NJEC
IJB=D%NJBC
IKT=D%NKT
CALL MZM_PHY_MANYBLOCKS (D, PDXX, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL DXM_PHY_MANYBLOCKS (D, PA, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JJ, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT

      DO JJ=IJB, IJE
        
        ZWORK3 (JI, JJ, JK, JBLK)=ZWORK2 (JI, JJ, JK, JBLK)/ZWORK1 (JI, JJ, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDDO


CALL MZF_PHY_MANYBLOCKS (D, PA, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MXM_PHY_MANYBLOCKS (D, ZWORK2, ZWORK4, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL DZM_PHY_MANYBLOCKS (D, ZWORK4, ZWORK5, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MXM_PHY_MANYBLOCKS (D, PDZZ, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JJ, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT

      DO JJ=IJB, IJE
        
        PGX_W_UW (JI, JJ, JK, JBLK)=ZWORK3 (JI, JJ, JK, JBLK)-ZWORK5 (JI, JJ, JK, JBLK)*PDZX&
        & (JI, JJ, JK, JBLK)/(ZWORK1 (JI, JJ, JK, JBLK)*ZWORK2 (JI, JJ, JK, JBLK))
      
      ENDDO

    ENDDO

  ENDDO

ENDDO


IF (LHOOK) CALL DR_HOOK ('GX_W_UW_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE GX_W_UW_PHY_MANYBLOCKS

SUBROUTINE GY_W_VW_PHY_MANYBLOCKS (D, OFLAT, PA, PDYY, PDZZ, PDZY, PGY_W_VW, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODE_SHUMAN_PHY,ONLY:MZM_PHY, DYM_PHY, MZF_PHY, MYM_PHY, DZM_PHY
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MZM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MZF_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MYM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : DZM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : DYM_PHY_MANYBLOCKS
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PDYY(D%NIT, D%NJT, D%NKT, KGPBLKS)
REAL, INTENT (IN)::PDZZ(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PDZY(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
LOGICAL, INTENT (IN)::OFLAT
REAL, INTENT (OUT)::PGY_W_VW(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL::ZWORK5(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK4(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK3(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK2(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK1(D%NIT, D%NJT, D%NKT,KGPBLKS)
INTEGER::IKT
INTEGER::IJE
INTEGER::IIE
INTEGER::IJB
INTEGER::IIB
INTEGER::JK
INTEGER::JJ
INTEGER::JI
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&CREATE (ZWORK1, ZWORK2, ZWORK3, ZWORK4, ZWORK5) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PDYY, PDZY, PDZZ, PGY_W_VW) 

IF (LHOOK) CALL DR_HOOK ('GY_W_VW_MANYBLOCKS', 0, ZHOOK_HANDLE)
IIE=D%NIEC
IIB=D%NIBC
IJE=D%NJEC
IJB=D%NJBC
IKT=D%NKT
CALL MZM_PHY_MANYBLOCKS (D, PDYY, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL DYM_PHY_MANYBLOCKS (D, PA, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JJ, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT

      DO JJ=IJB, IJE
        
        ZWORK3 (JI, JJ, JK, JBLK)=ZWORK2 (JI, JJ, JK, JBLK)/ZWORK1 (JI, JJ, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDDO


CALL MZF_PHY_MANYBLOCKS (D, PA, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MYM_PHY_MANYBLOCKS (D, ZWORK2, ZWORK4, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL DZM_PHY_MANYBLOCKS (D, ZWORK4, ZWORK5, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MYM_PHY_MANYBLOCKS (D, PDZZ, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JJ, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT

      DO JJ=IJB, IJE
        
        PGY_W_VW (JI, JJ, JK, JBLK)=ZWORK3 (JI, JJ, JK, JBLK)-ZWORK5 (JI, JJ, JK, JBLK)*PDZY&
        & (JI, JJ, JK, JBLK)/(ZWORK1 (JI, JJ, JK, JBLK)*ZWORK2 (JI, JJ, JK, JBLK))
      
      ENDDO

    ENDDO

  ENDDO

ENDDO


IF (LHOOK) CALL DR_HOOK ('GY_W_VW_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE GY_W_VW_PHY_MANYBLOCKS

SUBROUTINE GZ_W_M_PHY_MANYBLOCKS (D, PA, PDZZ, PGZ_W_M, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODE_SHUMAN_PHY,ONLY:DZF_PHY, MZF_PHY
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MZF_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : DZF_PHY_MANYBLOCKS
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PDZZ(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (OUT)::PGZ_W_M(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL::ZWORK2(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK1(D%NIT, D%NJT, D%NKT,KGPBLKS)
INTEGER::IKT
INTEGER::IJE
INTEGER::IIE
INTEGER::IJB
INTEGER::IIB
INTEGER::JK
INTEGER::JJ
INTEGER::JI
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&CREATE (ZWORK1, ZWORK2) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PDZZ, PGZ_W_M) 

IF (LHOOK) CALL DR_HOOK ('GZ_W_M_MANYBLOCKS', 0, ZHOOK_HANDLE)
IIE=D%NIEC
IIB=D%NIBC
IJE=D%NJEC
IJB=D%NJBC
IKT=D%NKT
CALL DZF_PHY_MANYBLOCKS (D, PA, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MZF_PHY_MANYBLOCKS (D, PDZZ, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JJ, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT

      DO JJ=IJB, IJE
        
        PGZ_W_M (JI, JJ, JK, JBLK)=ZWORK1 (JI, JJ, JK, JBLK)/ZWORK2 (JI, JJ, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDDO

IF (LHOOK) CALL DR_HOOK ('GZ_W_M_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE GZ_W_M_PHY_MANYBLOCKS

ENDMODULE MODE_GRADIENT_W_PHY_MANYBLOCKS
