
MODULE MODE_CLOUD_MODIF_LM_MANYBLOCKS


IMPLICIT NONE



CONTAINS
SUBROUTINE CLOUD_MODIF_LM_MANYBLOCKS (D, CST, CSTURB, TURBN, TPFILE, TZFIELD, KRR&
&, KRRI, OCLOUDMODIFLM, OOCEAN, OCOMPUTE_SRC, O2D, HTURBLEN_CL, PDZZ, PDXX, PDYY,&
& PZZ, PRT, PTKET, PTHLT, PTHLM, PRM, PTHVREF, PLOCPEXNM, PSRCT, PCOEF_AMPL_SAT, PAMOIST&
&, PATHETA, PDIRCOSZW, PCEI, PCEI_MIN, PCEI_MAX, PLM, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_CST,ONLY:CST_T
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_IO,ONLY:TFILEDATA
USE MODD_FIELD,ONLY:TFIELDMETADATA, TYPEREAL
USE MODD_TURB_N,ONLY:TURB_T
USE MODD_CTURB,ONLY:CSTURB_T
USE MODE_BL89,ONLY:BL89
USE MODE_BL89_MANYBLOCKS, ONLY : BL89_MANYBLOCKS
USE MODE_DELT,ONLY:DELT
USE MODE_DELT_MANYBLOCKS, ONLY : DELT_MANYBLOCKS
USE MODE_DEAR,ONLY:DEAR
USE MODE_DEAR_MANYBLOCKS, ONLY : DEAR_MANYBLOCKS
USE MODE_IO_FIELD_WRITE_PHY,ONLY:IO_FIELD_WRITE_PHY
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
TYPE (CST_T), INTENT (IN)::CST
TYPE (CSTURB_T), INTENT (IN)::CSTURB
TYPE (TURB_T), INTENT (IN)::TURBN
TYPE (TFIELDMETADATA), INTENT (INOUT)::TZFIELD
TYPE (TFILEDATA), INTENT (INOUT)::TPFILE
INTEGER, INTENT (IN)::KRR
INTEGER, INTENT (IN)::KRRI
LOGICAL, INTENT (IN)::OCLOUDMODIFLM
LOGICAL, INTENT (IN)::OOCEAN
LOGICAL, INTENT (IN)::O2D
LOGICAL, INTENT (IN)::OCOMPUTE_SRC
CHARACTER (LEN=4), INTENT (IN)::HTURBLEN_CL
REAL, INTENT (IN)::PTKET (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDZZ (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PZZ (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHVREF (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PSRCT (:, :, :)
REAL, INTENT (IN)::PCOEF_AMPL_SAT
REAL, INTENT (IN)::PDIRCOSZW (:, :) ! (D%NIJT)
REAL, INTENT (IN)::PCEI (:, :, :)
REAL, INTENT (IN)::PCEI_MAX
REAL, INTENT (IN)::PCEI_MIN
REAL, INTENT (IN)::PDXX (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDYY (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHLT (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHLM (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PRM (:, :, :, :) ! (D%NIJT, D%NKT, KRR)
REAL, INTENT (IN)::PLOCPEXNM (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PRT (:, :, :, :) ! (D%NIJT, D%NKT, KRR)
REAL, INTENT (INOUT)::PLM (:, :, :) ! (D%NIJT, D%NKT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL, INTENT (INOUT)::PAMOIST (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PATHETA (:, :, :) ! (D%NIJT, D%NKT)
REAL::ZWORK2 (D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK1 (D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK2D (D%NIJT,KGPBLKS)
REAL::ZCOEF_AMPL (D%NIJT, D%NKT,KGPBLKS)
REAL::ZSHEAR (D%NIJT, D%NKT,KGPBLKS)
REAL::PCOEF_AMPL_CEI_NUL
REAL::ZPENTE
REAL::PLM_CLOUD (D%NIJT, D%NKT,KGPBLKS)
INTEGER::IKL
INTEGER::IKT
INTEGER::IKA
INTEGER::IKU
INTEGER::IKE
INTEGER::IKB
INTEGER::IKTE
INTEGER::IIJE
INTEGER::IKTB
INTEGER::IIJB
INTEGER::JI
INTEGER::JK
REAL (KIND=JPHOOK)::ZHOOK_HANDLE2
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&CREATE (PLM_CLOUD, ZCOEF_AMPL, ZSHEAR, ZWORK1, ZWORK2, ZWORK2D) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (CST, CSTURB, D, PAMOIST, PATHETA, PCEI, PDIRCOSZW, PDXX, PDYY, PDZZ, PLM, &
!$ACC&         PLOCPEXNM, PRM, PRT, PSRCT, PTHLM, PTHLT, PTHVREF, PTKET, PZZ, TPFILE, &
!$ACC&         TURBN, TZFIELD) 

IF (LHOOK) CALL DR_HOOK ('TURB:CLOUD_MODIF_LM_MANYBLOCKS', 0, ZHOOK_HANDLE2)
IKT=D%NKT
IKTB=D%NKTB
IKTE=D%NKTE
IKE=D%NKE
IKA=D%NKA
IKU=D%NKU
IKL=D%NKL
IIJE=D%NIJE
IIJB=D%NIJB
ZPENTE=(PCOEF_AMPL_SAT-1.)/(PCEI_MAX-PCEI_MIN)
PCOEF_AMPL_CEI_NUL=1.-ZPENTE*PCEI_MIN

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZCOEF_AMPL (JI, JK, JBLK)=1.
    
    ENDDO


    DO JK=1, IKT

      

      IF (PCEI (JI, JK, JBLK)>=PCEI_MAX) THEN
        ZCOEF_AMPL (JI, JK, JBLK)=PCOEF_AMPL_SAT
      ENDIF

    
    ENDDO


    DO JK=1, IKT

      

      IF (PCEI (JI, JK, JBLK)<PCEI_MAX.AND.PCEI (JI, JK, JBLK)>PCEI_MIN) THEN
        ZCOEF_AMPL (JI, JK, JBLK)=ZPENTE*PCEI (JI, JK, JBLK)+PCOEF_AMPL_CEI_NUL
      ENDIF

    
    ENDDO

  ENDDO

ENDDO




IF (HTURBLEN_CL==TURBN%CTURBLEN) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        PLM_CLOUD (JI, JK, JBLK)=PLM (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ELSE

  SELECTCASE (HTURBLEN_CL)
  CASE ('BL89','RM17','HM21')
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZSHEAR (JI, JK, JBLK)=0.
        
        ENDDO

      ENDDO

    ENDDO

    CALL BL89_MANYBLOCKS (D, CST, CSTURB, TURBN, PZZ, PDZZ, PTHVREF, PTHLM, KRR,&
    & PRM, PTKET, ZSHEAR, PLM_CLOUD, OOCEAN, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CASE ('DELT')
    CALL DELT_MANYBLOCKS (D, TURBN, .FALSE.,.TRUE., OOCEAN, PZZ, PDYY,&
    & PDXX, PDIRCOSZW, PLM_CLOUD, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CASE ('DEAR')
    CALL DEAR_MANYBLOCKS (D, CST, TURBN, KRR, KRRI, .FALSE., OCOMPUTE_SRC, OOCEAN&
    &, PLM_CLOUD, PRT, PDZZ, PZZ, PTKET, PTHVREF, PTHLT, PLOCPEXNM, PSRCT, PAMOIST&
    &, PDIRCOSZW, PDXX, PDYY, PATHETA, LDACC = LDACC, KGPBLKS = KGPBLKS)
  ENDSELECT

ENDIF



!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT

      

      IF (ZCOEF_AMPL (JI, JK, JBLK)/=1.) THEN
        PLM (JI, JK, JBLK)=ZCOEF_AMPL (JI, JK, JBLK)*PLM_CLOUD (JI, JK, JBLK)
      ENDIF

    
    ENDDO


    DO JK=1, IKT

      

      IF (PCEI (JI, JK, JBLK)==-1.) THEN
        PLM (JI, JK, JBLK)=PLM_CLOUD (JI, JK, JBLK)
      ENDIF

    
    ENDDO

  ENDDO

ENDDO



IF (LHOOK) CALL DR_HOOK ('TURB:CLOUD_MODIF_LM_MANYBLOCKS', 1, ZHOOK_HANDLE2)
!$ACC END DATA

END SUBROUTINE CLOUD_MODIF_LM_MANYBLOCKS

ENDMODULE MODE_CLOUD_MODIF_LM_MANYBLOCKS
