MODULE MODE_GRADIENT_U_PHY_MANYBLOCKS


IMPLICIT NONE



CONTAINS
SUBROUTINE GZ_U_UW_PHY_MANYBLOCKS (D, PA, PDZZ, PGZ_U_UW, LDACC, KGPBLKS)
USE MODE_SHUMAN_PHY,ONLY:DZM_PHY, MXM_PHY
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MXM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : DZM_PHY_MANYBLOCKS
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PA(D%NIT, D%NJT, D%NKT, KGPBLKS)
REAL, INTENT (IN)::PDZZ(D%NIT, D%NJT, D%NKT, KGPBLKS)
REAL, INTENT (OUT)::PGZ_U_UW(D%NIT, D%NJT, D%NKT, KGPBLKS)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL::PDZZ_WORK(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::PA_WORK(D%NIT, D%NJT, D%NKT,KGPBLKS)
INTEGER::IKT
INTEGER::IJE
INTEGER::IJB
INTEGER::IIE
INTEGER::IIB
INTEGER::JK
INTEGER::JJ
INTEGER::JI
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&CREATE (PA_WORK, PDZZ_WORK) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PDZZ, PGZ_U_UW) 


IIE=D%NIEC
IIB=D%NIBC
IJE=D%NJEC
IJB=D%NJBC
IKT=D%NKT
CALL DZM_PHY_MANYBLOCKS (D, PA, PA_WORK, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MXM_PHY_MANYBLOCKS (D, PDZZ, PDZZ_WORK, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JJ, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT

      DO JJ=IJB, IJE
        
        PGZ_U_UW (JI, JJ, JK, JBLK)=PA_WORK (JI, JJ, JK, JBLK)/PDZZ_WORK (JI, JJ, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDDO


!$ACC END DATA
END SUBROUTINE GZ_U_UW_PHY_MANYBLOCKS

SUBROUTINE GX_U_M_PHY_MANYBLOCKS (D, OFLAT, PA, PDXX, PDZZ, PDZX, PGX_U_M, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODE_SHUMAN_PHY,ONLY:DXF_PHY, MXF_PHY, DZM_PHY, MZF_PHY
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MZF_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MXF_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : DZM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : DXF_PHY_MANYBLOCKS
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
LOGICAL, INTENT (IN)::OFLAT
REAL, INTENT (IN)::PA(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PDXX(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PDZZ(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (IN)::PDZX(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
REAL, INTENT (OUT)::PGX_U_M(:, :, :, :) ! (D%NIT, D%NJT, D%NKT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL::ZWORK4(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK3(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK2(D%NIT, D%NJT, D%NKT,KGPBLKS)
REAL::ZWORK1(D%NIT, D%NJT, D%NKT,KGPBLKS)
INTEGER::IKT
INTEGER::IJE
INTEGER::IIE
INTEGER::IJB
INTEGER::IIB
INTEGER::JK
INTEGER::JJ
INTEGER::JI
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&CREATE (ZWORK1, ZWORK2, ZWORK3, ZWORK4) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (D, PA, PDXX, PDZX, PDZZ, PGX_U_M) 

IF (LHOOK) CALL DR_HOOK ('GX_U_M_MANYBLOCKS', 0, ZHOOK_HANDLE)
IIE=D%NIEC
IIB=D%NIBC
IJE=D%NJEC
IJB=D%NJBC
IKT=D%NKT
CALL DXF_PHY_MANYBLOCKS (D, PA, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MXF_PHY_MANYBLOCKS (D, PDXX, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)

CALL DZM_PHY_MANYBLOCKS (D, PA, ZWORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JJ, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT

      DO JJ=IJB, IJE
        
        ZWORK3 (JI, JJ, JK, JBLK)=ZWORK3 (JI, JJ, JK, JBLK)*PDZX (JI, JJ, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDDO

CALL MXF_PHY_MANYBLOCKS (D, ZWORK3, ZWORK4, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JJ, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT

      DO JJ=IJB, IJE
        
        ZWORK4 (JI, JJ, JK, JBLK)=ZWORK4 (JI, JJ, JK, JBLK)/PDZZ (JI, JJ, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDDO

CALL MZF_PHY_MANYBLOCKS (D, ZWORK4, ZWORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JJ, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT

      DO JJ=IJB, IJE
        
        PGX_U_M (JI, JJ, JK, JBLK)=(ZWORK1 (JI, JJ, JK, JBLK)-ZWORK3&
        & (JI, JJ, JK, JBLK))/ZWORK2 (JI, JJ, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDDO


IF (LHOOK) CALL DR_HOOK ('GX_U_M_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE GX_U_M_PHY_MANYBLOCKS

ENDMODULE MODE_GRADIENT_U_PHY_MANYBLOCKS
