
MODULE MODE_DEAR_MANYBLOCKS


IMPLICIT NONE



CONTAINS
SUBROUTINE DEAR_MANYBLOCKS (D, CST, TURBN, KRR, KRRI, O2D, OCOMPUTE_SRC, OOCEAN, PLM, PRT, PDZZ, PZZ,&
& PTKET, PTHVREF, PTHLT, PLOCPEXNM, PSRCT, PAMOIST, PDIRCOSZW, PDXX, PDYY, PATHETA, LDACC, KGPBLKS)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_CST,ONLY:CST_T
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_TURB_N,ONLY:TURB_T
USE MODE_SHUMAN_PHY,ONLY:MXF_PHY, MYF_PHY
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MYF_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MXF_PHY_MANYBLOCKS
USE MODE_ETHETA,ONLY:ETHETA
USE MODE_ETHETA_MANYBLOCKS, ONLY : ETHETA_MANYBLOCKS
USE MODE_EMOIST,ONLY:EMOIST
USE MODE_EMOIST_MANYBLOCKS, ONLY : EMOIST_MANYBLOCKS
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
TYPE (CST_T), INTENT (IN)::CST
TYPE (TURB_T), INTENT (IN)::TURBN
LOGICAL, INTENT (IN)::OCOMPUTE_SRC
LOGICAL, INTENT (IN)::O2D
LOGICAL, INTENT (IN)::OOCEAN
INTEGER, INTENT (IN)::KRR
INTEGER, INTENT (IN)::KRRI
REAL, INTENT (IN)::PDZZ (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PZZ (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PTKET (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDIRCOSZW (:, :) ! (D%NIJT)
REAL, INTENT (IN)::PDXX (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDYY (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHVREF (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PSRCT (:, :, :)
!REAL, INTENT (IN)::PSRCT (MERGE (D%NIJT, 0, OCOMPUTE_SRC), MERGE (D%NKT, 0, OCOMPUTE_SRC))
REAL, INTENT (IN)::PRT (:, :, :, :) ! (D%NIJT, D%NKT, KRR)
REAL, INTENT (IN)::PTHLT (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PLOCPEXNM (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PATHETA (:, :, :) ! (D%NIJT, D%NKT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL, INTENT (INOUT)::PAMOIST (:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT)::PLM(:, :, :) ! (D%NIJT, D%NKT)
REAL::ZVAR
REAL::ZD
REAL::ZALPHA
LOGICAL::GZD
REAL::PWORK1 (D%NIJT, D%NKT,KGPBLKS)
REAL::PWORK2 (D%NIJT, D%NKT,KGPBLKS)
REAL::PWORK2D (D%NIJT,KGPBLKS)
REAL::ZETHETA (D%NIJT, D%NKT,KGPBLKS)
REAL::ZEMOIST (D%NIJT, D%NKT,KGPBLKS)
REAL::ZDRTDZ (D%NIJT, D%NKT,KGPBLKS)
REAL::ZDTHLDZ (D%NIJT, D%NKT,KGPBLKS)
REAL (KIND=JPHOOK)::ZHOOK_HANDLE2
INTEGER::IKL
INTEGER::IKT
INTEGER::IKA
INTEGER::IKU
INTEGER::IKE
INTEGER::IKB
INTEGER::IKTE
INTEGER::IIJE
INTEGER::IKTB
INTEGER::IIJB
INTEGER::JI
INTEGER::JK
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&CREATE (PWORK1, PWORK2, PWORK2D, ZDRTDZ, ZDTHLDZ, ZEMOIST, ZETHETA) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (CST, D, PAMOIST, PATHETA, PDIRCOSZW, PDXX, PDYY, PDZZ, PLM, PLOCPEXNM, &
!$ACC&         PRT, PSRCT, PTHLT, PTHVREF, PTKET, PZZ, TURBN) 

IF (LHOOK) CALL DR_HOOK ('TURB:DEAR_MANYBLOCKS', 0, ZHOOK_HANDLE2)
IKT=D%NKT
IKTB=D%NKTB
IKTE=D%NKTE
IKB=D%NKB
IKE=D%NKE
IKA=D%NKA
IKU=D%NKU
IKL=D%NKL
IIJE=D%NIJE
IIJB=D%NIJB

IF ("1DIM"/='1DIM') THEN
  CALL MXF_PHY_MANYBLOCKS (D, PDXX, PWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  CALL MYF_PHY_MANYBLOCKS (D, PDYY, PWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
ENDIF


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=IKTB, IKTE
      
      PLM (JI, JK, JBLK)=PZZ (JI, IKL+JK, JBLK)-PZZ (JI, JK, JBLK)
    
    ENDDO

    
    PLM (JI, IKU, JBLK)=PLM (JI, IKE, JBLK)
    PLM (JI, IKA, JBLK)=PZZ (JI, IKB, JBLK)-PZZ (JI, IKA, JBLK)
  
  ENDDO

ENDDO



IF ("1DIM"/='1DIM') THEN
  
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        PLM (JI, JK, JBLK)=(PLM (JI, JK, JBLK)*PWORK1 (JI, JK, JBLK)*PWORK2 (JI, JK, JBLK))**(1./3.)
      
      ENDDO

    ENDDO

  ENDDO

  
ENDIF

CALL ETHETA_MANYBLOCKS (D, CST, KRR, KRRI, PTHLT, PRT, PLOCPEXNM, PATHETA, PSRCT&
&, OOCEAN, OCOMPUTE_SRC, ZETHETA, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL EMOIST_MANYBLOCKS (D, CST, KRR, KRRI, PTHLT, PRT, PLOCPEXNM, PAMOIST&
&, PSRCT, OOCEAN, ZEMOIST, LDACC = LDACC, KGPBLKS = KGPBLKS)

IF (KRR>0) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK, ZVAR) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=IKTB+1, IKTE-1
        
        ZDTHLDZ (JI, JK, JBLK)=0.5*((PTHLT (JI, JK+IKL, JBLK)-PTHLT (JI, JK, JBLK))/PDZZ (JI, JK&
        &+IKL, JBLK)+(PTHLT (JI, JK, JBLK)-PTHLT (JI, JK-IKL, JBLK))/PDZZ (JI, JK, JBLK))
        ZDRTDZ (JI, JK, JBLK)=0.5*((PRT (JI, JK+IKL, 1, JBLK)-PRT (JI, JK, 1, JBLK))/PDZZ (JI, JK&
        &+IKL, JBLK)+(PRT (JI, JK, 1, JBLK)-PRT (JI, JK-IKL, 1, JBLK))/PDZZ (JI, JK, JBLK))
      
      ENDDO


      DO JK=IKTB+1, IKTE-1

        

        IF (OOCEAN) THEN
          ZVAR=CST%XG*(CST%XALPHAOC*ZDTHLDZ (JI, JK, JBLK)-CST%XBETAOC*ZDRTDZ (JI, JK, JBLK))
        ELSE
          ZVAR=CST%XG/PTHVREF (JI, JK, JBLK)*(ZETHETA (JI, JK, JBLK)*ZDTHLDZ&
          & (JI, JK, JBLK)+ZEMOIST (JI, JK, JBLK)*ZDRTDZ (JI, JK, JBLK))
        ENDIF


        IF (ZVAR>0.) THEN
          PLM (JI, JK, JBLK)=MAX (CST%XMNH_EPSILON, MIN (PLM (JI,&
          & JK, JBLK), 0.76*SQRT (PTKET (JI, JK, JBLK)/ZVAR)))
        ENDIF

      
      ENDDO

    ENDDO

  ENDDO

  
ELSE
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK, ZVAR) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=IKTB+1, IKTE-1
        
        ZDTHLDZ (JI, JK, JBLK)=0.5*((PTHLT (JI, JK+IKL, JBLK)-PTHLT (JI, JK, JBLK))/PDZZ (JI, JK&
        &+IKL, JBLK)+(PTHLT (JI, JK, JBLK)-PTHLT (JI, JK-IKL, JBLK))/PDZZ (JI, JK, JBLK))

        IF (OOCEAN) THEN
          ZVAR=CST%XG*CST%XALPHAOC*ZDTHLDZ (JI, JK, JBLK)
        ELSE
          ZVAR=CST%XG/PTHVREF (JI, JK, JBLK)*ZETHETA (JI, JK, JBLK)*ZDTHLDZ (JI, JK, JBLK)
        ENDIF


        IF (ZVAR>0.) THEN
          PLM (JI, JK, JBLK)=MAX (CST%XMNH_EPSILON, MIN (PLM (JI,&
          & JK, JBLK), 0.76*SQRT (PTKET (JI, JK, JBLK)/ZVAR)))
        ENDIF

      
      ENDDO

    ENDDO

  ENDDO

ENDIF


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    ZDTHLDZ (JI, IKB, JBLK)=(PTHLT (JI, IKB+IKL, JBLK)-PTHLT (JI, IKB, JBLK))/PDZZ (JI, IKB+IKL, JBLK)
  
  ENDDO

ENDDO


IF (KRR>0) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      
      ZDRTDZ (JI, IKB, JBLK)=(PRT (JI, IKB+IKL, 1, JBLK)-PRT (JI, IKB, 1, JBLK))/PDZZ (JI, IKB+IKL, JBLK)
    
    ENDDO

  ENDDO

ELSE
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      ZDRTDZ (JI, IKB, JBLK)=0
    ENDDO

  ENDDO

ENDIF


IF (OOCEAN) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      
      PWORK2D (JI, JBLK)=CST%XG*(CST%XALPHAOC*ZDTHLDZ (JI, IKB, JBLK)-CST%XBETAOC*ZDRTDZ (JI, IKB, JBLK))
    
    ENDDO

  ENDDO

ELSE
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      
      PWORK2D (JI, JBLK)=CST%XG/PTHVREF (JI, IKB, JBLK)*(ZETHETA (JI, IKB, JBLK)*ZDTHLDZ&
      & (JI, IKB, JBLK)+ZEMOIST (JI, IKB, JBLK)*ZDRTDZ (JI, IKB, JBLK))
    
    ENDDO

  ENDDO

ENDIF


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    

    IF (PWORK2D (JI, JBLK)>0.) THEN
      PLM (JI, IKB, JBLK)=MAX (CST%XMNH_EPSILON, MIN (PLM (JI, IKB, JBLK&
      &), 0.76*SQRT (PTKET (JI, IKB, JBLK)/PWORK2D (JI, JBLK))))
    ENDIF

  
  ENDDO

ENDDO


IF (.NOT.TURBN%LRMC01) THEN
  ZALPHA=0.5**(-1.5)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (GZD, JI, JK, ZD) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      
      GZD=.TRUE.

      IF (OOCEAN) THEN

        DO JK=IKTE, IKTB,-1
          ZD=ZALPHA*(PZZ (JI, IKTE+1, JBLK)-PZZ (JI, JK, JBLK))

          IF (PLM (JI, JK, JBLK)>ZD.AND.GZD) THEN
            PLM (JI, JK, JBLK)=ZD
          ELSE
            GZD=.FALSE.
          ENDIF

        ENDDO

      ELSE

        DO JK=IKTB, IKTE
          ZD=ZALPHA*(0.5*(PZZ (JI, JK, JBLK)+PZZ (JI, JK+IKL, JBLK))-PZZ (JI, IKB, JBLK))*PDIRCOSZW (JI, JBLK)

          IF (PLM (JI, JK, JBLK)>ZD.AND.GZD) THEN
            PLM (JI, JK, JBLK)=ZD
          ELSE
            GZD=.FALSE.
          ENDIF

        ENDDO

      ENDIF

    
    ENDDO

  ENDDO

ENDIF


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    PLM (JI, IKA, JBLK)=PLM (JI, IKB, JBLK)
    PLM (JI, IKE, JBLK)=PLM (JI, IKE-IKL, JBLK)
    PLM (JI, IKU, JBLK)=PLM (JI, IKU-IKL, JBLK)
  
  ENDDO

ENDDO

IF (LHOOK) CALL DR_HOOK ('TURB:DEAR_MANYBLOCKS', 1, ZHOOK_HANDLE2)
!$ACC END DATA

END SUBROUTINE DEAR_MANYBLOCKS

ENDMODULE MODE_DEAR_MANYBLOCKS
