
MODULE MODE_TURB_VER_DYN_FLUX_MANYBLOCKS


IMPLICIT NONE



CONTAINS
SUBROUTINE TURB_VER_DYN_FLUX_MANYBLOCKS (D, CST, CSTURB, TURBN, TLES, KSV, O2D, OFLAT,&
& KRR, OOCEAN, OCOUPLES, PEXPL, PTSTEP, TPFILE, PDXX, PDYY, PDZZ, PDZX, PDZY, PDIRCOSZW&
&, PZZ, PCOSSLOPE, PSINSLOPE, PRHODJ, PSFUM, PSFVM, PCDUEFF, PTAU11M, PTAU12M, PTAU33M&
&, PTHLM, PRM, PSVM, PUM, PVM, PWM, PUSLOPEM, PVSLOPEM, PTKEM, PLM, MFMOIST, PWU, PWV,&
& PRUS, PRVS, PRWS, PDP, PTP, PSSUFL_C, PSSVFL_C, PSSUFL, PSSVFL, LDACC, KGPBLKS)
USE MODE_SHUMAN_PHY,ONLY:MZM_PHY, MXM_PHY, MXM2D_PHY, DZM_PHY, MXF_PHY&
&, MZF_PHY, MXF2D_PHY, MYM_PHY, MYM2D_PHY, MYF_PHY, MYF2D_PHY
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MZM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MZF_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MYM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MYM2D_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MYF_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MYF2D_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MXM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MXM2D_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MXF_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MXF2D_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : DZM_PHY_MANYBLOCKS
USE MODE_TRIDIAG_WIND,ONLY:TRIDIAG_WIND
USE MODE_TRIDIAG_WIND_MANYBLOCKS, ONLY : TRIDIAG_WIND_MANYBLOCKS
USE MODE_IO_FIELD_WRITE_PHY,ONLY:IO_FIELD_WRITE_PHY
USE MODE_GRADIENT_U_PHY,ONLY:GZ_U_UW_PHY
USE MODE_GRADIENT_U_PHY_MANYBLOCKS, ONLY : GZ_U_UW_PHY_MANYBLOCKS
USE MODE_GRADIENT_V_PHY,ONLY:GZ_V_VW_PHY
USE MODE_GRADIENT_V_PHY_MANYBLOCKS, ONLY : GZ_V_VW_PHY_MANYBLOCKS
USE MODE_GRADIENT_W_PHY,ONLY:GZ_W_M_PHY
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_CST,ONLY:CST_T
USE MODD_CTURB,ONLY:CSTURB_T
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_FIELD,ONLY:TFIELDMETADATA, TYPEREAL
USE MODD_IO,ONLY:TFILEDATA
USE MODD_LES,ONLY:TLES_T
USE MODD_PARAMETERS,ONLY:XUNDEF
USE MODD_TURB_N,ONLY:TURB_T
USE MODI_LES_MEAN_SUBGRID_PHY
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

#ifdef MNH_COMPILER_CCE
#endif
TYPE (DIMPHYEX_T), INTENT (IN)::D
TYPE (CST_T), INTENT (IN)::CST
TYPE (CSTURB_T), INTENT (IN)::CSTURB
TYPE (TURB_T), INTENT (IN)::TURBN
TYPE (TLES_T), INTENT (INOUT)::TLES
INTEGER, INTENT (IN)::KSV
LOGICAL, INTENT (IN)::OOCEAN
LOGICAL, INTENT (IN)::O2D
LOGICAL, INTENT (IN)::OFLAT
LOGICAL, INTENT (IN)::OCOUPLES
INTEGER, INTENT (IN)::KRR
REAL, INTENT (IN)::PEXPL
REAL, INTENT (IN)::PTSTEP
TYPE (TFILEDATA), INTENT (INOUT)::TPFILE
REAL, INTENT (IN)::PDZY(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDZX(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDZZ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDYY(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDXX(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDIRCOSZW(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PZZ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PCOSSLOPE(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSINSLOPE(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PRHODJ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::MFMOIST(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PSFVM(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFUM(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PCDUEFF(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PTAU11M(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PTAU12M(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PTAU33M(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PTHLM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PWM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PVM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PUM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PRM(:, :, :, :) ! (D%NIJT, D%NKT, KRR)
REAL, INTENT (IN)::PSVM(:, :, :, :) ! (D%NIJT, D%NKT, KSV)
REAL, INTENT (IN)::PUSLOPEM(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PVSLOPEM(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PTKEM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PLM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT)::PWU(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT)::PWV(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRWS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRVS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRUS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT)::PDP(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PTP(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN), OPTIONAL, TARGET::PSSUFL_C(MERGE (D%NIJT, 0, OCOUPLES))
REAL, INTENT (IN), OPTIONAL, TARGET::PSSVFL_C(MERGE (D%NIJT, 0, OCOUPLES))
REAL, INTENT (IN), OPTIONAL, TARGET::PSSUFL(MERGE (D%NIJT, 0, OCOUPLES))
REAL, INTENT (IN), OPTIONAL, TARGET::PSSVFL(MERGE (D%NIJT, 0, OCOUPLES))
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL::ZPDZZ(D%NIJT,KGPBLKS)
REAL::ZPRHODJ(D%NIJT,KGPBLKS)
REAL::ZDIRSINZW(D%NIJT,KGPBLKS)
REAL::ZWORK61D(D%NIJT,KGPBLKS)
REAL::ZWORK51D(D%NIJT,KGPBLKS)
REAL::ZWORK41D(D%NIJT,KGPBLKS)
REAL::ZWORK31D(D%NIJT,KGPBLKS)
REAL::ZWORK21D(D%NIJT,KGPBLKS)
REAL::ZWORK11D(D%NIJT,KGPBLKS)
REAL::ZCOEFS(D%NIJT,KGPBLKS)
REAL::ZWORK5(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK4(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK3(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZKEFF(D%NIJT, D%NKT,KGPBLKS)
REAL::ZSOURCE(D%NIJT, D%NKT,KGPBLKS)
REAL::ZFLXZ(D%NIJT, D%NKT,KGPBLKS)
REAL::ZRES(D%NIJT, D%NKT,KGPBLKS)
REAL::ZA(D%NIJT, D%NKT,KGPBLKS)
INTEGER::IKU
INTEGER::IKA
INTEGER::IKE
INTEGER::IKB
INTEGER::IIJB
INTEGER::IIJE
INTEGER::IKT
INTEGER::IKTE
INTEGER::IKTB
INTEGER::JJ
INTEGER::JI
INTEGER::JK
INTEGER::JSV
INTEGER::IKL
REAL::ZFLUXSFCV(D%NIJT,KGPBLKS)
REAL::ZFLUXSFCU(D%NIJT,KGPBLKS)
REAL::ZVSLOPEM(D%NIJT,KGPBLKS)
REAL::ZUSLOPEM(D%NIJT,KGPBLKS)
REAL::ZCOEFFLXV(D%NIJT,KGPBLKS)
REAL::ZCOEFFLXU(D%NIJT,KGPBLKS)
REAL::ZCMFS
REAL::ZTIME2
REAL::ZTIME1
TYPE (TFIELDMETADATA)::TZFIELD
LOGICAL::GOCEAN
REAL::ZMXM2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMXM2D_WORK2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMZM2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMXM2D_WORK3(D%NIJT, D%NKT,KGPBLKS)
REAL::ZSHUGRADWK1_1D(D%NIJT,KGPBLKS)
REAL::ZMXM1D_WORK1(D%NIJT,KGPBLKS)
REAL::ZMXM1D_WORK2(D%NIJT,KGPBLKS)
REAL::ZMXM1D_WORK3(D%NIJT,KGPBLKS)
REAL::ZMXM1D_WORK4(D%NIJT,KGPBLKS)
REAL::ZSHUGRADWK1_2D(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDZM2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMZF2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZSHUGRADWK2_2D(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMXF2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZGZ_U_UW2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMXF1D_WORK1(D%NIJT,KGPBLKS)
REAL::ZSHUGRADWK2_1D(D%NIJT,KGPBLKS)
REAL::ZDXF2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMZF2D_WORK2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZGX_W_UW2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDXM1D_WORK1(D%NIJT,KGPBLKS)
REAL::ZMYM2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMYM2D_WORK2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMYM2D_WORK3(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMYM1D_WORK1(D%NIJT,KGPBLKS)
REAL::ZMYM1D_WORK2(D%NIJT,KGPBLKS)
REAL::ZMYM1D_WORK3(D%NIJT,KGPBLKS)
REAL::ZMYM1D_WORK4(D%NIJT,KGPBLKS)
REAL::ZMYF2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZGZ_V_VW2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMYF1D_WORK1(D%NIJT,KGPBLKS)
REAL::ZDYF2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZGY_W_VW2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDYM1D_WORK1(D%NIJT,KGPBLKS)
REAL::ZGZ_W_M2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZGX_M_U2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZGX_U_M2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZGY_M_V2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZGY_V_M2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
REAL, POINTER :: PSSUFL_PTR
REAL, POINTER :: PSSUFL_C_PTR
REAL, POINTER :: PSSVFL_PTR
REAL, POINTER :: PSSVFL_C_PTR
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&CREATE (ZA, ZCOEFFLXU, ZCOEFFLXV, ZCOEFS, ZDIRSINZW, ZDXF2D_WORK1, ZDXM1D_WORK1, &
!$ACC&        ZDYF2D_WORK1, ZDYM1D_WORK1, ZDZM2D_WORK1, ZFLUXSFCU, ZFLUXSFCV, &
!$ACC&        ZFLXZ, ZGX_M_U2D_WORK1, ZGX_U_M2D_WORK1, ZGX_W_UW2D_WORK1, &
!$ACC&        ZGY_M_V2D_WORK1, ZGY_V_M2D_WORK1, ZGY_W_VW2D_WORK1, ZGZ_U_UW2D_WORK1, &
!$ACC&        ZGZ_V_VW2D_WORK1, ZGZ_W_M2D_WORK1, ZKEFF, ZMXF1D_WORK1, ZMXF2D_WORK1, &
!$ACC&        ZMXM1D_WORK1, ZMXM1D_WORK2, ZMXM1D_WORK3, ZMXM1D_WORK4, ZMXM2D_WORK1, &
!$ACC&        ZMXM2D_WORK2, ZMXM2D_WORK3, ZMYF1D_WORK1, ZMYF2D_WORK1, ZMYM1D_WORK1, &
!$ACC&        ZMYM1D_WORK2, ZMYM1D_WORK3, ZMYM1D_WORK4, ZMYM2D_WORK1, ZMYM2D_WORK2, &
!$ACC&        ZMYM2D_WORK3, ZMZF2D_WORK1, ZMZF2D_WORK2, ZMZM2D_WORK1, ZRES, &
!$ACC&        ZSHUGRADWK1_1D, ZSHUGRADWK1_2D, ZSHUGRADWK2_1D, ZSHUGRADWK2_2D, &
!$ACC&        ZSOURCE, ZUSLOPEM, ZVSLOPEM, ZWORK1, ZWORK11D, ZWORK2, ZWORK21D, &
!$ACC&        ZWORK3, ZWORK31D, ZWORK4, ZWORK41D, ZWORK5, ZWORK51D, ZWORK61D, &
!$ACC&        ZPRHODJ, ZPDZZ) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (CST, CSTURB, D, MFMOIST, PCDUEFF, PCOSSLOPE, PDIRCOSZW, PDP, PDXX, PDYY, &
!$ACC&         PDZX, PDZY, PDZZ, PLM, PRHODJ, PRM, PRUS, PRVS, PRWS, PSFUM, PSFVM, PSINSLOPE, &
!$ACC&         PSSUFL, PSSUFL_C, PSSVFL, PSSVFL_C, PSVM, PTAU11M, PTAU12M, PTAU33M, &
!$ACC&         PTHLM, PTKEM, PTP, PUM, PUSLOPEM, PVM, PVSLOPEM, PWM, PWU, PWV, PZZ, TLES, &
!$ACC&         TPFILE, TURBN) 

IF (LHOOK) CALL DR_HOOK ('TURB_VER_DYN_FLUX_MANYBLOCKS', 0, ZHOOK_HANDLE)
IKT=D%NKT
IKTB=D%NKTB
IKTE=D%NKTE
IKB=D%NKB
IKE=D%NKE
IKA=D%NKA
IKU=D%NKU
IKL=D%NKL
IIJE=D%NIJE
IIJB=D%NIJB
GOCEAN=OOCEAN

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    ZA (JI,:, JBLK)=XUNDEF
    PDP (JI,:, JBLK)=XUNDEF
    ZSOURCE (JI,:, JBLK)=0.
    ZFLXZ (JI,:, JBLK)=0.
  ENDDO

ENDDO




ZCMFS=CSTURB%XCMFS


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    ZDIRSINZW (JI, JBLK)=SQRT (1.-PDIRCOSZW (JI, JBLK)**2)

    

    DO JK=1, IKT
      
      ZWORK1 (JI, JK, JBLK)=PLM (JI, JK, JBLK)*SQRT (PTKEM (JI, JK, JBLK))
    
    ENDDO

  ENDDO

ENDDO



CALL MZM_PHY_MANYBLOCKS (D, ZWORK1, ZKEFF, LDACC = LDACC, KGPBLKS = KGPBLKS)


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    ZUSLOPEM (JI, JBLK)=PUSLOPEM (JI, JBLK)
    ZVSLOPEM (JI, JBLK)=PVSLOPEM (JI, JBLK)
    ZFLUXSFCU (JI, JBLK)=PSFUM (JI, JBLK)
    ZFLUXSFCV (JI, JBLK)=PSFVM (JI, JBLK)
  ENDDO

ENDDO




CALL MXM_PHY_MANYBLOCKS (D, ZKEFF, ZMXM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MZM_PHY_MANYBLOCKS (D, PRHODJ, ZMZM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MXM_PHY_MANYBLOCKS (D, ZMZM2D_WORK1, ZMXM2D_WORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MXM_PHY_MANYBLOCKS (D, PDZZ, ZMXM2D_WORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZA (JI, JK, JBLK)=-PTSTEP*ZCMFS*ZMXM2D_WORK1 (JI, JK, JBLK)*ZMXM2D_WORK2&
      & (JI, JK, JBLK)/ZMXM2D_WORK3 (JI, JK, JBLK)**2
    
    ENDDO

    
    ZCOEFFLXU (JI, JBLK)=PCDUEFF (JI, JBLK)*(PDIRCOSZW (JI, JBLK&
    &)**2-ZDIRSINZW (JI, JBLK)**2)*PCOSSLOPE (JI, JBLK)
    ZCOEFFLXV (JI, JBLK)=PCDUEFF (JI, JBLK)*PDIRCOSZW (JI, JBLK)*PSINSLOPE (JI, JBLK)
    ZCOEFS (JI, JBLK)=ZCOEFFLXU (JI, JBLK)*PCOSSLOPE (JI, JBLK)*PDIRCOSZW&
    & (JI, JBLK)+ZCOEFFLXV (JI, JBLK)*PSINSLOPE (JI, JBLK)
    
    
    ZSHUGRADWK1_1D (JI, JBLK)=ZCOEFS (JI, JBLK)/PDZZ (JI, IKB, JBLK)
  
  ENDDO

ENDDO



CALL MXM2D_PHY_MANYBLOCKS (D, ZSHUGRADWK1_1D, ZMXM1D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    ZCOEFS (JI, JBLK)=ZMXM1D_WORK1 (JI, JBLK)

    

    DO JK=IKTB+1, IKTE-1
      
      ZSOURCE (JI, JK, JBLK)=0.
    
    ENDDO

    
    ZSOURCE (JI, IKB, JBLK)=PTAU11M (JI, JBLK)*PCOSSLOPE (JI, JBLK)*PDIRCOSZW (JI, JBLK)&
    &*ZDIRSINZW (JI, JBLK)-PTAU12M (JI, JBLK)*PSINSLOPE (JI, JBLK)*ZDIRSINZW (JI, JBLK)-PTAU33M&
    & (JI, JBLK)*PCOSSLOPE (JI, JBLK)*ZDIRSINZW (JI, JBLK)*PDIRCOSZW (JI, JBLK)
    
    
    ZSHUGRADWK1_1D (JI, JBLK)=ZSOURCE (JI, IKB, JBLK)/PDZZ (JI, IKB, JBLK)
  
  ENDDO

ENDDO





CALL MXM2D_PHY_MANYBLOCKS (D, ZSHUGRADWK1_1D, ZMXM1D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    ZSHUGRADWK1_1D (JI, JBLK)=ZCOEFFLXU (JI, JBLK)/PDZZ (JI, IKB, JBLK)*ZUSLOPEM&
    & (JI, JBLK)-ZCOEFFLXV (JI, JBLK)/PDZZ (JI, IKB, JBLK)*ZVSLOPEM (JI, JBLK)
  
  ENDDO

ENDDO

CALL MXM2D_PHY_MANYBLOCKS (D, ZSHUGRADWK1_1D, ZMXM1D_WORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT)
DO JBLK = 1, KGPBLKS
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 
  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    ZPRHODJ(JI, JBLK) =  PRHODJ(JI, IKA, JBLK)  
  ENDDO
ENDDO
CALL MXM2D_PHY_MANYBLOCKS (D, ZPRHODJ, ZMXM1D_WORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)
!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT)
DO JBLK = 1, KGPBLKS
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 
  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    ZPRHODJ(JI, JBLK) =  PRHODJ(JI, IKB, JBLK)  
  ENDDO
ENDDO
CALL MXM2D_PHY_MANYBLOCKS (D,ZPRHODJ, ZMXM1D_WORK4, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    ZSOURCE (JI, IKB, JBLK)=(ZMXM1D_WORK1 (JI, JBLK)+ZMXM1D_WORK2 (JI, JBLK)-ZCOEFS (JI, JBLK)*PUM&
    & (JI, IKB, JBLK)*TURBN%XIMPL)*0.5*(1.+ZMXM1D_WORK3 (JI, JBLK)/ZMXM1D_WORK4 (JI, JBLK))
    
    
    ZSOURCE (JI, IKE, JBLK)=0.
  
  ENDDO

ENDDO



CALL MXM_PHY_MANYBLOCKS (D, PRHODJ, ZMXM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL TRIDIAG_WIND_MANYBLOCKS (D, PUM (:,:,:), ZA (:,:,:), ZCOEFS (:,:), PTSTEP, PEXPL, TURBN%XIMPL&
&, ZMXM2D_WORK1 (:,:,:), ZSOURCE (:,:,:), ZRES (:,:,:), LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MXM_PHY_MANYBLOCKS (D, PRHODJ, ZMXM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      PRUS (JI, JK, JBLK)=PRUS (JI, JK, JBLK)+ZMXM2D_WORK1 (JI, JK&
      &, JBLK)*(ZRES (JI, JK, JBLK)-PUM (JI, JK, JBLK))/PTSTEP
    
    ENDDO


    DO JK=1, IKT
      
      ZSHUGRADWK1_2D (JI, JK, JBLK)=TURBN%XIMPL*ZRES (JI, JK, JBLK)+PEXPL*PUM (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO


CALL DZM_PHY_MANYBLOCKS (D, ZSHUGRADWK1_2D, ZDZM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MXM_PHY_MANYBLOCKS (D, ZKEFF, ZMXM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MXM_PHY_MANYBLOCKS (D, PDZZ, ZMXM2D_WORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZFLXZ (JI, JK, JBLK)=-ZCMFS*ZMXM2D_WORK1 (JI, JK, JBLK)*ZDZM2D_WORK1&
      & (JI, JK, JBLK)/ZMXM2D_WORK2 (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT)
DO JBLK = 1, KGPBLKS
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 
  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    ZPDZZ(JI, JBLK) =  PDZZ(JI, IKB, JBLK)
  ENDDO
ENDDO
CALL MXM2D_PHY_MANYBLOCKS (D, ZPDZZ, ZMXM1D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT)
DO JBLK = 1, KGPBLKS
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 
  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    ZPRHODJ(JI, JBLK) =  PRHODJ(JI, IKA, JBLK)  
  ENDDO
ENDDO
CALL MXM2D_PHY_MANYBLOCKS (D, ZPRHODJ, ZMXM1D_WORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT)
DO JBLK = 1, KGPBLKS
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 
  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    ZPRHODJ(JI, JBLK) =  PRHODJ(JI, IKB, JBLK)  
  ENDDO
ENDDO
CALL MXM2D_PHY_MANYBLOCKS (D, ZPRHODJ, ZMXM1D_WORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    ZFLXZ (JI, IKB, JBLK)=ZMXM1D_WORK1 (JI, JBLK)*(ZSOURCE (JI, IKB, JBLK)+ZCOEFS (JI, JBLK)*ZRES&
    & (JI, IKB, JBLK)*TURBN%XIMPL)/0.5/(1.+ZMXM1D_WORK2 (JI, JBLK)/ZMXM1D_WORK3 (JI, JBLK))
    
    
    ZFLXZ (JI, IKA, JBLK)=ZFLXZ (JI, IKB, JBLK)
    
    PWU (JI, 1:IKT, JBLK)=ZFLXZ (JI, 1:IKT, JBLK)
  ENDDO

ENDDO





CALL GZ_U_UW_PHY_MANYBLOCKS (D, PUM, PDZZ, ZGZ_U_UW2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZSHUGRADWK2_2D (JI, JK, JBLK)=ZFLXZ (JI, JK, JBLK)*ZGZ_U_UW2D_WORK1 (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO

CALL MXF_PHY_MANYBLOCKS (D, ZSHUGRADWK2_2D, ZMXF2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZSHUGRADWK1_2D (JI, JK, JBLK)=ZMXF2D_WORK1 (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO

CALL MZF_PHY_MANYBLOCKS (D, ZSHUGRADWK1_2D, ZMZF2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      PDP (JI, JK, JBLK)=-ZMZF2D_WORK1 (JI, JK, JBLK)
    
    ENDDO

    
    ZSHUGRADWK2_1D (JI, JBLK)=PDZZ (JI, IKB+IKL, JBLK)
  
  ENDDO

ENDDO



CALL MXM2D_PHY_MANYBLOCKS (D, ZSHUGRADWK2_1D, ZMXM1D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    ZSHUGRADWK1_1D (JI, JBLK)=ZFLXZ (JI, IKB+IKL, JBLK)*(PUM (JI, IKB&
    &+IKL, JBLK)-PUM (JI, IKB, JBLK))/ZMXM1D_WORK1 (JI, JBLK)
  
  ENDDO

ENDDO

CALL MXF2D_PHY_MANYBLOCKS (D, ZSHUGRADWK1_1D, ZMXF1D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    PDP (JI, IKB, JBLK)=-ZMXF1D_WORK1 (JI, JBLK)
  
  ENDDO

ENDDO


CALL MYM_PHY_MANYBLOCKS (D, ZKEFF, ZMYM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MZM_PHY_MANYBLOCKS (D, PRHODJ, ZMZM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MYM_PHY_MANYBLOCKS (D, ZMZM2D_WORK1, ZMYM2D_WORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MYM_PHY_MANYBLOCKS (D, PDZZ, ZMYM2D_WORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZA (JI, JK, JBLK)=-PTSTEP*ZCMFS*ZMYM2D_WORK1 (JI, JK, JBLK)*ZMYM2D_WORK2&
      & (JI, JK, JBLK)/ZMYM2D_WORK3 (JI, JK, JBLK)**2
    
    ENDDO

    
    ZCOEFFLXU (JI, JBLK)=PCDUEFF (JI, JBLK)*(PDIRCOSZW (JI, JBLK&
    &)**2-ZDIRSINZW (JI, JBLK)**2)*PSINSLOPE (JI, JBLK)
    ZCOEFFLXV (JI, JBLK)=PCDUEFF (JI, JBLK)*PDIRCOSZW (JI, JBLK)*PCOSSLOPE (JI, JBLK)
    ZCOEFS (JI, JBLK)=ZCOEFFLXU (JI, JBLK)*PSINSLOPE (JI, JBLK)*PDIRCOSZW&
    & (JI, JBLK)+ZCOEFFLXV (JI, JBLK)*PCOSSLOPE (JI, JBLK)
    
    
    ZSHUGRADWK1_1D (JI, JBLK)=ZCOEFS (JI, JBLK)/PDZZ (JI, IKB, JBLK)
  
  ENDDO

ENDDO



CALL MYM2D_PHY_MANYBLOCKS (D, ZSHUGRADWK1_1D, ZMYM1D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    ZCOEFS (JI, JBLK)=ZMYM1D_WORK1 (JI, JBLK)

    

    DO JK=IKB+1, IKE-1
      
      ZSOURCE (JI, JK, JBLK)=0.
    
    ENDDO

    
    ZSOURCE (JI, IKB, JBLK)=PTAU11M (JI, JBLK)*PSINSLOPE (JI, JBLK)*PDIRCOSZW (JI, JBLK)&
    &*ZDIRSINZW (JI, JBLK)+PTAU12M (JI, JBLK)*PCOSSLOPE (JI, JBLK)*ZDIRSINZW (JI, JBLK)-PTAU33M&
    & (JI, JBLK)*PSINSLOPE (JI, JBLK)*ZDIRSINZW (JI, JBLK)*PDIRCOSZW (JI, JBLK)
    
    
    ZSHUGRADWK1_1D (JI, JBLK)=ZSOURCE (JI, IKB, JBLK)/PDZZ (JI, IKB, JBLK)
  
  ENDDO

ENDDO





CALL MYM2D_PHY_MANYBLOCKS (D, ZSHUGRADWK1_1D, ZMYM1D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    ZSHUGRADWK1_1D (JI, JBLK)=ZCOEFFLXU (JI, JBLK)/PDZZ (JI, IKB, JBLK)*ZUSLOPEM&
    & (JI, JBLK)+ZCOEFFLXV (JI, JBLK)/PDZZ (JI, IKB, JBLK)*ZVSLOPEM (JI, JBLK)
  
  ENDDO

ENDDO

CALL MYM2D_PHY_MANYBLOCKS (D, ZSHUGRADWK1_1D, ZMYM1D_WORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT)
DO JBLK = 1, KGPBLKS
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 
  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    ZPRHODJ(JI, JBLK) =  PRHODJ(JI, IKA, JBLK)  
  ENDDO
ENDDO
CALL MYM2D_PHY_MANYBLOCKS (D, ZPRHODJ, ZMYM1D_WORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)
!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT)
DO JBLK = 1, KGPBLKS
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 
  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    ZPRHODJ(JI, JBLK) =  PRHODJ(JI, IKB, JBLK)  
  ENDDO
ENDDO
CALL MYM2D_PHY_MANYBLOCKS (D, ZPRHODJ, ZMYM1D_WORK4, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    ZSOURCE (JI, IKB, JBLK)=(ZMYM1D_WORK1 (JI, JBLK)+ZMYM1D_WORK2 (JI, JBLK)-ZCOEFS (JI, JBLK)*PVM&
    & (JI, IKB, JBLK)*TURBN%XIMPL)*0.5*(1.+ZMYM1D_WORK3 (JI, JBLK)/ZMYM1D_WORK4 (JI, JBLK))
    
    
    ZSOURCE (JI, IKE, JBLK)=0.
  
  ENDDO

ENDDO



CALL MYM_PHY_MANYBLOCKS (D, PRHODJ, ZMYM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL TRIDIAG_WIND_MANYBLOCKS (D, PVM (:,:,:), ZA (:,:,:), ZCOEFS (:,:), PTSTEP, PEXPL, TURBN%XIMPL&
&, ZMYM2D_WORK1 (:,:,:), ZSOURCE (:,:,:), ZRES (:,:,:), LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MYM_PHY_MANYBLOCKS (D, PRHODJ, ZMYM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      PRVS (JI, JK, JBLK)=PRVS (JI, JK, JBLK)+ZMYM2D_WORK1 (JI, JK&
      &, JBLK)*(ZRES (JI, JK, JBLK)-PVM (JI, JK, JBLK))/PTSTEP
    
    ENDDO

  ENDDO

ENDDO

CALL MYM_PHY_MANYBLOCKS (D, ZKEFF, ZMYM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZSHUGRADWK1_2D (JI, JK, JBLK)=TURBN%XIMPL*ZRES (JI, JK, JBLK)+PEXPL*PVM (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO

CALL DZM_PHY_MANYBLOCKS (D, ZSHUGRADWK1_2D, ZDZM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MYM_PHY_MANYBLOCKS (D, PDZZ, ZMYM2D_WORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZFLXZ (JI, JK, JBLK)=-ZCMFS*ZMYM2D_WORK1 (JI, JK, JBLK)*ZDZM2D_WORK1&
      & (JI, JK, JBLK)/ZMYM2D_WORK2 (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT)
DO JBLK = 1, KGPBLKS
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 
  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    ZPDZZ(JI, JBLK) =  PDZZ(JI, IKB, JBLK)  
  ENDDO
ENDDO
CALL MYM2D_PHY_MANYBLOCKS (D, ZPDZZ, ZMYM1D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT)
DO JBLK = 1, KGPBLKS
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 
  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    ZPRHODJ(JI, JBLK) =  PRHODJ(JI, IKA, JBLK)  
  ENDDO
ENDDO
CALL MYM2D_PHY_MANYBLOCKS (D, ZPRHODJ, ZMYM1D_WORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT)
DO JBLK = 1, KGPBLKS
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 
  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    ZPRHODJ(JI, JBLK) =  PRHODJ(JI, IKB, JBLK)  
  ENDDO
ENDDO
CALL MYM2D_PHY_MANYBLOCKS (D, ZPRHODJ, ZMYM1D_WORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    ZFLXZ (JI, IKB, JBLK)=ZMYM1D_WORK1 (JI, JBLK)*(ZSOURCE (JI, IKB, JBLK)+ZCOEFS (JI, JBLK)*ZRES&
    & (JI, IKB, JBLK)*TURBN%XIMPL)/0.5/(1.+ZMYM1D_WORK2 (JI, JBLK)/ZMYM1D_WORK3 (JI, JBLK))
    
    
    ZFLXZ (JI, IKA, JBLK)=ZFLXZ (JI, IKB, JBLK)

    

    DO JK=1, IKT
      
      PWV (JI, JK, JBLK)=ZFLXZ (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO





CALL GZ_V_VW_PHY_MANYBLOCKS (D, PVM, PDZZ, ZGZ_V_VW2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZSHUGRADWK2_2D (JI, JK, JBLK)=ZFLXZ (JI, JK, JBLK)*ZGZ_V_VW2D_WORK1 (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO

CALL MYF_PHY_MANYBLOCKS (D, ZSHUGRADWK2_2D, ZMYF2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZSHUGRADWK1_2D (JI, JK, JBLK)=ZMYF2D_WORK1 (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO

CALL MZF_PHY_MANYBLOCKS (D, ZSHUGRADWK1_2D, ZMZF2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZA (JI, JK, JBLK)=-ZMZF2D_WORK1 (JI, JK, JBLK)
    
    ENDDO

    
    ZSHUGRADWK2_1D (JI, JBLK)=PDZZ (JI, IKB+IKL, JBLK)
  
  ENDDO

ENDDO



CALL MYM2D_PHY_MANYBLOCKS (D, ZSHUGRADWK2_1D, ZMYM1D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    ZSHUGRADWK1_1D (JI, JBLK)=ZFLXZ (JI, IKB+IKL, JBLK)*(PVM (JI, IKB&
    &+IKL, JBLK)-PVM (JI, IKB, JBLK))/ZMYM1D_WORK1 (JI, JBLK)
  
  ENDDO

ENDDO

CALL MYF2D_PHY_MANYBLOCKS (D, ZSHUGRADWK1_1D, ZMYF1D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    ZA (JI, IKB, JBLK)=-ZMYF1D_WORK1 (JI, JBLK)

    

    DO JK=1, IKT
      
      PDP (JI, JK, JBLK)=PDP (JI, JK, JBLK)+ZA (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO




IF (LHOOK) CALL DR_HOOK ('TURB_VER_DYN_FLUX_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE TURB_VER_DYN_FLUX_MANYBLOCKS

ENDMODULE MODE_TURB_VER_DYN_FLUX_MANYBLOCKS
