
MODULE MODE_TKE_EPS_SOURCES_MANYBLOCKS


IMPLICIT NONE



CONTAINS
SUBROUTINE TKE_EPS_SOURCES_MANYBLOCKS (D, CST, CSTURB, TURBN, TLES, PTKEM, PLM, PLEPS&
&, PDP, PTRH, PRHODJ, PDZZ, PDXX, PDYY, PDZX, PDZY, PZZ, PTSTEP, PEXPL, TPFILE, ODIAG_IN_RUN&
&, OOCEAN, PSFUM, PSFVM, PTP, PRTKES, PRTHLS, PCOEF_DISS, PTDIFF, PTDISS, PRTKEMS,&
& KBUDGETS, PEDR, PTR, PDISS, PCURRENT_TKE_DISS, LDACC, KGPBLKS)
USE MODE_SHUMAN_PHY,ONLY:MZM_PHY, DZM_PHY, DZF_PHY
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MZM_PHY_MANYBLOCKS
USE MODE_TRIDIAG_TKE,ONLY:TRIDIAG_TKE
USE MODE_TRIDIAG_TKE_MANYBLOCKS, ONLY : TRIDIAG_TKE_MANYBLOCKS
USE MODE_IO_FIELD_WRITE_PHY,ONLY:IO_FIELD_WRITE_PHY
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_ARGSLIST_LL,ONLY:LIST_LL
USE MODD_BUDGET,ONLY:TBUDGETCONF_T, NBUDGET_TKE, TBUDGETDATA_PTR
USE MODD_CST,ONLY:CST_T
USE MODD_CTURB,ONLY:CSTURB_T
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_FIELD,ONLY:TFIELDMETADATA, TYPEREAL
USE MODD_IO,ONLY:TFILEDATA
USE MODD_LES,ONLY:TLES_T
USE MODD_TURB_N,ONLY:TURB_T
USE MODI_GET_HALO
USE MODI_LES_MEAN_SUBGRID_PHY
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

#ifdef MNH_COMPILER_CCE
#endif
TYPE (DIMPHYEX_T), INTENT (IN)::D
TYPE (CST_T), INTENT (IN)::CST
TYPE (CSTURB_T), INTENT (IN)::CSTURB
TYPE (TURB_T), INTENT (IN)::TURBN
TYPE (TLES_T), INTENT (INOUT)::TLES
REAL, INTENT (IN)::PTKEM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PLM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PLEPS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PDP(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PTRH(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PRHODJ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDZY(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDZX(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDZZ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDYY(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDXX(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PZZ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PTSTEP
REAL, INTENT (IN)::PEXPL
TYPE (TFILEDATA), INTENT (INOUT)::TPFILE
LOGICAL, INTENT (IN)::ODIAG_IN_RUN
LOGICAL, INTENT (IN)::OOCEAN
REAL, INTENT (IN)::PSFVM(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFUM(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PTP(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRTKES(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRTHLS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PCOEF_DISS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT)::PTDIFF(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT)::PTDISS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PRTKEMS(:, :, :) ! (D%NIJT, D%NKT)
INTEGER, INTENT (IN)::KBUDGETS
REAL, INTENT (OUT), OPTIONAL, TARGET::PEDR(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT), OPTIONAL, TARGET::PTR(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT), OPTIONAL, TARGET::PDISS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT), OPTIONAL, TARGET::PCURRENT_TKE_DISS(MERGE&
& (D%NIJT, 0, .FALSE.), MERGE (D%NKT, 0, .FALSE.))
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL::ZW(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDWORK2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDWORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMWORK2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMWORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZTR(D%NIJT, D%NKT,KGPBLKS)
REAL::ZKEFF(D%NIJT, D%NKT,KGPBLKS)
REAL::ZSOURCE(D%NIJT, D%NKT,KGPBLKS)
REAL::ZFLX(D%NIJT, D%NKT,KGPBLKS)
REAL::ZRES(D%NIJT, D%NKT,KGPBLKS)
REAL::ZA(D%NIJT, D%NKT,KGPBLKS)
LOGICAL::GTKENEG(D%NIJT, D%NKT,KGPBLKS)
INTEGER::IKL
INTEGER::IKA
INTEGER::IKT
INTEGER::IKE
INTEGER::IKB
INTEGER::IIJE
INTEGER::IIJB
TYPE (LIST_LL), POINTER::TZFIELDDISS_LL
INTEGER::IINFO_LL
TYPE (TFIELDMETADATA)::TZFIELD
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
REAL::ZMZM2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMZM2D_WORK2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZSHUGRADWK1_2D(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDZM2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDZF2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
INTEGER::JK
INTEGER::JI
REAL, POINTER :: PCURRENT_TKE_DISS_PTR
REAL, POINTER :: PDISS_PTR
REAL, POINTER :: PEDR_PTR
REAL, POINTER :: PTR_PTR
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK
NULLIFY (TZFIELDDISS_LL)

!$ACC DATA &
!$ACC&CREATE (GTKENEG, ZA, ZDWORK1, ZDWORK2, ZDZF2D_WORK1, ZDZM2D_WORK1, ZFLX, &
!$ACC&        ZKEFF, ZMWORK1, ZMWORK2, ZMZM2D_WORK1, ZMZM2D_WORK2, ZRES, ZSHUGRADWK1_2D, &
!$ACC&        ZSOURCE, ZTR, ZW) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (CST, CSTURB, D, PCOEF_DISS, PCURRENT_TKE_DISS, PDISS, PDP, PDXX, PDYY, &
!$ACC&         PDZX, PDZY, PDZZ, PEDR, PLEPS, PLM, PRHODJ, PRTHLS, PRTKEMS, PRTKES, PSFUM, &
!$ACC&         PSFVM, PTDIFF, PTDISS, PTKEM, PTP, PTR, PTRH, PZZ, TLES, TPFILE, TURBN) 

IF (LHOOK) CALL DR_HOOK ('TKE_EPS_SOURCES_MANYBLOCKS', 0, ZHOOK_HANDLE)
IKB=D%NKB
IKE=D%NKE
IIJB=D%NIJB
IIJE=D%NIJE
IKT=D%NKT
IKA=D%NKA
IKL=D%NKL

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZKEFF (JI, JK, JBLK)=PLM (JI, JK, JBLK)*SQRT (PTKEM (JI, JK, JBLK))
    
    ENDDO

    ZTR (JI, 1:IKT, JBLK)=0.
  ENDDO

ENDDO





IF (OOCEAN) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      
      PDP (JI, IKE, JBLK)=PDP (JI, IKE, JBLK)*(1.+PDZZ (JI, IKE, JBLK)/PDZZ (JI, IKE+1, JBLK))
    
    ENDDO

  ENDDO

ELSE
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      
      PDP (JI, IKB, JBLK)=PDP (JI, IKB, JBLK)*(1.+PDZZ (JI, IKB+IKL, JBLK)/PDZZ (JI, IKB, JBLK))
    
    ENDDO

  ENDDO

ENDIF


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZFLX (JI, JK, JBLK)=TURBN%XCED*SQRT (PTKEM (JI, JK, JBLK))/PLEPS (JI, JK, JBLK)
      ZSOURCE (JI, JK, JBLK)=(PRTKES (JI, JK, JBLK)+PRTKEMS (JI, JK, JBLK))/PRHODJ&
      & (JI, JK, JBLK)-PTKEM (JI, JK, JBLK)/PTSTEP+PDP (JI, JK, JBLK)+PTP (JI, JK,&
      & JBLK)+ZTR (JI, JK, JBLK)-PEXPL*ZFLX (JI, JK, JBLK)*PTKEM (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO


IF (OOCEAN) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      
      ZSOURCE (JI, IKE, JBLK)=ZSOURCE (JI, IKE, JBLK)-1.E2*((PSFUM (JI&
      &, JBLK)**2+PSFVM (JI, JBLK)**2)**1.5)/PDZZ (JI, IKE, JBLK)
    
    ENDDO

  ENDDO

ENDIF

CALL MZM_PHY_MANYBLOCKS (D, ZKEFF, ZMZM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
CALL MZM_PHY_MANYBLOCKS (D, PRHODJ, ZMZM2D_WORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZA (JI, JK, JBLK)=-PTSTEP*CSTURB%XCET*ZMZM2D_WORK1 (JI, JK, JBLK&
      &)*ZMZM2D_WORK2 (JI, JK, JBLK)/PDZZ (JI, JK, JBLK)**2
    
    ENDDO


    DO JK=1, IKT
      
      ZW (JI, JK, JBLK)=PTSTEP*ZFLX (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO


CALL TRIDIAG_TKE_MANYBLOCKS (D, PTKEM, ZA, PTSTEP, PEXPL, TURBN%XIMPL&
&, PRHODJ, ZSOURCE, ZW, ZRES, LDACC = LDACC, KGPBLKS = KGPBLKS)


IF (TURBN%LTKEMINTURB) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        GTKENEG (JI, JK, JBLK)=ZRES (JI, JK, JBLK)<=TURBN%XTKEMIN

        IF (GTKENEG (JI, JK, JBLK)) THEN
          ZRES (JI, JK, JBLK)=TURBN%XTKEMIN
        ENDIF

      
      ENDDO

    ENDDO

  ENDDO

ENDIF


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      PTDISS (JI, JK, JBLK)=-ZFLX (JI, JK, JBLK)*(PEXPL*PTKEM&
      & (JI, JK, JBLK)+TURBN%XIMPL*ZRES (JI, JK, JBLK))
    
    ENDDO


    DO JK=1, IKT
      
      PRTKES (JI, JK, JBLK)=PRTKES (JI, JK, JBLK)+PRHODJ (JI, JK, JBLK)*(PDP (JI, JK&
      &, JBLK)+PTP (JI, JK, JBLK)-TURBN%XCED*SQRT (PTKEM (JI, JK, JBLK))/PLEPS (JI,&
      & JK, JBLK)*(PEXPL*PTKEM (JI, JK, JBLK)+TURBN%XIMPL*ZRES (JI, JK, JBLK)))
      PTDIFF (JI, JK, JBLK)=ZRES (JI, JK, JBLK)/PTSTEP-PRTKES (JI, JK, JBLK)/PRHODJ &
      &(JI, JK, JBLK)-PDP (JI, JK, JBLK)-PTP (JI, JK, JBLK)-PTDISS (JI, JK, JBLK)
    
    ENDDO


    DO JK=1, IKT
      
      PRTKES (JI, JK, JBLK)=ZRES (JI, JK, JBLK)*PRHODJ (JI, JK, JBLK)/PTSTEP-PRTKEMS (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO





!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      PRTHLS (JI, JK, JBLK)=PRTHLS (JI, JK, JBLK)+TURBN%XCED*SQRT (PTKEM (JI, JK&
      &, JBLK))/PLEPS (JI, JK, JBLK)*(PEXPL*PTKEM (JI, JK, JBLK)+TURBN%XIMPL*ZRES&
      & (JI, JK, JBLK))*PRHODJ (JI, JK, JBLK)*PCOEF_DISS (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO


IF (PRESENT (PTR)) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        PTR (JI, JK, JBLK)=ZTR (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDIF


IF (PRESENT (PDISS)) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        PDISS (JI, JK, JBLK)=-TURBN%XCED*(PTKEM (JI, JK, JBLK)**1.5)/PLEPS (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDIF


IF (PRESENT (PEDR)) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        PEDR (JI, JK, JBLK)=TURBN%XCED*(PTKEM (JI, JK, JBLK)**1.5)/PLEPS (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDIF


IF (LHOOK) CALL DR_HOOK ('TKE_EPS_SOURCES_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE TKE_EPS_SOURCES_MANYBLOCKS

ENDMODULE MODE_TKE_EPS_SOURCES_MANYBLOCKS
