
MODULE MODE_TURB_VER_THERMO_CORR_MANYBLOCKS


IMPLICIT NONE



CONTAINS
SUBROUTINE TURB_VER_THERMO_CORR_MANYBLOCKS (D, CST, CSTURB, TURBN, NEBN, TLES, KRR, KRRL&
&, KRRI, KSV, OCOMPUTE_SRC, OCOUPLES, PEXPL, TPFILE, PDXX, PDYY, PDZZ, PDZX, PDZY, PDIRCOSZW&
&, PRHODJ, PTHVREF, PSFTHM, PSFRM, PSFTHP, PSFRP, PWM, PTHLM, PRM, PSVM, PTKEM, PLM, PLEPS&
&, PLOCPEXNM, PATHETA, PAMOIST, PBETA, PSQRT_TKE, PDTH_DZ, PDR_DZ, PRED2TH3, PRED2R3,&
& PRED2THR3, PBLL_O_E, PETHETA, PEMOIST, PREDTH1, PREDR1, PPHI3, PPSI3, PD, PFWTH, PFWR&
&, PFTH2, PFR2, PFTHR, PTHLP, PRP, MFMOIST, PSIGS, LDACC, KGPBLKS)
USE MODE_SHUMAN_PHY,ONLY:MZF_PHY, MZM_PHY, DZM_PHY
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MZM_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MZF_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : DZM_PHY_MANYBLOCKS
USE MODE_PRANDTL,ONLY:M3_TH2_WTH2, D_M3_TH2_WTH2_O_DDTDZ, M3_TH2_W2TH, D_M3_TH2_W2TH_O_DDTDZ, M3_TH2_WR2&
&, D_M3_TH2_WR2_O_DDTDZ, M3_TH2_W2R, D_M3_TH2_W2R_O_DDTDZ, M3_TH2_WTHR, D_M3_TH2_WTHR_O_DDTDZ, M3_THR_WTH2&
&, D_M3_THR_WTH2_O_DDTDZ, D_M3_THR_WTH2_O_DDRDZ, M3_THR_W2TH, D_M3_THR_W2TH_O_DDTDZ, D_M3_THR_W2TH_O_DDRDZ&
&, M3_THR_WR2, D_M3_THR_WR2_O_DDTDZ, D_M3_THR_WR2_O_DDRDZ, M3_THR_W2R, D_M3_THR_W2R_O_DDTDZ, D_M3_THR_W2R_O_DDRDZ&
&, M3_THR_WTHR, D_M3_THR_WTHR_O_DDTDZ, D_M3_THR_WTHR_O_DDRDZ, D_PHI3DTDZ_O_DDTDZ, D_PSI3DTDZ_O_DDTDZ&
&, D_PHI3DRDZ_O_DDRDZ, D_PSI3DRDZ_O_DDRDZ, M3_R2_WR2, D_M3_R2_WR2_O_DDRDZ, M3_R2_W2R, D_M3_R2_W2R_O_DDRDZ&
&, M3_R2_WTH2, D_M3_R2_WTH2_O_DDRDZ, M3_R2_W2TH, D_M3_R2_W2TH_O_DDRDZ, M3_R2_WTHR, D_M3_R2_WTHR_O_DDRDZ&
&, D_PSI3DRDZ2_O_DDRDZ
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_THR_WTHR_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_THR_WTH2_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_THR_WR2_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_THR_W2TH_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_THR_W2R_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_TH2_WTHR_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_TH2_WTH2_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_TH2_WR2_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_TH2_W2TH_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_TH2_W2R_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_R2_WTHR_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_R2_WTH2_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_R2_WR2_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_R2_W2TH_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : M3_R2_W2R_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_PSI3DTDZ_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_PSI3DRDZ_O_DDRDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_PSI3DRDZ2_O_DDRDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_PHI3DTDZ_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_PHI3DRDZ_O_DDRDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_THR_WTHR_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_THR_WTHR_O_DDRDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_THR_WTH2_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_THR_WTH2_O_DDRDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_THR_WR2_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_THR_WR2_O_DDRDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_THR_W2TH_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_THR_W2TH_O_DDRDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_THR_W2R_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_THR_W2R_O_DDRDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_TH2_WTHR_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_TH2_WTH2_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_TH2_WR2_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_TH2_W2TH_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_TH2_W2R_O_DDTDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_R2_WTHR_O_DDRDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_R2_WTH2_O_DDRDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_R2_WR2_O_DDRDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_R2_W2TH_O_DDRDZ_MANYBLOCKS
USE MODE_PRANDTL_MANYBLOCKS, ONLY : D_M3_R2_W2R_O_DDRDZ_MANYBLOCKS
USE MODE_IO_FIELD_WRITE_PHY,ONLY:IO_FIELD_WRITE_PHY
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_CST,ONLY:CST_T
USE MODD_CTURB,ONLY:CSTURB_T
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_FIELD,ONLY:TFIELDMETADATA, TYPEREAL
USE MODD_IO,ONLY:TFILEDATA
USE MODD_LES,ONLY:TLES_T
USE MODD_PARAMETERS,ONLY:JPVEXT_TURB
USE MODD_TURB_N,ONLY:TURB_T
USE MODD_NEB_N,ONLY:NEB_T
USE MODI_LES_MEAN_SUBGRID_PHY
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE

#ifdef MNH_COMPILER_CCE
#endif
TYPE (DIMPHYEX_T), INTENT (IN)::D
TYPE (CST_T), INTENT (IN)::CST
TYPE (CSTURB_T), INTENT (IN)::CSTURB
TYPE (TURB_T), INTENT (IN)::TURBN
TYPE (NEB_T), INTENT (IN)::NEBN
TYPE (TLES_T), INTENT (INOUT)::TLES
INTEGER, INTENT (IN)::KRR
INTEGER, INTENT (IN)::KSV
INTEGER, INTENT (IN)::KRRL
INTEGER, INTENT (IN)::KRRI
LOGICAL, INTENT (IN)::OCOUPLES
LOGICAL, INTENT (IN)::OCOMPUTE_SRC
REAL, INTENT (IN)::PEXPL
TYPE (TFILEDATA), INTENT (INOUT)::TPFILE
REAL, INTENT (IN)::PDZY(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDZX(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDYY(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDXX(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDZZ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDIRCOSZW(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PRHODJ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHVREF(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PSFRM(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFTHM(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFRP(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFTHP(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PWM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHLM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PRM(:, :, :, :) ! (D%NIJT, D%NKT, KRR)
REAL, INTENT (IN)::PSVM(:, :, :, :) ! (D%NIJT, D%NKT, KSV)
REAL, INTENT (IN)::PTKEM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PLM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PLEPS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PLOCPEXNM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PATHETA(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PAMOIST(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PBETA(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PSQRT_TKE(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDTH_DZ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDR_DZ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PRED2TH3(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PRED2R3(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PRED2THR3(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PBLL_O_E(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PETHETA(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PEMOIST(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PREDTH1(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PREDR1(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PPHI3(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PPSI3(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PD(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PFWTH(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PFWR(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PFTH2(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PFR2(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PFTHR(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHLP(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PRP(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::MFMOIST(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT)::PSIGS(:, :, :)
!REAL, INTENT (OUT)::PSIGS(D%NIJT, D%NKT, KGPBLKS)
!REAL, INTENT (OUT)::PSIGS(MERGE (D%NIJT, 0, OCOMPUTE_SRC), MERGE (D%NKT, 0, OCOMPUTE_SRC))
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL::ZWKPHIPSI4(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWKPHIPSI3(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWKPHIPSI2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWKPHIPSI1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK8(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK7(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK6(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK5(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK4(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK3(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::PLEPSF(D%NIJT, D%NKT,KGPBLKS)
REAL::PLMF(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDFDDRDZ(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDFDDTDZ(D%NIJT, D%NKT,KGPBLKS)
REAL::ZF(D%NIJT, D%NKT,KGPBLKS)
REAL::ZKEFF(D%NIJT, D%NKT,KGPBLKS)
REAL::ZFLXZ(D%NIJT, D%NKT,KGPBLKS)
INTEGER::IKA
INTEGER::IKT
INTEGER::IKE
INTEGER::IKB
INTEGER::IIJE
INTEGER::IIJB
INTEGER::IKU
INTEGER::IKL
INTEGER::JK
INTEGER::JI
REAL::ZCOEFF(D%NIJT, MIN (D%NKA+JPVEXT_TURB*D%NKL, D%NKA+JPVEXT_TURB*D%NKL+2*D%NKL&
&):MAX (D%NKA+JPVEXT_TURB*D%NKL, D%NKA+JPVEXT_TURB*D%NKL+2*D%NKL),KGPBLKS)
REAL::ZTIME2
REAL::ZTIME1
LOGICAL::GUSERV
LOGICAL::GFTH2
LOGICAL::GFWTH
LOGICAL::GFR2
LOGICAL::GFWR
LOGICAL::GFTHR
TYPE (TFIELDMETADATA)::TZFIELD
REAL::ZSHUGRADWK1_2D(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMZF2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZSHUGRADWK2_2D(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDZM2D_WORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDZM2D_WORK2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDZM2D_WORK3(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMZF2D_WORK2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDZM2D_WORK4(D%NIJT, D%NKT,KGPBLKS)
REAL::ZSHUGRADWK3_2D(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMZF2D_WORK3(D%NIJT, D%NKT,KGPBLKS)
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK

!$ACC DATA &
!$ACC&CREATE (PLEPSF, PLMF, ZCOEFF, ZDFDDRDZ, ZDFDDTDZ, ZDZM2D_WORK1, ZDZM2D_WORK2, &
!$ACC&        ZDZM2D_WORK3, ZDZM2D_WORK4, ZF, ZFLXZ, ZKEFF, ZMZF2D_WORK1, ZMZF2D_WORK2, &
!$ACC&        ZMZF2D_WORK3, ZSHUGRADWK1_2D, ZSHUGRADWK2_2D, ZSHUGRADWK3_2D, &
!$ACC&        ZWKPHIPSI1, ZWKPHIPSI2, ZWKPHIPSI3, ZWKPHIPSI4, ZWORK1, ZWORK2, &
!$ACC&        ZWORK3, ZWORK4, ZWORK5, ZWORK6, ZWORK7, ZWORK8) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (CST, CSTURB, D, MFMOIST, NEBN, PAMOIST, PATHETA, PBETA, PBLL_O_E, PD, PDIRCOSZW, &
!$ACC&         PDR_DZ, PDTH_DZ, PDXX, PDYY, PDZX, PDZY, PDZZ, PEMOIST, PETHETA, PFR2, &
!$ACC&         PFTH2, PFTHR, PFWR, PFWTH, PLEPS, PLM, PLOCPEXNM, PPHI3, PPSI3, PRED2R3, &
!$ACC&         PRED2TH3, PRED2THR3, PREDR1, PREDTH1, PRHODJ, PRM, PRP, PSFRM, PSFRP, &
!$ACC&         PSFTHM, PSFTHP, PSIGS, PSQRT_TKE, PSVM, PTHLM, PTHLP, PTHVREF, PTKEM, &
!$ACC&         PWM, TLES, TPFILE, TURBN) 

IF (LHOOK) CALL DR_HOOK ('TURB_VER_THERMO_CORR_MANYBLOCKS', 0, ZHOOK_HANDLE)
IKB=D%NKB
IKE=D%NKE
IKT=D%NKT
IKA=D%NKA
IKU=D%NKU
IKL=D%NKL
IIJE=D%NIJE
IIJB=D%NIJB
GUSERV=(KRR/=0)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    ZCOEFF (JI, IKB+2*IKL, JBLK)=-PDZZ (JI, IKB+IKL, JBLK)/((PDZZ (JI, IKB&
    &+2*IKL, JBLK)+PDZZ (JI, IKB+IKL, JBLK))*PDZZ (JI, IKB+2*IKL, JBLK))
    ZCOEFF (JI, IKB+IKL, JBLK)=(PDZZ (JI, IKB+2*IKL, JBLK)+PDZZ (JI, IKB+IKL&
    &, JBLK))/(PDZZ (JI, IKB+IKL, JBLK)*PDZZ (JI, IKB+2*IKL, JBLK))
    ZCOEFF (JI, IKB, JBLK)=-(PDZZ (JI, IKB+2*IKL, JBLK)+2.*PDZZ (JI, IKB+IKL, JBLK))/(&
    &(PDZZ (JI, IKB+2*IKL, JBLK)+PDZZ (JI, IKB+IKL, JBLK))*PDZZ (JI, IKB+IKL, JBLK))

    

    DO JK=1, IKT
      
      ZWORK1 (JI, JK, JBLK)=PLM (JI, JK, JBLK)*SQRT (PTKEM (JI, JK, JBLK))
    
    ENDDO

  ENDDO

ENDDO



CALL MZM_PHY_MANYBLOCKS (D, ZWORK1, ZKEFF, LDACC = LDACC, KGPBLKS = KGPBLKS)
GFR2=.FALSE.
GFTHR=.FALSE.
GFWTH=.FALSE.
GFWR=.FALSE.

IF (TURBN%CTOM/='NONE') THEN
  GFTH2=ANY (PFTH2 (:,:,:)/=0.)
  GFR2=ANY (PFR2 (:,:,:)/=0.).AND.GUSERV
  GFTHR=ANY (PFTHR (:,:,:)/=0.).AND.GUSERV
  GFWTH=ANY (PFWTH (:,:,:)/=0.)
  GFWR=ANY (PFWR (:,:,:)/=0.).AND.GUSERV
ENDIF



!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZWORK1 (JI, JK, JBLK)=PPHI3 (JI, JK, JBLK)*PDTH_DZ (JI, JK, JBLK)**2
    
    ENDDO

  ENDDO

ENDDO

CALL MZF_PHY_MANYBLOCKS (D, ZWORK1, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZF (JI, JK, JBLK)=TURBN%XCTV*PLM (JI, JK, JBLK)*PLEPS (JI, JK, JBLK)*ZWORK2 (JI, JK, JBLK)
    
    ENDDO

    ZDFDDTDZ (JI,:, JBLK)=0.
  ENDDO

ENDDO




IF (GFTH2) THEN
  CALL M3_TH2_WTH2_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1, PD&
  &, PLEPS, PSQRT_TKE, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL D_M3_TH2_WTH2_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1, PD, PLEPS&
  &, PSQRT_TKE, PBLL_O_E, PETHETA, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*PFTH2 (JI, JK, JBLK)
        ZDFDDTDZ (JI, JK, JBLK)=ZDFDDTDZ (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*PFTH2 (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDIF


IF (GFWTH) THEN
  CALL M3_TH2_W2TH_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1, PD, PDTH_DZ&
  &, PLM, PLEPS, PTKEM, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL MZF_PHY_MANYBLOCKS (D, PFWTH, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL D_M3_TH2_W2TH_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1, PD&
  &, PLM, PLEPS, PTKEM, GUSERV, ZWORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*ZWORK2 (JI, JK, JBLK)
        ZDFDDTDZ (JI, JK, JBLK)=ZDFDDTDZ (JI, JK, JBLK)+ZWORK3 (JI, JK, JBLK)*ZWORK2 (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDIF


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZSHUGRADWK2_2D (JI, JK, JBLK)=PTHLP (JI, JK, JBLK)-PTHLM (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO

CALL DZM_PHY_MANYBLOCKS (D, ZSHUGRADWK2_2D, ZDZM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

IF (KRR/=0) THEN

  IF (GFR2) THEN
    CALL M3_TH2_WR2_MANYBLOCKS (D, CSTURB, TURBN, PD, PLEPS, PSQRT_TKE, PBLL_O_E&
    &, PEMOIST, PDTH_DZ, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_TH2_WR2_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1, PD, PLEPS, PSQRT_TKE&
    &, PBLL_O_E, PEMOIST, PDTH_DZ, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*PFR2 (JI, JK, JBLK)
          ZDFDDTDZ (JI, JK, JBLK)=ZDFDDTDZ (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*PFR2 (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF


  IF (GFWR) THEN
    CALL M3_TH2_W2R_MANYBLOCKS (D, CSTURB, TURBN, PD, PLM, PLEPS, PTKEM, PBLL_O_E&
    &, PEMOIST, PDTH_DZ, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL MZF_PHY_MANYBLOCKS (D, PFWR, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_TH2_W2R_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1, PD, PLM, PLEPS&
    &, PTKEM, PBLL_O_E, PEMOIST, PDTH_DZ, ZWORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*ZWORK2 (JI, JK, JBLK)
          ZDFDDTDZ (JI, JK, JBLK)=ZDFDDTDZ (JI, JK, JBLK)+ZWORK3 (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF


  IF (GFTHR) THEN
    CALL M3_TH2_WTHR_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PD, PLEPS, PSQRT_TKE&
    &, PBLL_O_E, PEMOIST, PDTH_DZ, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_TH2_WTHR_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1, PD, PLEPS,&
    & PSQRT_TKE, PBLL_O_E, PEMOIST, PDTH_DZ, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*PFTHR (JI, JK, JBLK)
          ZDFDDTDZ (JI, JK, JBLK)=ZDFDDTDZ (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*PFTHR (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF

ENDIF


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZSHUGRADWK1_2D (JI, JK, JBLK)=ZDZM2D_WORK1 (JI, JK, JBLK)/PDZZ (JI, JK, JBLK)
    
    ENDDO

  ENDDO

ENDDO

CALL MZF_PHY_MANYBLOCKS (D, ZSHUGRADWK1_2D, ZMZF2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZFLXZ (JI, JK, JBLK)=ZF (JI, JK, JBLK)+TURBN%XIMPL*ZDFDDTDZ&
      & (JI, JK, JBLK)*ZMZF2D_WORK1 (JI, JK, JBLK)
    
    ENDDO

    
    ZFLXZ (JI, IKB, JBLK)=TURBN%XCTV*PPHI3 (JI, IKB+IKL, JBLK)*PLM (JI, IKB, JBLK)*PLEPS (JI, IKB&
    &, JBLK)*(PEXPL*(ZCOEFF (JI, IKB+2*IKL, JBLK)*PTHLM (JI, IKB+2*IKL, JBLK)+ZCOEFF (JI, IKB+IKL&
    &, JBLK)*PTHLM (JI, IKB+IKL, JBLK)+ZCOEFF (JI, IKB, JBLK)*PTHLM (JI, IKB, JBLK))**2+TURBN%XIMPL&
    &*(ZCOEFF (JI, IKB+2*IKL, JBLK)*PTHLP (JI, IKB+2*IKL, JBLK)+ZCOEFF (JI, IKB+IKL, JBLK)*PTHLP&
    & (JI, IKB+IKL, JBLK)+ZCOEFF (JI, IKB, JBLK)*PTHLP (JI, IKB, JBLK))**2)
    
    
    ZFLXZ (JI, IKA, JBLK)=ZFLXZ (JI, IKB, JBLK)
  
  ENDDO

ENDDO






IF (NEBN%LSTATNW) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZFLXZ (JI, JK, JBLK)=MAX (0., 2.*ZFLXZ (JI, JK, JBLK))
      
      ENDDO

    ENDDO

  ENDDO

ELSE
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZFLXZ (JI, JK, JBLK)=MAX (0., ZFLXZ (JI, JK, JBLK))
      
      ENDDO

    ENDDO

  ENDDO

ENDIF


IF (KRRL>0) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        PSIGS (JI, JK, JBLK)=ZFLXZ (JI, JK, JBLK)*PATHETA (JI, JK, JBLK)**2
      
      ENDDO

    ENDDO

  ENDDO

ELSE
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      PSIGS (JI,:, JBLK)=0.
    ENDDO

  ENDDO

ENDIF



IF (KRR/=0) THEN
  
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZSHUGRADWK1_2D (JI, JK, JBLK)=0.5*(PPHI3 (JI, JK, JBLK)+PPSI3 (JI&
        &, JK, JBLK))*PDTH_DZ (JI, JK, JBLK)*PDR_DZ (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

  CALL MZF_PHY_MANYBLOCKS (D, ZSHUGRADWK1_2D, ZMZF2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZF (JI, JK, JBLK)=TURBN%XCTV*PLM (JI, JK, JBLK)*PLEPS (JI, JK, JBLK)*ZMZF2D_WORK1 (JI, JK, JBLK)
      
      ENDDO

      ZDFDDTDZ (JI,:, JBLK)=0.
      ZDFDDRDZ (JI,:, JBLK)=0.
    ENDDO

  ENDDO


  

  

  

  IF (GFTH2) THEN
    CALL M3_THR_WTH2_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PD, PLEPS, PSQRT_TKE&
    &, PBLL_O_E, PETHETA, PDR_DZ, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_THR_WTH2_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1, PD, PLEPS,&
    & PSQRT_TKE, PBLL_O_E, PETHETA, PDR_DZ, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_THR_WTH2_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1, PD, PLEPS&
    &, PSQRT_TKE, PBLL_O_E, PETHETA, ZWORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*PFTH2 (JI, JK, JBLK)
          ZDFDDTDZ (JI, JK, JBLK)=ZDFDDTDZ (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*PFTH2 (JI, JK, JBLK)
          ZDFDDRDZ (JI, JK, JBLK)=ZDFDDRDZ (JI, JK, JBLK)+ZWORK3 (JI, JK, JBLK)*PFTH2 (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF


  IF (GFWTH) THEN
    CALL MZF_PHY_MANYBLOCKS (D, PFWTH, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL M3_THR_W2TH_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PD, PLM, PLEPS&
    &, PTKEM, PDR_DZ, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_THR_W2TH_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1, PD, PLM, PLEPS&
    &, PTKEM, PBLL_O_E, PDR_DZ, PETHETA, ZWORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_THR_W2TH_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1&
    &, PD, PLM, PLEPS, PTKEM, ZWORK4, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
          ZDFDDTDZ (JI, JK, JBLK)=ZDFDDTDZ (JI, JK, JBLK)+ZWORK3 (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
          ZDFDDRDZ (JI, JK, JBLK)=ZDFDDRDZ (JI, JK, JBLK)+ZWORK4 (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF


  IF (GFR2) THEN
    CALL M3_THR_WR2_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PD, PLEPS, PSQRT_TKE&
    &, PBLL_O_E, PEMOIST, PDTH_DZ, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_THR_WR2_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PREDTH1, PD, PLEPS&
    &, PSQRT_TKE, PBLL_O_E, PEMOIST, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_THR_WR2_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PREDTH1, PD, PLEPS, PSQRT_TKE&
    &, PBLL_O_E, PEMOIST, PDTH_DZ, ZWORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*PFR2 (JI, JK, JBLK)
          ZDFDDTDZ (JI, JK, JBLK)=ZDFDDTDZ (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*PFR2 (JI, JK, JBLK)
          ZDFDDRDZ (JI, JK, JBLK)=ZDFDDRDZ (JI, JK, JBLK)+ZWORK3 (JI, JK, JBLK)*PFR2 (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF


  IF (GFWR) THEN
    CALL MZF_PHY_MANYBLOCKS (D, PFWR, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL M3_THR_W2R_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PD, PLM, PLEPS&
    &, PTKEM, PDTH_DZ, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_THR_W2R_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PREDTH1&
    &, PD, PLM, PLEPS, PTKEM, ZWORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_THR_W2R_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PREDTH1, PD, PLM, PLEPS&
    &, PTKEM, PBLL_O_E, PDTH_DZ, PEMOIST, ZWORK4, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
          ZDFDDTDZ (JI, JK, JBLK)=ZDFDDTDZ (JI, JK, JBLK)+ZWORK3 (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
          ZDFDDRDZ (JI, JK, JBLK)=ZDFDDRDZ (JI, JK, JBLK)+ZWORK4 (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF


  IF (GFTHR) THEN
    CALL M3_THR_WTHR_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1, PD&
    &, PLEPS, PSQRT_TKE, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_THR_WTHR_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PREDR1, PD, PLEPS&
    &, PSQRT_TKE, PBLL_O_E, PETHETA, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_THR_WTHR_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PREDTH1, PD, PLEPS&
    &, PSQRT_TKE, PBLL_O_E, PEMOIST, ZWORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*PFTHR (JI, JK, JBLK)
          ZDFDDTDZ (JI, JK, JBLK)=ZDFDDTDZ (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*PFTHR (JI, JK, JBLK)
          ZDFDDRDZ (JI, JK, JBLK)=ZDFDDRDZ (JI, JK, JBLK)+ZWORK3 (JI, JK, JBLK)*PFTHR (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF

  
  CALL D_PHI3DTDZ_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, PPHI3, PREDTH1, PREDR1, PRED2TH3&
  &, PRED2THR3, "1DIM", GUSERV, ZWKPHIPSI1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL D_PSI3DTDZ_O_DDTDZ_MANYBLOCKS (D, CSTURB, TURBN, PPSI3, PREDR1, PREDTH1, PRED2R3&
  &, PRED2THR3, "1DIM", GUSERV, ZWKPHIPSI2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL D_PHI3DRDZ_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, PPHI3, PREDTH1, PREDR1, PRED2TH3&
  &, PRED2THR3, "1DIM", GUSERV, ZWKPHIPSI3, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL D_PSI3DRDZ_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, PPSI3, PREDR1, PREDTH1, PRED2R3&
  &, PRED2THR3, "1DIM", GUSERV, ZWKPHIPSI4, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZSHUGRADWK2_2D (JI, JK, JBLK)=PTHLP (JI, JK, JBLK)-PTHLM (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

  CALL DZM_PHY_MANYBLOCKS (D, ZSHUGRADWK2_2D, ZDZM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZSHUGRADWK2_2D (JI, JK, JBLK)=PRP (JI, JK, JBLK)-PRM (JI, JK, 1, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

  CALL DZM_PHY_MANYBLOCKS (D, ZSHUGRADWK2_2D, ZDZM2D_WORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZSHUGRADWK1_2D (JI, JK, JBLK)=(ZWKPHIPSI1 (JI, JK, JBLK)+ZWKPHIPSI2 (JI, JK, JBLK))*PDR_DZ (JI&
        &, JK, JBLK)*ZDZM2D_WORK1 (JI, JK, JBLK)/PDZZ (JI, JK, JBLK)+(ZWKPHIPSI3 (JI, JK, JBLK)+ZWKPHIPSI4&
        & (JI, JK, JBLK))*PDTH_DZ (JI, JK, JBLK)*ZDZM2D_WORK2 (JI, JK, JBLK)/PDZZ (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

  CALL MZF_PHY_MANYBLOCKS (D, ZSHUGRADWK1_2D, ZMZF2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZSHUGRADWK3_2D (JI, JK, JBLK)=PTHLP (JI, JK, JBLK)-PTHLM (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

  CALL DZM_PHY_MANYBLOCKS (D, ZSHUGRADWK3_2D, ZDZM2D_WORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZSHUGRADWK1_2D (JI, JK, JBLK)=ZDZM2D_WORK3 (JI, JK, JBLK)/PDZZ (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

  CALL MZF_PHY_MANYBLOCKS (D, ZSHUGRADWK1_2D, ZMZF2D_WORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZSHUGRADWK2_2D (JI, JK, JBLK)=PRP (JI, JK, JBLK)-PRM (JI, JK, 1, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

  CALL DZM_PHY_MANYBLOCKS (D, ZSHUGRADWK2_2D, ZDZM2D_WORK4, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZSHUGRADWK1_2D (JI, JK, JBLK)=ZDZM2D_WORK4 (JI, JK, JBLK)/PDZZ (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

  CALL MZF_PHY_MANYBLOCKS (D, ZSHUGRADWK1_2D, ZMZF2D_WORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZFLXZ (JI, JK, JBLK)=ZF (JI, JK, JBLK)+TURBN%XIMPL*TURBN%XCTV*PLM (JI, JK, JBLK)*PLEPS (JI&
        &, JK, JBLK)*0.5*ZMZF2D_WORK1 (JI, JK, JBLK)+TURBN%XIMPL*ZDFDDTDZ (JI, JK, JBLK)*ZMZF2D_WORK2&
        & (JI, JK, JBLK)+TURBN%XIMPL*ZDFDDRDZ (JI, JK, JBLK)*ZMZF2D_WORK3 (JI, JK, JBLK)
      
      ENDDO

      
      ZFLXZ (JI, IKB, JBLK)=(TURBN%XCHT1*PPHI3 (JI, IKB+IKL, JBLK)+TURBN%XCHT2*PPSI3 (JI, IKB+IKL, JBLK&
      &))*(PEXPL*(ZCOEFF (JI, IKB+2*IKL, JBLK)*PTHLM (JI, IKB+2*IKL, JBLK)+ZCOEFF (JI, IKB+IKL, JBLK)&
      &*PTHLM (JI, IKB+IKL, JBLK)+ZCOEFF (JI, IKB, JBLK)*PTHLM (JI, IKB, JBLK))*(ZCOEFF (JI, IKB+2*IKL&
      &, JBLK)*PRM (JI, IKB+2*IKL, 1, JBLK)+ZCOEFF (JI, IKB+IKL, JBLK)*PRM (JI, IKB+IKL, 1, JBLK)+ZCOEFF&
      & (JI, IKB, JBLK)*PRM (JI, IKB, 1, JBLK))+TURBN%XIMPL*(ZCOEFF (JI, IKB+2*IKL, JBLK)*PTHLP (JI, IKB&
      &+2*IKL, JBLK)+ZCOEFF (JI, IKB+IKL, JBLK)*PTHLP (JI, IKB+IKL, JBLK)+ZCOEFF (JI, IKB, JBLK)*PTHLP&
      & (JI, IKB, JBLK))*(ZCOEFF (JI, IKB+2*IKL, JBLK)*PRP (JI, IKB+2*IKL, JBLK)+ZCOEFF (JI, IKB+IKL,&
      & JBLK)*PRP (JI, IKB+IKL, JBLK)+ZCOEFF (JI, IKB, JBLK)*PRP (JI, IKB, JBLK)))
      
      
      ZFLXZ (JI, IKA, JBLK)=ZFLXZ (JI, IKB, JBLK)
    
    ENDDO

  ENDDO


  

  

  

  

  

  IF (NEBN%LSTATNW) THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZFLXZ (JI, JK, JBLK)=MIN (0., 2.*ZFLXZ (JI, JK, JBLK))
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF


  IF (KRRL>0) THEN

    IF (NEBN%LSTATNW) THEN
      
      !$ACC PARALLEL LOOP GANG &
      !$ACC&IF (LDACC) &
      !$ACC&PRIVATE (JBLK) &
      !$ACC&VECTOR_LENGTH (D%NIT) 

      

      DO JBLK = 1, KGPBLKS
        
        !$ACC LOOP VECTOR &
        !$ACC&PRIVATE (JI, JK) 

        

        DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

          DO JK=1, IKT
            
            PSIGS (JI, JK, JBLK)=PSIGS (JI, JK, JBLK)-2.*PATHETA (JI,&
            & JK, JBLK)*PAMOIST (JI, JK, JBLK)*ZFLXZ (JI, JK, JBLK)
          
          ENDDO

        ENDDO

      ENDDO

    ELSE
      
      !$ACC PARALLEL LOOP GANG &
      !$ACC&IF (LDACC) &
      !$ACC&PRIVATE (JBLK) &
      !$ACC&VECTOR_LENGTH (D%NIT) 

      

      DO JBLK = 1, KGPBLKS
        
        !$ACC LOOP VECTOR &
        !$ACC&PRIVATE (JI, JK) 

        

        DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

          DO JK=1, IKT
            
            PSIGS (JI, JK, JBLK)=PSIGS (JI, JK, JBLK)+2.*PATHETA (JI,&
            & JK, JBLK)*PAMOIST (JI, JK, JBLK)*ZFLXZ (JI, JK, JBLK)
          
          ENDDO

        ENDDO

      ENDDO

    ENDIF

  ENDIF

  
  
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZSHUGRADWK1_2D (JI, JK, JBLK)=PPSI3 (JI, JK, JBLK)*PDR_DZ (JI, JK, JBLK)**2
      
      ENDDO

    ENDDO

  ENDDO

  CALL MZF_PHY_MANYBLOCKS (D, ZSHUGRADWK1_2D, ZMZF2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZF (JI, JK, JBLK)=TURBN%XCTV*PLM (JI, JK, JBLK)*PLEPS (JI, JK, JBLK)*ZMZF2D_WORK1 (JI, JK, JBLK)
      
      ENDDO

      ZDFDDRDZ (JI,:, JBLK)=0.
    ENDDO

  ENDDO


  

  

  IF (GFR2) THEN
    CALL M3_R2_WR2_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PREDTH1, PD&
    &, PLEPS, PSQRT_TKE, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_R2_WR2_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PREDTH1, PD, PLEPS&
    &, PSQRT_TKE, PBLL_O_E, PEMOIST, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*PFR2 (JI, JK, JBLK)
          ZDFDDRDZ (JI, JK, JBLK)=ZDFDDRDZ (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*PFR2 (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF


  IF (GFWR) THEN
    CALL MZF_PHY_MANYBLOCKS (D, PFWR, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL M3_R2_W2R_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PREDTH1, PD, PDR_DZ&
    &, PLM, PLEPS, PTKEM, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
    CALL D_M3_R2_W2R_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PREDTH1, PD&
    &, PLM, PLEPS, PTKEM, GUSERV, ZWORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
          ZDFDDRDZ (JI, JK, JBLK)=ZDFDDRDZ (JI, JK, JBLK)+ZWORK3 (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF


  IF (KRR/=0) THEN

    IF (GFTH2) THEN
      CALL M3_R2_WTH2_MANYBLOCKS (D, CSTURB, TURBN, PD, PLEPS, PSQRT_TKE, PBLL_O_E&
      &, PETHETA, PDR_DZ, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
      CALL D_M3_R2_WTH2_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PREDTH1, PD, PLEPS,&
      & PSQRT_TKE, PBLL_O_E, PETHETA, PDR_DZ, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
      
      !$ACC PARALLEL LOOP GANG &
      !$ACC&IF (LDACC) &
      !$ACC&PRIVATE (JBLK) &
      !$ACC&VECTOR_LENGTH (D%NIT) 

      

      DO JBLK = 1, KGPBLKS
        
        !$ACC LOOP VECTOR &
        !$ACC&PRIVATE (JI, JK) 

        

        DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

          DO JK=1, IKT
            
            ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*PFTH2 (JI, JK, JBLK)
            ZDFDDRDZ (JI, JK, JBLK)=ZDFDDRDZ (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*PFTH2 (JI, JK, JBLK)
          
          ENDDO

        ENDDO

      ENDDO

    ENDIF


    IF (GFWTH) THEN
      CALL MZF_PHY_MANYBLOCKS (D, PFWTH, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
      CALL M3_R2_W2TH_MANYBLOCKS (D, CSTURB, TURBN, PD, PLM, PLEPS, PTKEM, PBLL_O_E&
      &, PETHETA, PDR_DZ, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
      CALL D_M3_R2_W2TH_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PREDTH1, PD, PLM, PLEPS&
      &, PTKEM, PBLL_O_E, PETHETA, PDR_DZ, ZWORK3, LDACC = LDACC, KGPBLKS = KGPBLKS)
      
      !$ACC PARALLEL LOOP GANG &
      !$ACC&IF (LDACC) &
      !$ACC&PRIVATE (JBLK) &
      !$ACC&VECTOR_LENGTH (D%NIT) 

      

      DO JBLK = 1, KGPBLKS
        
        !$ACC LOOP VECTOR &
        !$ACC&PRIVATE (JI, JK) 

        

        DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

          DO JK=1, IKT
            
            ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
            ZDFDDRDZ (JI, JK, JBLK)=ZDFDDRDZ (JI, JK, JBLK)+ZWORK3 (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
          
          ENDDO

        ENDDO

      ENDDO

    ENDIF


    IF (GFTHR) THEN
      CALL M3_R2_WTHR_MANYBLOCKS (D, CSTURB, TURBN, PREDTH1, PD, PLEPS, PSQRT_TKE&
      &, PBLL_O_E, PETHETA, PDR_DZ, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
      CALL D_M3_R2_WTHR_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, PREDR1, PREDTH1, PD, PLEPS,&
      & PSQRT_TKE, PBLL_O_E, PETHETA, PDR_DZ, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
      
      !$ACC PARALLEL LOOP GANG &
      !$ACC&IF (LDACC) &
      !$ACC&PRIVATE (JBLK) &
      !$ACC&VECTOR_LENGTH (D%NIT) 

      

      DO JBLK = 1, KGPBLKS
        
        !$ACC LOOP VECTOR &
        !$ACC&PRIVATE (JI, JK) 

        

        DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

          DO JK=1, IKT
            
            ZF (JI, JK, JBLK)=ZF (JI, JK, JBLK)+ZWORK1 (JI, JK, JBLK)*PFTHR (JI, JK, JBLK)
            ZDFDDRDZ (JI, JK, JBLK)=ZDFDDRDZ (JI, JK, JBLK)+ZWORK2 (JI, JK, JBLK)*PFTHR (JI, JK, JBLK)
          
          ENDDO

        ENDDO

      ENDDO

    ENDIF

  ENDIF

  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZWORK1 (JI, JK, JBLK)=PRP (JI, JK, JBLK)-PRM (JI, JK, 1, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

  CALL DZM_PHY_MANYBLOCKS (D, ZWORK1, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  CALL D_PSI3DRDZ2_O_DDRDZ_MANYBLOCKS (D, CSTURB, TURBN, PPSI3, PREDR1, PREDTH1, PRED2R3&
  &, PRED2THR3, PDR_DZ, "1DIM", GUSERV, ZWKPHIPSI1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZSHUGRADWK2_2D (JI, JK, JBLK)=PRP (JI, JK, JBLK)-PRM (JI, JK, 1, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

  CALL DZM_PHY_MANYBLOCKS (D, ZSHUGRADWK2_2D, ZDZM2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZSHUGRADWK1_2D (JI, JK, JBLK)=ZWKPHIPSI1 (JI, JK, JBLK&
        &)*ZDZM2D_WORK1 (JI, JK, JBLK)/PDZZ (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

  CALL MZF_PHY_MANYBLOCKS (D, ZSHUGRADWK1_2D, ZMZF2D_WORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZSHUGRADWK2_2D (JI, JK, JBLK)=PRP (JI, JK, JBLK)-PRM (JI, JK, 1, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

  CALL DZM_PHY_MANYBLOCKS (D, ZSHUGRADWK2_2D, ZDZM2D_WORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZSHUGRADWK1_2D (JI, JK, JBLK)=ZDZM2D_WORK2 (JI, JK, JBLK)/PDZZ (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

  CALL MZF_PHY_MANYBLOCKS (D, ZSHUGRADWK1_2D, ZMZF2D_WORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZFLXZ (JI, JK, JBLK)=ZF (JI, JK, JBLK)+TURBN%XIMPL*TURBN%XCTV*PLM (JI, JK, JBLK)*PLEPS (JI, JK, JBLK&
        &)*ZMZF2D_WORK1 (JI, JK, JBLK)+TURBN%XIMPL*ZDFDDRDZ (JI, JK, JBLK)*ZMZF2D_WORK2 (JI, JK, JBLK)
      
      ENDDO

      
      ZFLXZ (JI, IKB, JBLK)=TURBN%XCHV*PPSI3 (JI, IKB+IKL, JBLK)*PLM (JI, IKB, JBLK)*PLEPS (JI,&
      & IKB, JBLK)*(PEXPL*(ZCOEFF (JI, IKB+2*IKL, JBLK)*PRM (JI, IKB+2*IKL, 1, JBLK)+ZCOEFF (JI&
      &, IKB+IKL, JBLK)*PRM (JI, IKB+IKL, 1, JBLK)+ZCOEFF (JI, IKB, JBLK)*PRM (JI, IKB, 1, JBLK&
      &))**2+TURBN%XIMPL*(ZCOEFF (JI, IKB+2*IKL, JBLK)*PRP (JI, IKB+2*IKL, JBLK)+ZCOEFF (JI, IKB&
      &+IKL, JBLK)*PRP (JI, IKB+IKL, JBLK)+ZCOEFF (JI, IKB, JBLK)*PRP (JI, IKB, JBLK))**2)
      
      
      ZFLXZ (JI, IKA, JBLK)=ZFLXZ (JI, IKB, JBLK)
    
    ENDDO

  ENDDO


  

  

  

  

  

  IF (NEBN%LSTATNW) THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          ZFLXZ (JI, JK, JBLK)=MAX (0., 2.*ZFLXZ (JI, JK, JBLK))
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF


  IF (KRRL>0) THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          PSIGS (JI, JK, JBLK)=PSIGS (JI, JK, JBLK)+PAMOIST (JI, JK, JBLK)**2*ZFLXZ (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF

  
ENDIF


IF (KRRL>0) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      
      PSIGS (JI, IKA, JBLK)=PSIGS (JI, IKB, JBLK)
      PSIGS (JI, IKU, JBLK)=PSIGS (JI, IKE, JBLK)

      

      DO JK=1, IKT
        
        PSIGS (JI, JK, JBLK)=SQRT (MAX (PSIGS (JI, JK, JBLK), TURBN%XMINSIGS))
      
      ENDDO

    ENDDO

  ENDDO

  
ENDIF

IF (LHOOK) CALL DR_HOOK ('TURB_VER_THERMO_CORR_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE TURB_VER_THERMO_CORR_MANYBLOCKS

ENDMODULE MODE_TURB_VER_THERMO_CORR_MANYBLOCKS
