
SUBROUTINE TURB_MANYBLOCKS (CST, CSTURB, TURBN, NEBN, D, TLES, KRR, KRRL, KRRI, HLBCX, HLBCY, KGRADIENTSLEO&
&, KGRADIENTSGOG, KHALO, KSPLIT, OCLOUDMODIFLM, KSV, KSV_LGBEG, KSV_LGEND, KSV_LIMA_NR, KSV_LIMA_NS&
&, KSV_LIMA_NG, KSV_LIMA_NH, O2D, ONOMIXLG, OFLAT, OCOUPLES, OBLOWSNOW, OIBM, OFLYER, OCOMPUTE_SRC,&
& PRSNOW, OOCEAN, ODEEPOC, ODIAG_IN_RUN, HTURBLEN_CL, HCLOUD, HELEC, PTSTEP, TPFILE, PDXX, PDYY, PDZZ&
&, PDZX, PDZY, PZZ, PDIRCOSXW, PDIRCOSYW, PDIRCOSZW, PCOSSLOPE, PSINSLOPE, PRHODJ, PTHVREF, PHGRADLEO&
&, PHGRADGOG, PZS, PSFTH, PSFRV, PSFSV, PSFU, PSFV, PPABST, PUT, PVT, PWT, PTKET, PSVT, PSRCT, PLENGTHM&
&, PLENGTHH, MFMOIST, PBL_DEPTH, PSBL_DEPTH, PCEI, PCEI_MIN, PCEI_MAX, PCOEF_AMPL_SAT, PTHLT, PRT, PRUS&
&, PRVS, PRWS, PRTHLS, PRRS, PRSVS, PRTKES, PSIGS, PFLXZTHVMF, PFLXZUMF, PFLXZVMF, PWTH, PWRC, PWSV&
&, PDP, PTP, PTDIFF, PTDISS, KBUDGETS, PEDR, PLEM, PRTKEMS, PDPMF, PTPMF, PDRUS_TURB, PDRVS_TURB, PDRTHLS_TURB&
&, PDRRTS_TURB, PDRSVS_TURB, PTR, PDISS, PIBM_LS, PIBM_XMUT, PCURRENT_TKE_DISS, PSSTFL, PSSTFL_C, PSSRFL_C&
&, PSSUFL_C, PSSVFL_C, PSSUFL, PSSVFL, LDACC, KGPBLKS)
USE MODE_SHUMAN_PHY,ONLY:MZF_PHY, MXF_PHY, MYF_PHY
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MZF_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MYF_PHY_MANYBLOCKS
USE MODE_SHUMAN_PHY_MANYBLOCKS, ONLY : MXF_PHY_MANYBLOCKS
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE MODD_BUDGET,ONLY:NBUDGET_U, NBUDGET_V, NBUDGET_W, NBUDGET_TH, NBUDGET_RV, NBUDGET_RC, NBUDGET_RI&
&, NBUDGET_SV1, NBUDGET_RG, NBUDGET_RH, NBUDGET_RR, NBUDGET_RS, TBUDGETDATA_PTR, TBUDGETCONF_T
USE MODD_CST,ONLY:CST_T
USE MODD_CTURB,ONLY:CSTURB_T
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_FIELD,ONLY:TFIELDMETADATA, TYPEREAL
USE MODD_IO,ONLY:TFILEDATA
USE MODD_LES,ONLY:TLES_T
USE MODD_PARAMETERS,ONLY:JPVEXT_TURB, XUNDEF
USE MODD_TURB_N,ONLY:TURB_T
USE MODD_NEB_N,ONLY:NEB_T
USE MODE_BL89,ONLY:BL89
USE MODE_BL89_MANYBLOCKS, ONLY : BL89_MANYBLOCKS
USE MODE_CLOUD_MODIF_LM,ONLY:CLOUD_MODIF_LM
USE MODE_CLOUD_MODIF_LM_MANYBLOCKS, ONLY : CLOUD_MODIF_LM_MANYBLOCKS
USE MODE_COMPUTE_FUNCTION_THERMO_NEW_STAT,ONLY:COMPUTE_FUNCTION_THERMO_NEW_STAT
USE MODE_COMPUTE_FUNCTION_THERMO_NEW_STAT_MANYBLOCKS, ONLY&
& : COMPUTE_FUNCTION_THERMO_NEW_STAT_MANYBLOCKS
USE MODE_COMPUTE_FUNCTION_THERMO,ONLY:COMPUTE_FUNCTION_THERMO
USE MODE_COMPUTE_FUNCTION_THERMO_MANYBLOCKS, ONLY : COMPUTE_FUNCTION_THERMO_MANYBLOCKS
USE MODE_DEAR,ONLY:DEAR
USE MODE_DEAR_MANYBLOCKS, ONLY : DEAR_MANYBLOCKS
USE MODE_DELT,ONLY:DELT
USE MODE_DELT_MANYBLOCKS, ONLY : DELT_MANYBLOCKS
USE MODE_EMOIST,ONLY:EMOIST
USE MODE_ETHETA,ONLY:ETHETA
USE MODE_GRADIENT_U_PHY,ONLY:GZ_U_UW_PHY
USE MODE_GRADIENT_U_PHY_MANYBLOCKS, ONLY : GZ_U_UW_PHY_MANYBLOCKS
USE MODE_GRADIENT_V_PHY,ONLY:GZ_V_VW_PHY
USE MODE_GRADIENT_V_PHY_MANYBLOCKS, ONLY : GZ_V_VW_PHY_MANYBLOCKS
USE MODE_GRADIENT_W_PHY,ONLY:GZ_W_M_PHY
USE MODE_GRADIENT_M_PHY,ONLY:GZ_M_W_PHY
USE MODE_IBM_MIXINGLENGTH,ONLY:IBM_MIXINGLENGTH
USE MODE_IBM_MIXINGLENGTH_MANYBLOCKS, ONLY : IBM_MIXINGLENGTH_MANYBLOCKS
USE MODE_IO_FIELD_WRITE_PHY,ONLY:IO_FIELD_WRITE_PHY
USE MODE_SBL_PHY,ONLY:LMO
USE MODE_SOURCES_NEG_CORRECT,ONLY:SOURCES_NEG_CORRECT_PHY
USE MODE_SOURCES_NEG_CORRECT_MANYBLOCKS, ONLY : SOURCES_NEG_CORRECT_PHY_MANYBLOCKS
USE MODE_TKE_EPS_SOURCES,ONLY:TKE_EPS_SOURCES
USE MODE_TKE_EPS_SOURCES_MANYBLOCKS, ONLY : TKE_EPS_SOURCES_MANYBLOCKS
USE MODE_TURB_VER,ONLY:TURB_VER
USE MODE_TURB_VER_MANYBLOCKS, ONLY : TURB_VER_MANYBLOCKS
USE MODI_LES_MEAN_SUBGRID_PHY
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"
IMPLICIT NONE



#ifdef MNH_COMPILER_CCE
#endif
TYPE (DIMPHYEX_T), INTENT (IN)::D
TYPE (CST_T), INTENT (IN)::CST
TYPE (CSTURB_T), INTENT (IN)::CSTURB
TYPE (TURB_T), INTENT (IN)::TURBN
TYPE (NEB_T), INTENT (IN)::NEBN
TYPE (TLES_T), INTENT (INOUT)::TLES
INTEGER, INTENT (IN)::KGRADIENTSLEO
INTEGER, INTENT (IN)::KGRADIENTSGOG
INTEGER, INTENT (IN)::KRR
INTEGER, INTENT (IN)::KRRL
INTEGER, INTENT (IN)::KRRI
INTEGER, INTENT (IN)::KSV_LGEND
INTEGER, INTENT (IN)::KSV_LGBEG
INTEGER, INTENT (IN)::KSV
INTEGER, INTENT (IN)::KSV_LIMA_NH
INTEGER, INTENT (IN)::KSV_LIMA_NG
INTEGER, INTENT (IN)::KSV_LIMA_NS
INTEGER, INTENT (IN)::KSV_LIMA_NR
CHARACTER (LEN=4), INTENT (IN)::HLBCY(2)
CHARACTER (LEN=4), INTENT (IN)::HLBCX(2)
INTEGER, INTENT (IN)::KSPLIT
LOGICAL, INTENT (IN)::OCLOUDMODIFLM
INTEGER, INTENT (IN)::KHALO
LOGICAL, INTENT (IN)::OCOMPUTE_SRC
LOGICAL, INTENT (IN)::OOCEAN
LOGICAL, INTENT (IN)::ODEEPOC
LOGICAL, INTENT (IN)::OFLYER
LOGICAL, INTENT (IN)::OFLAT
LOGICAL, INTENT (IN)::OCOUPLES
LOGICAL, INTENT (IN)::OBLOWSNOW
LOGICAL, INTENT (IN)::ODIAG_IN_RUN
LOGICAL, INTENT (IN)::OIBM
CHARACTER (LEN=4), INTENT (IN)::HTURBLEN_CL
CHARACTER (LEN=4), INTENT (IN)::HCLOUD
CHARACTER (LEN=4), INTENT (IN)::HELEC
REAL, INTENT (IN)::PRSNOW
REAL, INTENT (IN)::PTSTEP
TYPE (TFILEDATA), INTENT (INOUT)::TPFILE
REAL, INTENT (IN)::PDZY(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDZX(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDZZ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDYY(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDXX(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PZZ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PDIRCOSZW(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PDIRCOSYW(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PDIRCOSXW(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PCOSSLOPE(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSINSLOPE(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PZS(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PRHODJ(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::MFMOIST(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHVREF(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PHGRADLEO(:, :, :, :) ! (D%NIJT, D%NKT, KGRADIENTSLEO)
REAL, INTENT (IN)::PHGRADGOG(:, :, :, :) ! (D%NIJT, D%NKT, KGRADIENTSGOG)
REAL, INTENT (IN)::PSFV(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFU(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFRV(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFTH(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PSFSV(:, :, :) ! (D%NIJT, KSV)
REAL, INTENT (IN)::PPABST(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PWT(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PVT(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PUT(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PTKET(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PSVT(:, :, :, :) ! (D%NIJT, D%NKT, KSV)
REAL, INTENT (IN)::PSRCT(:, :, :)
REAL, INTENT (INOUT)::PBL_DEPTH(:, :) ! (D%NIJT)
REAL, INTENT (INOUT)::PSBL_DEPTH(:, :) ! (D%NIJT)
REAL, INTENT (IN)::PCEI(:, :, :)
REAL, INTENT (IN)::PCEI_MIN
REAL, INTENT (IN)::PCEI_MAX
REAL, INTENT (IN)::PCOEF_AMPL_SAT
REAL, INTENT (INOUT)::PTHLT(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRT(:, :, :, :) ! (D%NIJT, D%NKT, KRR)
REAL, INTENT (INOUT)::PRTKES(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRTHLS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRWS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRVS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRUS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN), OPTIONAL, TARGET::PRTKEMS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRRS(:, :, :, :) ! (D%NIJT, D%NKT, KRR)
REAL, INTENT (INOUT)::PRSVS(:, :, :, :) ! (D%NIJT, D%NKT, KSV)
REAL, INTENT (OUT)::PSIGS(:, :, :)
REAL, INTENT (OUT), OPTIONAL, TARGET::PDRUS_TURB(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT), OPTIONAL, TARGET::PDRVS_TURB(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT), OPTIONAL, TARGET::PDRTHLS_TURB(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT), OPTIONAL, TARGET::PDRRTS_TURB(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT), OPTIONAL, TARGET::PDRSVS_TURB(:, :, :, :) ! (D%NIJT, D%NKT, KSV)
REAL, INTENT (IN)::PFLXZTHVMF(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT)::PWTH(:, :, :)
REAL, INTENT (OUT)::PWRC(:, :, :)
REAL, INTENT (OUT)::PWSV(:, :, :, :)
REAL, INTENT (IN)::PFLXZUMF(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PFLXZVMF(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT)::PTP(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT), OPTIONAL, TARGET::PTPMF(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT)::PDP(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT), OPTIONAL, TARGET::PDPMF(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT)::PTDIFF(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT)::PTDISS(:, :, :) ! (D%NIJT, D%NKT)
INTEGER, INTENT (IN)::KBUDGETS
LOGICAL, INTENT (IN)::ONOMIXLG
LOGICAL, INTENT (IN)::O2D
REAL, INTENT (IN)::PLENGTHH(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (IN)::PLENGTHM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT), OPTIONAL, TARGET::PEDR(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT), OPTIONAL, TARGET::PLEM(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT), OPTIONAL, TARGET::PTR(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (OUT), OPTIONAL, TARGET::PDISS(:, :, :) ! (D%NIJT, D%NKT)
REAL, INTENT (INOUT), OPTIONAL, TARGET::PCURRENT_TKE_DISS(MERGE&
& (D%NIJT, 0, .FALSE.), MERGE (D%NKT, 0, .FALSE.))
REAL, INTENT (IN), OPTIONAL, TARGET::PSSTFL(MERGE (D%NIJT, 0, OCOUPLES))
REAL, INTENT (IN), OPTIONAL, TARGET::PSSTFL_C(MERGE (D%NIJT, 0, OCOUPLES))
REAL, INTENT (IN), OPTIONAL, TARGET::PSSRFL_C(MERGE (D%NIJT, 0, OCOUPLES))
REAL, INTENT (IN), OPTIONAL, TARGET::PSSUFL_C(MERGE (D%NIJT, 0, OCOUPLES))
REAL, INTENT (IN), OPTIONAL, TARGET::PSSVFL_C(MERGE (D%NIJT, 0, OCOUPLES))
REAL, INTENT (IN), OPTIONAL, TARGET::PSSUFL(MERGE (D%NIJT, 0, OCOUPLES))
REAL, INTENT (IN), OPTIONAL, TARGET::PSSVFL(MERGE (D%NIJT, 0, OCOUPLES))
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL, INTENT (OUT), OPTIONAL, TARGET::PIBM_XMUT(MERGE (D%NIJT, 0, OIBM), MERGE (D%NKT, 0, OIBM))
REAL, INTENT (IN), OPTIONAL, TARGET::PIBM_LS(MERGE (D%NIJT, 0, OIBM), MERGE (D%NKT, 0, OIBM))
REAL::ZTEMP_BUD(D%NIJT, D%NKT,KGPBLKS)
REAL::ZCOEF_AMPL(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZWORK1(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDRVSATDT(D%NIJT, D%NKT,KGPBLKS)
REAL::ZRVSAT(D%NIJT, D%NKT,KGPBLKS)
REAL::ZAMOIST_ICE(D%NIJT, D%NKT,KGPBLKS)
REAL::ZATHETA_ICE(D%NIJT, D%NKT,KGPBLKS)
REAL::ZLSOCPEXNM(D%NIJT, D%NKT,KGPBLKS)
REAL::ZLVOCPEXNM(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDVDZ(D%NIJT, D%NKT,KGPBLKS)
REAL::ZDUDZ(D%NIJT, D%NKT,KGPBLKS)
REAL::ZSHEAR(D%NIJT, D%NKT,KGPBLKS)
REAL::ZRTKEMS(D%NIJT, D%NKT,KGPBLKS)
REAL::ZTHLM(D%NIJT, D%NKT,KGPBLKS)
REAL::ZFTHR(D%NIJT, D%NKT,KGPBLKS)
REAL::ZFR2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZFTH2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZFWR(D%NIJT, D%NKT,KGPBLKS)
REAL::ZFWTH(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMTHR(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMR2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMTH2(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMWR(D%NIJT, D%NKT,KGPBLKS)
REAL::ZMWTH(D%NIJT, D%NKT,KGPBLKS)
REAL::ZFRAC_ICE(D%NIJT, D%NKT,KGPBLKS)
REAL::ZCOEF_DISS(D%NIJT, D%NKT,KGPBLKS)
REAL::ZAMOIST(D%NIJT, D%NKT,KGPBLKS)
REAL::ZATHETA(D%NIJT, D%NKT,KGPBLKS)
REAL::ZTRH(D%NIJT, D%NKT,KGPBLKS)
REAL::ZLEPS(D%NIJT, D%NKT,KGPBLKS)
REAL::ZLMW(D%NIJT, D%NKT,KGPBLKS)
REAL::ZLM(D%NIJT, D%NKT,KGPBLKS)
REAL::ZLOCPEXNM(D%NIJT, D%NKT,KGPBLKS)
REAL::ZT(D%NIJT, D%NKT,KGPBLKS)
REAL::ZEXN(D%NIJT, D%NKT,KGPBLKS)
REAL::ZCP(D%NIJT, D%NKT,KGPBLKS)
REAL::ZRM(D%NIJT, D%NKT, KRR,KGPBLKS)
REAL::ZWORK2D(D%NIJT,KGPBLKS)
REAL::ZSFRV(D%NIJT,KGPBLKS)
REAL::ZRVM(D%NIJT,KGPBLKS)
REAL::ZLMO(D%NIJT,KGPBLKS)
REAL::ZUSTAR(D%NIJT,KGPBLKS)
REAL::ZCDUEFF(D%NIJT,KGPBLKS)
REAL::ZVSLOPE(D%NIJT,KGPBLKS)
REAL::ZUSLOPE(D%NIJT,KGPBLKS)
REAL::ZTAU33M(D%NIJT,KGPBLKS)
REAL::ZTAU22M(D%NIJT,KGPBLKS)
REAL::ZTAU12M(D%NIJT,KGPBLKS)
REAL::ZTAU11M(D%NIJT,KGPBLKS)
REAL::ZRSVS(D%NIJT, D%NKT, KSV,KGPBLKS)
REAL::ZEXPL
REAL::ZRVORD
REAL::ZEPS
REAL::ZPENTE
REAL::ZCOEF_AMPL_CEI_NUL
INTEGER::IKE
INTEGER::IKB
INTEGER::IIJE
INTEGER::IIJB
INTEGER::IKU
INTEGER::IKA
INTEGER::IKT
INTEGER::IKL
INTEGER::IKTE
INTEGER::IKTB
INTEGER::JSV
INTEGER::JK
INTEGER::JRR
INTEGER::JI
REAL::ZL0
REAL::ZALPHA
REAL::ZTIME2
REAL::ZTIME1
LOGICAL::GOCEAN
LOGICAL::GTURBLEN_BL89_TURBLEN_RM17_TURBLEN_HM21_ORMC01
TYPE (TFIELDMETADATA)::TZFIELD
REAL::ZWORKS(D%NIJT, D%NKT, MERGE (KSV+KRR, KSV, TURBN%LTURB_PRECIP),KGPBLKS)
REAL::ZWORKT(D%NIJT, D%NKT, MERGE (KSV+KRR, KSV, TURBN%LTURB_PRECIP),KGPBLKS)
REAL::ZWORKSFSV(D%NIJT, MERGE (KSV+KRR, KSV, TURBN%LTURB_PRECIP),KGPBLKS)
REAL::ZWORKWSV(D%NIJT, D%NKT, MERGE (KSV+KRR, KSV, TURBN%LTURB_PRECIP),KGPBLKS)
INTEGER::ISV
REAL (KIND=JPHOOK)::ZHOOK_HANDLE2
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
REAL, POINTER :: PCURRENT_TKE_DISS_PTR
REAL, POINTER :: PDISS_PTR
REAL, POINTER :: PDPMF_PTR
REAL, POINTER :: PDRRTS_TURB_PTR
REAL, POINTER :: PDRSVS_TURB_PTR
REAL, POINTER :: PDRTHLS_TURB_PTR
REAL, POINTER :: PDRUS_TURB_PTR
REAL, POINTER :: PDRVS_TURB_PTR
REAL, POINTER :: PEDR_PTR
REAL, POINTER :: PIBM_LS_PTR
REAL, POINTER :: PIBM_XMUT_PTR
REAL, POINTER :: PLEM_PTR
REAL, POINTER :: PRTKEMS_PTR
REAL, POINTER :: PSSRFL_C_PTR
REAL, POINTER :: PSSTFL_PTR
REAL, POINTER :: PSSTFL_C_PTR
REAL, POINTER :: PSSUFL_PTR
REAL, POINTER :: PSSUFL_C_PTR
REAL, POINTER :: PSSVFL_PTR
REAL, POINTER :: PSSVFL_C_PTR
REAL, POINTER :: PTPMF_PTR
REAL, POINTER :: PTR_PTR
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: JBLK


!$ACC DATA &
!$ACC&CREATE (ZAMOIST, ZAMOIST_ICE, ZATHETA, ZATHETA_ICE, ZCDUEFF, ZCOEF_AMPL, &
!$ACC&        ZCOEF_DISS, ZCP, ZDRVSATDT, ZDUDZ, ZDVDZ, ZEXN, ZFR2, ZFRAC_ICE, ZFTH2, &
!$ACC&        ZFTHR, ZFWR, ZFWTH, ZLEPS, ZLM, ZLMO, ZLMW, ZLOCPEXNM, ZLSOCPEXNM, ZLVOCPEXNM, &
!$ACC&        ZMR2, ZMTH2, ZMTHR, ZMWR, ZMWTH, ZRM, ZRSVS, ZRTKEMS, ZRVM, ZRVSAT, ZSFRV, &
!$ACC&        ZSHEAR, ZT, ZTAU11M, ZTAU12M, ZTAU22M, ZTAU33M, ZTEMP_BUD, ZTHLM, ZTRH, &
!$ACC&        ZUSLOPE, ZUSTAR, ZVSLOPE, ZWORK1, ZWORK2, ZWORK2D, ZWORKS, ZWORKSFSV, &
!$ACC&        ZWORKT, ZWORKWSV) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (CST, CSTURB, D, MFMOIST, NEBN, PBL_DEPTH, PCEI, PCOSSLOPE, PCURRENT_TKE_DISS, &
!$ACC&         PDIRCOSXW, PDIRCOSYW, PDIRCOSZW, PDISS, PDP, PDPMF, PDRRTS_TURB, &
!$ACC&         PDRSVS_TURB, PDRTHLS_TURB, PDRUS_TURB, PDRVS_TURB, PDXX, PDYY, &
!$ACC&         PDZX, PDZY, PDZZ, PEDR, PFLXZTHVMF, PFLXZUMF, PFLXZVMF, PHGRADGOG, &
!$ACC&         PHGRADLEO, PIBM_LS, PIBM_XMUT, PLEM, PLENGTHH, PLENGTHM, PPABST, &
!$ACC&         PRHODJ, PRRS, PRSVS, PRT, PRTHLS, PRTKEMS, PRTKES, PRUS, PRVS, PRWS, PSBL_DEPTH, &
!$ACC&         PSFRV, PSFSV, PSFTH, PSFU, PSFV, PSIGS, PSINSLOPE, PSRCT, PSSRFL_C, PSSTFL, &
!$ACC&         PSSTFL_C, PSSUFL, PSSUFL_C, PSSVFL, PSSVFL_C, PSVT, PTDIFF, PTDISS, &
!$ACC&         PTHLT, PTHVREF, PTKET, PTP, PTPMF, PTR, PUT, PVT, PWRC, PWSV, PWT, PWTH, PZS, &
!$ACC&         PZZ, TLES, TPFILE, TURBN) 

IF (LHOOK) CALL DR_HOOK ('TURB_MANYBLOCKS', 0, ZHOOK_HANDLE)
IKT=D%NKT
IKTB=D%NKTB
IKTE=D%NKTE
IKB=D%NKB
IKE=D%NKE
IKA=D%NKA
IKU=D%NKU
IKL=D%NKL
IIJE=D%NIJE
IIJB=D%NIJB
ZEXPL=1.-TURBN%XIMPL
ZRVORD=CST%XRV/CST%XRD
GOCEAN=OOCEAN
GTURBLEN_BL89_TURBLEN_RM17_TURBLEN_HM21_ORMC01=TURBN%CTURBLEN=='BL89'.OR&
&.TURBN%CTURBLEN=='RM17'.OR.TURBN%CTURBLEN=='HM21'.OR.TURBN%LRMC01

IF (GTURBLEN_BL89_TURBLEN_RM17_TURBLEN_HM21_ORMC01) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      ZTHLM (JI, 1:IKT, JBLK)=PTHLT (JI, 1:IKT, JBLK)
      ZRM (JI, 1:IKT,:, JBLK)=PRT (JI, 1:IKT,:, JBLK)
    ENDDO

  ENDDO

  
ENDIF


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    ZRSVS (JI, 1:IKT, 1:KSV, JBLK)=PRSVS (JI, 1:IKT, 1:KSV, JBLK)
  ENDDO

ENDDO

ISV=KSV

IF (TURBN%LTURB_PRECIP)  THEN
  ISV=KSV+KRR
ENDIF


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    ZWORKT (JI,:, 1:KSV, JBLK)=PSVT (JI,:,:, JBLK)
    ZWORKS (JI,:, 1:KSV, JBLK)=PRSVS (JI,:,:, JBLK)
  ENDDO

ENDDO



IF (TURBN%LTURB_PRECIP)  THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      ZWORKT (JI,:, KSV+1:KSV+KRR, JBLK)=PRT (JI,:,:, JBLK)
    ENDDO

  ENDDO

ENDIF


IF (TURBN%LTURB_PRECIP)  THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      ZWORKS (JI,:, KSV+1:KSV+KRR, JBLK)=PRRS (JI,:,:, JBLK)
    ENDDO

  ENDDO

ENDIF


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    ZWORKSFSV (JI,:, JBLK)=0.
    ZWORKWSV (JI,:,:, JBLK)=0.
    ZWORKSFSV (JI, 1:KSV, JBLK)=PSFSV (JI,:, JBLK)

    DO JK=1, IKT
      
      ZCP (JI, JK, JBLK)=CST%XCPD

      IF (KRR>0)  THEN
        ZCP (JI, JK, JBLK)=ZCP (JI, JK, JBLK)+CST%XCPV*PRT (JI, JK, 1, JBLK)
      ENDIF

    
    ENDDO

  ENDDO

ENDDO





DO JRR=2, 1+KRRL
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZCP (JI, JK, JBLK)=ZCP (JI, JK, JBLK)+CST%XCL*PRT (JI, JK, JRR, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDDO


DO JRR=2+KRRL, 1+KRRL+KRRI
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZCP (JI, JK, JBLK)=ZCP (JI, JK, JBLK)+CST%XCI*PRT (JI, JK, JRR, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ENDDO



!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZEXN (JI, JK, JBLK)=(PPABST (JI, JK, JBLK)/CST%XP00)**(CST%XRD/CST%XCPD)
    
    ENDDO


    DO JK=1, IKT
      
      ZCOEF_DISS (JI, JK, JBLK)=1/(ZCP (JI, JK, JBLK)*ZEXN (JI, JK, JBLK))
      ZFRAC_ICE (JI, JK, JBLK)=0.0
      ZATHETA (JI, JK, JBLK)=0.0
      ZAMOIST (JI, JK, JBLK)=0.0
    
    ENDDO

  ENDDO

ENDDO




IF (KRRL>=1) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZT (JI, JK, JBLK)=PTHLT (JI, JK, JBLK)*ZEXN (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO


  IF (KRRI>=1) THEN

    IF (NEBN%LSTATNW) THEN
      CALL COMPUTE_FUNCTION_THERMO_NEW_STAT_MANYBLOCKS (D, CST, CST%XALPW, CST%XBETAW, CST%XGAMW, CST%XLVTT&
      &, CST%XCL, ZT, ZEXN, ZCP, ZLVOCPEXNM, ZAMOIST, ZATHETA, PPABST, LDACC = LDACC, KGPBLKS = KGPBLKS)
      CALL COMPUTE_FUNCTION_THERMO_NEW_STAT_MANYBLOCKS (D, CST, CST%XALPI, CST&
      &%XBETAI, CST%XGAMI, CST%XLSTT, CST%XCI, ZT, ZEXN, ZCP, ZLSOCPEXNM, ZAMOIST_ICE&
      &, ZATHETA_ICE, PPABST, LDACC = LDACC, KGPBLKS = KGPBLKS)
    ELSE
      CALL COMPUTE_FUNCTION_THERMO_MANYBLOCKS (D, CST, CST%XALPW, CST%XBETAW, CST%XGAMW, CST%XLVTT, CST%XCL&
      &, ZT, ZEXN, ZCP, ZLVOCPEXNM, ZAMOIST, ZATHETA, PRT, PPABST, KRR, LDACC = LDACC, KGPBLKS = KGPBLKS)
      CALL COMPUTE_FUNCTION_THERMO_MANYBLOCKS (D, CST, CST%XALPI, CST%XBETAI,&
      & CST%XGAMI, CST%XLSTT, CST%XCI, ZT, ZEXN, ZCP, ZLSOCPEXNM, ZAMOIST_ICE&
      &, ZATHETA_ICE, PRT, PPABST, KRR, LDACC = LDACC, KGPBLKS = KGPBLKS)
    ENDIF

    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT

          

          IF (PRT (JI, JK, 2, JBLK)+PRT (JI, JK, 4, JBLK)>0.0) THEN
            ZFRAC_ICE (JI, JK, JBLK)=PRT (JI, JK, 4, JBLK)/(PRT (JI, JK, 2, JBLK)+PRT (JI, JK, 4, JBLK))
          ENDIF

        
        ENDDO


        DO JK=1, IKT
          
          ZLOCPEXNM (JI, JK, JBLK)=(1.0-ZFRAC_ICE (JI, JK, JBLK))*ZLVOCPEXNM (JI&
          &, JK, JBLK)+ZFRAC_ICE (JI, JK, JBLK)*ZLSOCPEXNM (JI, JK, JBLK)
          ZAMOIST (JI, JK, JBLK)=(1.0-ZFRAC_ICE (JI, JK, JBLK))*ZAMOIST (JI,&
          & JK, JBLK)+ZFRAC_ICE (JI, JK, JBLK)*ZAMOIST_ICE (JI, JK, JBLK)
          ZATHETA (JI, JK, JBLK)=(1.0-ZFRAC_ICE (JI, JK, JBLK))*ZATHETA (JI,&
          & JK, JBLK)+ZFRAC_ICE (JI, JK, JBLK)*ZATHETA_ICE (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  
  ELSE

    IF (NEBN%LSTATNW) THEN
      CALL COMPUTE_FUNCTION_THERMO_NEW_STAT_MANYBLOCKS (D, CST, CST%XALPW, CST%XBETAW, CST%XGAMW, CST%XLVTT&
      &, CST%XCL, ZT, ZEXN, ZCP, ZLOCPEXNM, ZAMOIST, ZATHETA, PPABST, LDACC = LDACC, KGPBLKS = KGPBLKS)
    ELSE
      CALL COMPUTE_FUNCTION_THERMO_MANYBLOCKS (D, CST, CST%XALPW, CST%XBETAW, CST%XGAMW, CST%XLVTT, CST%XCL&
      &, ZT, ZEXN, ZCP, ZLOCPEXNM, ZAMOIST, ZATHETA, PRT, PPABST, KRR, LDACC = LDACC, KGPBLKS = KGPBLKS)
    ENDIF

  ENDIF

  
ELSE
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      ZLOCPEXNM (JI, 1:IKT, JBLK)=0.
    ENDDO

  ENDDO

ENDIF


IF (KRRL>=1) THEN

  IF (KRRI>=1) THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          PRT (JI, JK, 1, JBLK)=PRT (JI, JK, 1, JBLK)+PRT (JI, JK, 2, JBLK)+PRT (JI, JK, 4, JBLK)
          PRRS (JI, JK, 1, JBLK)=PRRS (JI, JK, 1, JBLK)+PRRS (JI, JK, 2, JBLK)+PRRS (JI, JK, 4, JBLK)
          PTHLT (JI, JK, JBLK)=PTHLT (JI, JK, JBLK)-ZLVOCPEXNM (JI, JK, JBLK)*PRT&
          & (JI, JK, 2, JBLK)-ZLSOCPEXNM (JI, JK, JBLK)*PRT (JI, JK, 4, JBLK)
          PRTHLS (JI, JK, JBLK)=PRTHLS (JI, JK, JBLK)-ZLVOCPEXNM (JI, JK, JBLK)*PRRS&
          & (JI, JK, 2, JBLK)-ZLSOCPEXNM (JI, JK, JBLK)*PRRS (JI, JK, 4, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ELSE
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          PRT (JI, JK, 1, JBLK)=PRT (JI, JK, 1, JBLK)+PRT (JI, JK, 2, JBLK)
          PRRS (JI, JK, 1, JBLK)=PRRS (JI, JK, 1, JBLK)+PRRS (JI, JK, 2, JBLK)
          PTHLT (JI, JK, JBLK)=PTHLT (JI, JK, JBLK)-ZLOCPEXNM (JI, JK, JBLK)*PRT (JI, JK, 2, JBLK)
          PRTHLS (JI, JK, JBLK)=PRTHLS (JI, JK, JBLK)-ZLOCPEXNM (JI, JK, JBLK)*PRRS (JI, JK, 2, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF

ENDIF


IF (PRESENT (PDRUS_TURB)) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      PDRUS_TURB (JI,:, JBLK)=PRUS (JI,:, JBLK)
      PDRVS_TURB (JI,:, JBLK)=PRVS (JI,:, JBLK)
      PDRTHLS_TURB (JI,:, JBLK)=PRTHLS (JI,:, JBLK)
      PDRRTS_TURB (JI,:, JBLK)=PRRS (JI,:, 1, JBLK)
      PDRSVS_TURB (JI,:,:, JBLK)=PRSVS (JI,:,:, JBLK)
    ENDDO

  ENDDO

  
  
  
  
ENDIF



SELECTCASE (TURBN%CTURBLEN)
CASE ('BL89')
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      ZSHEAR (JI,:, JBLK)=0.
    ENDDO

  ENDDO

  CALL BL89_MANYBLOCKS (D, CST, CSTURB, TURBN, PZZ, PDZZ, PTHVREF, ZTHLM, KRR&
  &, ZRM, PTKET, ZSHEAR, ZLM, .FALSE., LDACC = LDACC, KGPBLKS = KGPBLKS)
CASE ('RM17')
  CALL GZ_U_UW_PHY_MANYBLOCKS (D, PUT, PDZZ, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL MZF_PHY_MANYBLOCKS (D, ZWORK1, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL MXF_PHY_MANYBLOCKS (D, ZWORK2, ZDUDZ, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL GZ_V_VW_PHY_MANYBLOCKS (D, PVT, PDZZ, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL MZF_PHY_MANYBLOCKS (D, ZWORK1, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL MYF_PHY_MANYBLOCKS (D, ZWORK2, ZDVDZ, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZSHEAR (JI, JK, JBLK)=SQRT (ZDUDZ (JI, JK, JBLK)*ZDUDZ (JI&
        &, JK, JBLK)+ZDVDZ (JI, JK, JBLK)*ZDVDZ (JI, JK, JBLK))
      
      ENDDO

    ENDDO

  ENDDO

  CALL BL89_MANYBLOCKS (D, CST, CSTURB, TURBN, PZZ, PDZZ, PTHVREF, ZTHLM, KRR&
  &, ZRM, PTKET, ZSHEAR, ZLM, .FALSE., LDACC = LDACC, KGPBLKS = KGPBLKS)
CASE ('HM21')
  CALL GZ_U_UW_PHY_MANYBLOCKS (D, PUT, PDZZ, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL MZF_PHY_MANYBLOCKS (D, ZWORK1, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL MXF_PHY_MANYBLOCKS (D, ZWORK2, ZDUDZ, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL GZ_V_VW_PHY_MANYBLOCKS (D, PVT, PDZZ, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL MZF_PHY_MANYBLOCKS (D, ZWORK1, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL MYF_PHY_MANYBLOCKS (D, ZWORK2, ZDVDZ, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZSHEAR (JI, JK, JBLK)=SQRT (ZDUDZ (JI, JK, JBLK)*ZDUDZ (JI&
        &, JK, JBLK)+ZDVDZ (JI, JK, JBLK)*ZDVDZ (JI, JK, JBLK))
      
      ENDDO

    ENDDO

  ENDDO

  CALL BL89_MANYBLOCKS (D, CST, CSTURB, TURBN, PZZ, PDZZ, PTHVREF, ZTHLM, KRR&
  &, ZRM, PTKET, ZSHEAR, ZLM, .FALSE., LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL DELT_MANYBLOCKS (D, TURBN, .FALSE.,.FALSE., .FALSE., PZZ, PDYY&
  &, PDXX, PDIRCOSZW, ZLMW, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZLM (JI, JK, JBLK)=MIN (ZLM (JI, JK, JBLK), TURBN%XCADAP*ZLMW (JI, JK, JBLK))
      
      ENDDO

    ENDDO

  ENDDO

CASE ('DELT')
  CALL DELT_MANYBLOCKS (D, TURBN, .FALSE.,.TRUE., .FALSE., PZZ, PDYY&
  &, PDXX, PDIRCOSZW, ZLMW, LDACC = LDACC, KGPBLKS = KGPBLKS)
CASE ('DEAR')
  CALL DEAR_MANYBLOCKS (D, CST, TURBN, KRR, KRRI, .FALSE., OCOMPUTE_SRC, .FALSE&
  &., ZLM, PRT, PDZZ, PZZ, PTKET, PTHVREF, PTHLT, ZLOCPEXNM, PSRCT, ZAMOIST,&
  & PDIRCOSZW, PDXX, PDYY, ZATHETA, LDACC = LDACC, KGPBLKS = KGPBLKS)
CASE ('BLKR')
  ZL0=100.
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZLM (JI, JK, JBLK)=ZL0
      
      ENDDO

    ENDDO

  ENDDO

  ZALPHA=0.5**(-1.5)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=IKTB, IKTE
        
        ZLM (JI, JK, JBLK)=(0.5*(PZZ (JI, JK, JBLK)+PZZ (JI, JK+IKL, JBLK&
        &))-PZZ (JI, IKA+JPVEXT_TURB*IKL, JBLK))*PDIRCOSZW (JI, JBLK)
        ZLM (JI, JK, JBLK)=ZALPHA*ZLM (JI, JK, JBLK)*ZL0/(ZL0+ZALPHA*ZLM (JI, JK, JBLK))
      
      ENDDO

      
      ZLM (JI, IKTB-1, JBLK)=ZLM (JI, IKTB, JBLK)
      ZLM (JI, IKTE+1, JBLK)=ZLM (JI, IKTE, JBLK)
    
    ENDDO

  ENDDO

  
ENDSELECT


IF (OCLOUDMODIFLM)  THEN
  CALL CLOUD_MODIF_LM_MANYBLOCKS (D, CST, CSTURB, TURBN, TPFILE, TZFIELD, KRR, KRRI, OCLOUDMODIFLM&
  &, .FALSE., OCOMPUTE_SRC, .FALSE., HTURBLEN_CL, PDZZ, PDXX, PDYY, PZZ, PRT, PTKET, PTHLT&
  &, ZTHLM, ZRM, PTHVREF, ZLOCPEXNM, PSRCT, PCOEF_AMPL_SAT, ZAMOIST, ZATHETA, PDIRCOSZW&
  &, PCEI, PCEI_MIN, PCEI_MAX, ZLM, LDACC = LDACC, KGPBLKS = KGPBLKS)
ENDIF




!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI, JK) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

    DO JK=1, IKT
      
      ZLEPS (JI, JK, JBLK)=ZLM (JI, JK, JBLK)
    
    ENDDO

    
    ZLMO (JI, JBLK)=XUNDEF
  
  ENDDO

ENDDO




IF (TURBN%CTURBLEN=='HM21') THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZLEPS (JI, JK, JBLK)=MIN (ZLEPS (JI, JK, JBLK), ZLMW (JI, JK, JBLK)*TURBN%XCADAP)
      
      ENDDO

    ENDDO

  ENDDO

ENDIF




IF (TURBN%LROTATE_WIND) THEN
ELSE
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      ZUSLOPE (JI, JBLK)=PUT (JI, IKA, JBLK)
      ZVSLOPE (JI, JBLK)=PVT (JI, IKA, JBLK)
    ENDDO

  ENDDO

  
ENDIF



!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    
    ZCDUEFF (JI, JBLK)=-SQRT ((PSFU (JI, JBLK)**2+PSFV (JI, JBLK)**2)&
    &/(CST%XMNH_TINY+ZUSLOPE (JI, JBLK)**2+ZVSLOPE (JI, JBLK)**2))
    
    
    ZTAU11M (JI, JBLK)=2./3.*((1.+(PZZ (JI, IKB+IKL, JBLK)-PZZ (JI, IKB, JBLK))/(PDZZ (JI, IKB&
    &+IKL, JBLK)+PDZZ (JI, IKB, JBLK)))*PTKET (JI, IKB, JBLK)-0.5*PTKET (JI, IKB+IKL, JBLK))
    
    ZTAU12M (JI, JBLK)=0.0
    ZTAU22M (JI, JBLK)=ZTAU11M (JI, JBLK)
    ZTAU33M (JI, JBLK)=ZTAU11M (JI, JBLK)
    ZMWTH (JI,:, JBLK)=0.
    ZMWR (JI,:, JBLK)=0.
    ZMTH2 (JI,:, JBLK)=0.
    ZMR2 (JI,:, JBLK)=0.
    ZMTHR (JI,:, JBLK)=0.
    ZFWTH (JI,:, JBLK)=0.
    ZFWR (JI,:, JBLK)=0.
    ZFTH2 (JI,:, JBLK)=0.
    ZFR2 (JI,:, JBLK)=0.
    ZFTHR (JI,:, JBLK)=0.
  ENDDO

ENDDO


CALL TURB_VER_MANYBLOCKS (D, CST, CSTURB, TURBN, NEBN, TLES, KRR, KRRL, KRRI, KGRADIENTSLEO, &
&.FALSE., ODEEPOC, OCOMPUTE_SRC, ISV, KSV_LGBEG, KSV_LGEND, ZEXPL, .FALSE., ONOMIXLG, .FALSE.&
&, OCOUPLES, OBLOWSNOW, .FALSE., PRSNOW, PTSTEP, TPFILE, PDXX, PDYY, PDZZ, PDZX, PDZY, PDIRCOSZW&
&, PZZ, PCOSSLOPE, PSINSLOPE, PRHODJ, PTHVREF, PSFU, PSFV, PSFTH, PSFRV, ZWORKSFSV, PSFTH, PSFRV&
&, ZWORKSFSV, ZCDUEFF, ZTAU11M, ZTAU12M, ZTAU33M, PUT, PVT, PWT, ZUSLOPE, ZVSLOPE, PTHLT, PRT&
&, ZWORKT, PTKET, ZLM, PLENGTHM, PLENGTHH, ZLEPS, MFMOIST, ZLOCPEXNM, ZATHETA, ZAMOIST, PSRCT&
&, ZFRAC_ICE, ZFWTH, ZFWR, ZFTH2, ZFR2, ZFTHR, PBL_DEPTH, PSBL_DEPTH, ZLMO, PHGRADLEO, PZS, PRUS&
&, PRVS, PRWS, PRTHLS, PRRS, ZWORKS, PDP, PTP, PSIGS, PWTH, PWRC, PSSTFL, PSSTFL_C,&
& PSSRFL_C, PSSUFL_C, PSSVFL_C, PSSUFL, PSSVFL, LDACC = LDACC, KGPBLKS = KGPBLKS)

IF (TURBN%LTURB_PRECIP) THEN

  IF (KRR.GE.3)  THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
        PRRS (JI,:, 3, JBLK)=ZWORKS (JI,:, KSV+3, JBLK)
      ENDDO

    ENDDO

  ENDIF


  IF (KRR.GE.5)  THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
        PRRS (JI,:, 5, JBLK)=ZWORKS (JI,:, KSV+5, JBLK)
      ENDDO

    ENDDO

  ENDIF


  IF (KRR.GE.6)  THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
        PRRS (JI,:, 6, JBLK)=ZWORKS (JI,:, KSV+6, JBLK)
      ENDDO

    ENDDO

  ENDIF


  IF (KRR.GE.7)  THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
        PRRS (JI,:, 7, JBLK)=ZWORKS (JI,:, KSV+7, JBLK)
      ENDDO

    ENDDO

  ENDIF

ENDIF


IF (TURBN%LTURB_PRECIP) THEN

  IF (KRR.GE.3)  THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
        PRRS (JI,:, 3, JBLK)=ZWORKS (JI,:, KSV+3, JBLK)
      ENDDO

    ENDDO

  ENDIF


  IF (KRR.GE.5)  THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
        PRRS (JI,:, 5, JBLK)=ZWORKS (JI,:, KSV+5, JBLK)
      ENDDO

    ENDDO

  ENDIF


  IF (KRR.GE.6)  THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
        PRRS (JI,:, 6, JBLK)=ZWORKS (JI,:, KSV+6, JBLK)
      ENDDO

    ENDDO

  ENDIF


  IF (KRR.GE.7)  THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
        PRRS (JI,:, 7, JBLK)=ZWORKS (JI,:, KSV+7, JBLK)
      ENDDO

    ENDDO

  ENDIF

ENDIF


IF (TURBN%LTHERMMF) THEN
  CALL MZF_PHY_MANYBLOCKS (D, PFLXZTHVMF, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        PTP (JI, JK, JBLK)=PTP (JI, JK, JBLK)+CST%XG/PTHVREF (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO


  IF (PRESENT (PTPMF)) THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          PTPMF (JI, JK, JBLK)=CST%XG/PTHVREF (JI, JK, JBLK)*ZWORK1 (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF

ELSEIF (PRESENT (PTPMF)) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      PTPMF (JI, 1:IKT, JBLK)=0.
    ENDDO

  ENDDO

ENDIF


IF (TURBN%LDYNMF) THEN
  CALL GZ_U_UW_PHY_MANYBLOCKS (D, PUT, PDZZ, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL MXF_PHY_MANYBLOCKS (D, ZWORK1, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZWORK1 (JI, JK, JBLK)=ZWORK2 (JI, JK, JBLK)*PFLXZUMF (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

  CALL MZF_PHY_MANYBLOCKS (D, ZWORK1, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        PDP (JI, JK, JBLK)=PDP (JI, JK, JBLK)-ZWORK2 (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO


  IF (PRESENT (PDPMF)) THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          PDPMF (JI, JK, JBLK)=-ZWORK2 (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF

  CALL GZ_V_VW_PHY_MANYBLOCKS (D, PVT, PDZZ, ZWORK1, LDACC = LDACC, KGPBLKS = KGPBLKS)
  CALL MXF_PHY_MANYBLOCKS (D, ZWORK1, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        ZWORK1 (JI, JK, JBLK)=ZWORK2 (JI, JK, JBLK)*PFLXZVMF (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

  CALL MZF_PHY_MANYBLOCKS (D, ZWORK1, ZWORK2, LDACC = LDACC, KGPBLKS = KGPBLKS)
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        PDP (JI, JK, JBLK)=PDP (JI, JK, JBLK)-ZWORK2 (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO


  IF (PRESENT (PDPMF)) THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          PDPMF (JI, JK, JBLK)=PDPMF (JI, JK, JBLK)-ZWORK2 (JI, JK, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF

ELSEIF (PRESENT (PDPMF)) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      PDPMF (JI, 1:IKT, JBLK)=0.
    ENDDO

  ENDDO

ENDIF


IF (TURBN%LGOGER) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        PDP (JI, JK, JBLK)=PDP (JI, JK, JBLK)+TURBN%XSMAG**2*PDXX (JI, JK, JBLK)*PDYY (JI, JK&
        &, JBLK)*(PHGRADGOG (JI, JK, 1, JBLK)*PHGRADGOG (JI, JK, 1, JBLK)+PHGRADGOG (JI, JK, 4&
        &, JBLK)*PHGRADGOG (JI, JK, 4, JBLK)+0.5*(PHGRADGOG (JI, JK, 2, JBLK)+PHGRADGOG (JI, JK&
        &, 3, JBLK))*(PHGRADGOG (JI, JK, 2, JBLK)+PHGRADGOG (JI, JK, 3, JBLK)))**(3./2.)
      
      ENDDO

    ENDDO

  ENDDO

ENDIF



IF (PRESENT (PRTKEMS)) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      ZRTKEMS (JI,:, JBLK)=PRTKEMS (JI,:, JBLK)
    ENDDO

  ENDDO

ELSE
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      ZRTKEMS (JI,:, JBLK)=0.
    ENDDO

  ENDDO

ENDIF

CALL TKE_EPS_SOURCES_MANYBLOCKS (D, CST, CSTURB, TURBN, TLES, PTKET, ZLM, ZLEPS, PDP, ZTRH,&
& PRHODJ, PDZZ, PDXX, PDYY, PDZX, PDZY, PZZ, PTSTEP, ZEXPL, TPFILE, .FALSE., .FALSE., PSFU,&
& PSFV, PTP, PRTKES, PRTHLS, ZCOEF_DISS, PTDIFF, PTDISS, ZRTKEMS, KBUDGETS, PEDR=PEDR, PTR=PTR&
&, PDISS=PDISS, PCURRENT_TKE_DISS=PCURRENT_TKE_DISS, LDACC = LDACC, KGPBLKS = KGPBLKS)



!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (D%NIT) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JI) 

  

  DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
    PRSVS (JI,:,:, JBLK)=ZWORKS (JI,:, 1:KSV, JBLK)
  ENDDO

ENDDO



IF (PRESENT (PDRUS_TURB)) THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI, JK) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

      DO JK=1, IKT
        
        PDRUS_TURB (JI, JK, JBLK)=PRUS (JI, JK, JBLK)-PDRUS_TURB (JI, JK, JBLK)
        PDRVS_TURB (JI, JK, JBLK)=PRVS (JI, JK, JBLK)-PDRVS_TURB (JI, JK, JBLK)
        PDRTHLS_TURB (JI, JK, JBLK)=PRTHLS (JI, JK, JBLK)-PDRTHLS_TURB (JI, JK, JBLK)
        PDRRTS_TURB (JI, JK, JBLK)=PRRS (JI, JK, 1, JBLK)-PDRRTS_TURB (JI, JK, JBLK)
      
      ENDDO

    ENDDO

  ENDDO


  DO JSV=1, KSV
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          PDRSVS_TURB (JI, JK, JSV, JBLK)=PRSVS (JI, JK, JSV, JBLK)-PDRSVS_TURB (JI, JK, JSV, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDDO

ENDIF


IF (KRRL>=1) THEN

  IF (KRRI>=1) THEN
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          PRT (JI, JK, 1, JBLK)=PRT (JI, JK, 1, JBLK)-PRT (JI, JK, 2, JBLK)-PRT (JI, JK, 4, JBLK)
          PRRS (JI, JK, 1, JBLK)=PRRS (JI, JK, 1, JBLK)-PRRS (JI, JK, 2, JBLK)-PRRS (JI, JK, 4, JBLK)
          PTHLT (JI, JK, JBLK)=PTHLT (JI, JK, JBLK)+ZLVOCPEXNM (JI, JK, JBLK)*PRT&
          & (JI, JK, 2, JBLK)+ZLSOCPEXNM (JI, JK, JBLK)*PRT (JI, JK, 4, JBLK)
          PRTHLS (JI, JK, JBLK)=PRTHLS (JI, JK, JBLK)+ZLVOCPEXNM (JI, JK, JBLK)*PRRS&
          & (JI, JK, 2, JBLK)+ZLSOCPEXNM (JI, JK, JBLK)*PRRS (JI, JK, 4, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ELSE
    
    !$ACC PARALLEL LOOP GANG &
    !$ACC&IF (LDACC) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (D%NIT) 

    

    DO JBLK = 1, KGPBLKS
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JI, JK) 

      

      DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)

        DO JK=1, IKT
          
          PRT (JI, JK, 1, JBLK)=PRT (JI, JK, 1, JBLK)-PRT (JI, JK, 2, JBLK)
          PRRS (JI, JK, 1, JBLK)=PRRS (JI, JK, 1, JBLK)-PRRS (JI, JK, 2, JBLK)
          PTHLT (JI, JK, JBLK)=PTHLT (JI, JK, JBLK)+ZLOCPEXNM (JI, JK, JBLK)*PRT (JI, JK, 2, JBLK)
          PRTHLS (JI, JK, JBLK)=PRTHLS (JI, JK, JBLK)+ZLOCPEXNM (JI, JK, JBLK)*PRRS (JI, JK, 2, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF

ENDIF

!CALL SOURCES_NEG_CORRECT_PHY_MANYBLOCKS (D, KSV, HCLOUD, HELEC,'NETUR', KRR, PTSTEP&
!&, PPABST, PTHLT, PRT, PRTHLS, PRRS, PRSVS, LDACC = LDACC, KGPBLKS = KGPBLKS)

IF (PRESENT (PLEM))  THEN
  
  !$ACC PARALLEL LOOP GANG &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JBLK) &
  !$ACC&VECTOR_LENGTH (D%NIT) 

  

  DO JBLK = 1, KGPBLKS
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JI) 

    

    DO JI = D%NIB, MERGE (D%NIT, D%NIE, JBLK < KGPBLKS)
      PLEM (JI, IKTB:IKTE, JBLK)=ZLM (JI, IKTB:IKTE, JBLK)
    ENDDO

  ENDDO

ENDIF

IF (LHOOK) CALL DR_HOOK ('TURB_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

END SUBROUTINE TURB_MANYBLOCKS
