MODULE UTIL_TBUDGETDATA_MOD

USE MODD_BUDGET, ONLY : TBUDGETDATA









CONTAINS

SUBROUTINE ACDC_SAVE_TBUDGETDATA (SELF, KLUN)

IMPLICIT NONE
CLASS (TBUDGETDATA), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%NBUDGET
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TBUDGETDATA (SELF, KLUN)

IMPLICIT NONE
CLASS (TBUDGETDATA), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%NBUDGET
END SUBROUTINE

SUBROUTINE ACDC_COPY_TBUDGETDATA (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TBUDGETDATA), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE







SUBROUTINE ACDC_WIPE_TBUDGETDATA (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TBUDGETDATA), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
