MODULE UTIL_TBUDGETCONF_T_MOD

USE MODD_BUDGET, ONLY : TBUDGETCONF_T

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TBUDGETCONF_T
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TBUDGETCONF_T
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TBUDGETCONF_T
END INTERFACE




INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TBUDGETCONF_T
END INTERFACE


CONTAINS

SUBROUTINE ACDC_SAVE_TBUDGETCONF_T (SELF, KLUN)

IMPLICIT NONE
TYPE (TBUDGETCONF_T), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%LBU_ENABLE
WRITE (KLUN) SELF%LBUDGET_U
WRITE (KLUN) SELF%LBUDGET_V
WRITE (KLUN) SELF%LBUDGET_W
WRITE (KLUN) SELF%LBUDGET_TH
WRITE (KLUN) SELF%LBUDGET_TKE
WRITE (KLUN) SELF%LBUDGET_RV
WRITE (KLUN) SELF%LBUDGET_RC
WRITE (KLUN) SELF%LBUDGET_RR
WRITE (KLUN) SELF%LBUDGET_RI
WRITE (KLUN) SELF%LBUDGET_RS
WRITE (KLUN) SELF%LBUDGET_RG
WRITE (KLUN) SELF%LBUDGET_RH
WRITE (KLUN) SELF%LBUDGET_SV
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TBUDGETCONF_T (SELF, KLUN)

IMPLICIT NONE
TYPE (TBUDGETCONF_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%LBU_ENABLE
READ (KLUN) SELF%LBUDGET_U
READ (KLUN) SELF%LBUDGET_V
READ (KLUN) SELF%LBUDGET_W
READ (KLUN) SELF%LBUDGET_TH
READ (KLUN) SELF%LBUDGET_TKE
READ (KLUN) SELF%LBUDGET_RV
READ (KLUN) SELF%LBUDGET_RC
READ (KLUN) SELF%LBUDGET_RR
READ (KLUN) SELF%LBUDGET_RI
READ (KLUN) SELF%LBUDGET_RS
READ (KLUN) SELF%LBUDGET_RG
READ (KLUN) SELF%LBUDGET_RH
READ (KLUN) SELF%LBUDGET_SV
END SUBROUTINE

SUBROUTINE ACDC_COPY_TBUDGETCONF_T (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TBUDGETCONF_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE







SUBROUTINE ACDC_WIPE_TBUDGETCONF_T (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TBUDGETCONF_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
