MODULE UTIL_TBUDGETDATA_PTR_MOD

USE MODD_BUDGET, ONLY : TBUDGETDATA_PTR

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TBUDGETDATA_PTR
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TBUDGETDATA_PTR
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TBUDGETDATA_PTR
END INTERFACE




INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TBUDGETDATA_PTR
END INTERFACE


CONTAINS

SUBROUTINE ACDC_SAVE_TBUDGETDATA_PTR (SELF, KLUN)
USE UTIL_TBUDGETDATA_MOD
IMPLICIT NONE
TYPE (TBUDGETDATA_PTR), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LPTR
LPTR = ASSOCIATED (SELF%PTR)
WRITE (KLUN) LPTR
IF (LPTR) THEN
  CALL ACDC_SAVE_TBUDGETDATA (SELF%PTR, KLUN)
ENDIF
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TBUDGETDATA_PTR (SELF, KLUN)
USE UTIL_TBUDGETDATA_MOD
IMPLICIT NONE
TYPE (TBUDGETDATA_PTR), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LPTR
READ (KLUN) LPTR
IF (LPTR) THEN
  ALLOCATE (SELF%PTR)
  CALL ACDC_LOAD_TBUDGETDATA (SELF%PTR, KLUN)
ELSE
  NULLIFY (SELF%PTR)
ENDIF
END SUBROUTINE

SUBROUTINE ACDC_COPY_TBUDGETDATA_PTR (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_TBUDGETDATA_MOD
IMPLICIT NONE
TYPE (TBUDGETDATA_PTR), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LPTR
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LPTR = ASSOCIATED (SELF%PTR)
IF (LPTR) THEN
  !$ACC ENTER DATA CREATE (SELF%PTR)
  !$ACC UPDATE DEVICE (SELF%PTR)
  CALL ACDC_COPY_TBUDGETDATA (SELF%PTR, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (SELF%PTR)
ENDIF

END SUBROUTINE







SUBROUTINE ACDC_WIPE_TBUDGETDATA_PTR (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_TBUDGETDATA_MOD
IMPLICIT NONE
TYPE (TBUDGETDATA_PTR), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LPTR
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LPTR = ASSOCIATED (SELF%PTR)
IF (LPTR) THEN
  !$ACC EXIT DATA DETACH (SELF%PTR)
  CALL ACDC_WIPE_TBUDGETDATA (SELF%PTR, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DELETE (SELF%PTR)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
