MODULE UTIL_CSTURB_T_MOD

USE MODD_CTURB, ONLY : CSTURB_T

INTERFACE SAVE
MODULE PROCEDURE SAVE_CSTURB_T
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_CSTURB_T
END INTERFACE



     




CONTAINS

SUBROUTINE SAVE_CSTURB_T (SELF, KLUN)

IMPLICIT NONE
TYPE (CSTURB_T), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%XCMFS
WRITE (KLUN) SELF%XCMFB
WRITE (KLUN) SELF%XCPR2
WRITE (KLUN) SELF%XCPR3
WRITE (KLUN) SELF%XCPR4
WRITE (KLUN) SELF%XCPR5
WRITE (KLUN) SELF%XCET
WRITE (KLUN) SELF%XCDP
WRITE (KLUN) SELF%XCDD
WRITE (KLUN) SELF%XCDT
WRITE (KLUN) SELF%XRM17
WRITE (KLUN) SELF%XLINF
WRITE (KLUN) SELF%XALPSBL
WRITE (KLUN) SELF%XCEP
WRITE (KLUN) SELF%XA0
WRITE (KLUN) SELF%XA2
WRITE (KLUN) SELF%XA3
WRITE (KLUN) SELF%XA5
WRITE (KLUN) SELF%XCTD
WRITE (KLUN) SELF%XPHI_LIM
WRITE (KLUN) SELF%XSBL_O_BL
WRITE (KLUN) SELF%XFTOP_O_FSURF
END SUBROUTINE

SUBROUTINE LOAD_CSTURB_T (SELF, KLUN)

IMPLICIT NONE
TYPE (CSTURB_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%XCMFS
READ (KLUN) SELF%XCMFB
READ (KLUN) SELF%XCPR2
READ (KLUN) SELF%XCPR3
READ (KLUN) SELF%XCPR4
READ (KLUN) SELF%XCPR5
READ (KLUN) SELF%XCET
READ (KLUN) SELF%XCDP
READ (KLUN) SELF%XCDD
READ (KLUN) SELF%XCDT
READ (KLUN) SELF%XRM17
READ (KLUN) SELF%XLINF
READ (KLUN) SELF%XALPSBL
READ (KLUN) SELF%XCEP
READ (KLUN) SELF%XA0
READ (KLUN) SELF%XA2
READ (KLUN) SELF%XA3
READ (KLUN) SELF%XA5
READ (KLUN) SELF%XCTD
READ (KLUN) SELF%XPHI_LIM
READ (KLUN) SELF%XSBL_O_BL
READ (KLUN) SELF%XFTOP_O_FSURF
END SUBROUTINE






     







END MODULE
