MODULE UTIL_NEB_T_MOD

USE MODD_NEB_n, ONLY : NEB_T

INTERFACE SAVE
MODULE PROCEDURE SAVE_NEB_T
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_NEB_T
END INTERFACE



     




CONTAINS

SUBROUTINE SAVE_NEB_T (SELF, KLUN)

IMPLICIT NONE
TYPE (NEB_T), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%XTMINMIX
WRITE (KLUN) SELF%XTMAXMIX
WRITE (KLUN) SELF%LHGT_QS
WRITE (KLUN) SELF%CFRAC_ICE_ADJUST
WRITE (KLUN) SELF%CFRAC_ICE_SHALLOW_MF
WRITE (KLUN) SELF%VSIGQSAT
WRITE (KLUN) SELF%CCONDENS
WRITE (KLUN) SELF%CLAMBDA3
WRITE (KLUN) SELF%LSTATNW
WRITE (KLUN) SELF%LSIGMAS
WRITE (KLUN) SELF%LSUBG_COND
WRITE (KLUN) SELF%LCONDBORN
END SUBROUTINE

SUBROUTINE LOAD_NEB_T (SELF, KLUN)

IMPLICIT NONE
TYPE (NEB_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%XTMINMIX
READ (KLUN) SELF%XTMAXMIX
READ (KLUN) SELF%LHGT_QS
READ (KLUN) SELF%CFRAC_ICE_ADJUST
READ (KLUN) SELF%CFRAC_ICE_SHALLOW_MF
READ (KLUN) SELF%VSIGQSAT
READ (KLUN) SELF%CCONDENS
READ (KLUN) SELF%CLAMBDA3
READ (KLUN) SELF%LSTATNW
READ (KLUN) SELF%LSIGMAS
READ (KLUN) SELF%LSUBG_COND
READ (KLUN) SELF%LCONDBORN
END SUBROUTINE






     







END MODULE
